### ISSUE TITLE
telebot error

### ISSUE THREAD

**Issue by soundaraj** [deepmipt/DeepPavlov#1002]
ERROR - TeleBot: "IndexError occurred, args=('index 0 is out of bounds for axis 0 with size 0',)
`Traceback (most recent call last):
  File "/home/user4/env2/lib/python3.6/site-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/utils/telegram/telegram_ui.py", line 61, in handle_inference
    response: RichMessage = agent([context], [chat_id])[0]
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/core/agent/agent.py", line 72, in __call__
    responses_batch = self._call(utterances_batch, utterances_ids)
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/agents/default_agent/default_agent.py", line 86, in _call
    predicted, confidence = skill(skill_i_utt_batch, skill_i_utt_ids)
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/core/agent/agent.py", line 146, in __call__
    predicted, confidence, *states = self.skill(utterances_batch, history_batch, states_batch)
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/skills/default_skill/default_skill.py", line 84, in __call__
    infer_results = self.model(*infer_utterances)
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/core/common/chainer.py", line 205, in __call__
    return self._compute(*args, param_names=self.in_x, pipe=self.pipe, targets=self.out_params)
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/core/common/chainer.py", line 228, in _compute
    res = component(*x)
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/models/go_bot/network.py", line 505, in __call__
    self._infer(tokens, state=state)
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/core/models/tf_backend.py", line 27, in _wrapped
    return func(*args, **kwargs)
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/models/go_bot/network.py", line 434, in _infer
    features, emb_context, key = self._encode_context(tokens, state=state)
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/core/models/tf_backend.py", line 27, in _wrapped
    return func(*args, **kwargs)
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/models/go_bot/network.py", line 260, in _encode_context
    bow_features = self.bow_embedder([tokens_idx])[0]
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/models/embedders/bow_embedder.py", line 58, in __call__
    return [self._encode(sample) for sample in batch]
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/models/embedders/bow_embedder.py", line 58, in <listcomp>
    return [self._encode(sample) for sample in batch]
  File "/home/user4/env2/lib/python3.6/site-packages/deeppavlov/models/embedders/bow_embedder.py", line 52, in _encode
    bow[idx] += 1
IndexError: index 0 is out of bounds for axis 0 with size 0
"
`

**Comment by yoptar** [comment]
Hi @soundaraj,
Could you tell us, at what point this error occurred?
