### ISSUE TITLE
Bilstm_attention model got bad performance on published evaluation tasks about classification

### ISSUE THREAD

**Issue by ConnieTong** [deepmipt/DeepPavlov#1004]
Hi all,
I have evaluated all the classification models of deepavlov on published evaluation dataset. Bilstm_attention and Bigru_attention model got very bad performance (f1 score less than 20%) compared with other models.
Anyone encountered same problem? Please help me if you met the same problem with me. 

Thanks so much !

Bests,
Connie Tong

**Comment by ConnieTong** [comment]
Hi dilyararimovna,
Thanks for the quick reply. The evaluation dataset I used is NLPCC News Headline Categorization dataset (The conference on Natural Language Processing and Chinese Computing).  The training set is about 16,000, the dev set is about 30,000 and the test set is 5,000. 
Did you try to tune network parameters? -> Yes, I tuned network parameters.

Bests,
Connie

**Comment by ConnieTong** [comment]
Hi dilyararimovna,
There is another issue. Firstly, when I trained these two models, model can not saved during training procedure. I fixed it by modifying keras_classifier_model.py file:

checkpoint = callbacks.ModelCheckpoint(file_name, monitor=score_name, mode='max', save_best_only=True, save_weights_only=True, verbose=1)

The save model problem was solved. Then I met the bad performance of classification.

**Comment by dilyararimovna** [comment]
I supposed there should not be a problem in saving model if other network configurations were saved successfully.
What was the error when saving model in the beginnning?

**Comment by ConnieTong** [comment]
Epoch 1/100
2433/2433 [==============================] - 16615s 7s/step - loss: 1.4374 - multilabel_f1: nan - val_loss: 0.9758 - val_multilabel_f1: 0.6808

Epoch 00001: val_multilabel_f1 improved from -inf to 0.68078, saving model to /home/tongyu/vnf_evaluation/vivo_nlp_framework/models/classifiers/ch_anti_cls_bilstm_attention_tencent_char_test/model-01-nan-0.6808.h5
Traceback (most recent call last):
  File "main_bilstm_attention.py", line 195, in <module>
    main()
  File "main_bilstm_attention.py", line 97, in main
    start_epoch_num=start_epoch_num)
  File "/home/tongyu/vnf_evaluation/vivo_nlp_framework/vnf/core/commands/train.py", line 310, in train_evaluate_model_from_config
    model = fit_chainer(config, iterator, debug=debug, debugger_port=debugger_port)
  File "/home/tongyu/vnf_evaluation/vivo_nlp_framework/vnf/core/commands/train.py", line 143, in fit_chainer
    component.fit_batches(data_train, data_valid, config['train'])
  File "/home/tongyu/vnf_evaluation/vivo_nlp_framework/deeppavlov/core/models/tf_backend.py", line 39, in _wrapped
    return func(*args, **kwargs)
  File "/home/tongyu/vnf_evaluation/vivo_nlp_framework/vnf/models/classifiers/keras_classifier_model.py", line 260, in fit_batches
    self.fit_model(self.model, data, args)
  File "/home/tongyu/vnf_evaluation/vivo_nlp_framework/deeppavlov/core/models/tf_backend.py", line 39, in _wrapped
    return func(*args, **kwargs)
  File "/home/tongyu/vnf_evaluation/vivo_nlp_framework/vnf/models/classifiers/keras_classifier_model.py", line 286, in fit_model
    callbacks=self.gen_callbacks(args['batch_size'], args["validation_patience"], id))
  File "/home/tongyu/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/tongyu/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/tongyu/.local/lib/python3.6/site-packages/keras/engine/training_generator.py", line 229, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/tongyu/.local/lib/python3.6/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/tongyu/.local/lib/python3.6/site-packages/keras/callbacks.py", line 444, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/home/tongyu/.local/lib/python3.6/site-packages/keras/engine/network.py", line 1104, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/tongyu/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 117, in save_model
    'config': model.get_config()
  File "/home/tongyu/.local/lib/python3.6/site-packages/keras/engine/network.py", line 942, in get_config
    return copy.deepcopy(config)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/bin/anaconda3/envs/py36/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects
(py36)

**Comment by ConnieTong** [comment]
Hi dilyararimovna,
When the first epoch stops, I meet the save model problem as follows:
The error is "TypeError: can't pickle _thread.RLock objects"

**Comment by ConnieTong** [comment]
hi dilyararimovna,
Thanks so much. Yes, I also noticed that this error was caused by modifying the code.  Thanks again for your time.

**Comment by dilyararimovna** [comment]
Connie, you are welcome!
