### ISSUE TITLE
How to retrain an existing NER model that was trained by using DeepPavlov?

### ISSUE THREAD

**Issue by DLNSimha** [deepmipt/DeepPavlov#1044]
If I want to retrain this existing NER model by extending the data on the train.txt file, How should I proceed?

**Comment by vikmary** [comment]
Hi!
1) Firstly, download the original dataset:
`python3 -m deeppavlov download ner_model_config`
2) Then open the config file (search in https://github.com/deepmipt/DeepPavlov/tree/master/deeppavlov/configs/ner)  and find the value of the "data_path" parameter. It should be something like `{DOWNLOADS_PATH}/<datasetname>`. You then can open and edit training data on path `~/.deeppavlov/downloads/<datasetname>/train.txt`.
3) To not load pretrained model you have to change every `load_path` and `save_path` to an empty directory, where you want to place the trained model.

This will work for the case if you want to train a new model from scratch on new data.

**Comment by vikmary** [comment]
Yes, if you don't change values of `load_path` in config file, the model will be initialized from previous saved model and will continue training.

**Comment by shivambatra76** [comment]
I am facing the issue where i want to train the already pretrained model "ner_ontonotes_bert_multi"
I have created three files train,test and valid with the same format and placed in some other folder.
""' This is the code 
import json
from deeppavlov import configs,train_model

with configs.ner.ner_ontonotes_bert.open(encoding='utf8') as f:
    ner_config = json.load(f)

ner_config['dataset_reader']['data_path']='data'
train_model(ner_config)

"""
This is the Error message i am getting:
"""
InvalidArgumentError                      Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1349       return self._call_tf_sessionrun(options, feed_dict, fetch_list,
-> 1350                                       target_list, run_metadata)
   1351 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1442                                             fetch_list, target_list,
-> 1443                                             run_metadata)
   1444 

InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [17,17] rhs shape= [37,37]
	 [[{{node save/Assign_76}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py in restore(self, sess, save_path)
   1289         sess.run(self.saver_def.restore_op_name,
-> 1290                  {self.saver_def.filename_tensor_name: save_path})
   1291     except errors.NotFoundError as err:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    955       result = self._run(None, fetches, feed_dict, options_ptr,
--> 956                          run_metadata_ptr)
    957       if run_metadata:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1179       results = self._do_run(handle, final_targets, final_fetches,
-> 1180                              feed_dict_tensor, options, run_metadata)
   1181     else:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1358       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1359                            run_metadata)
   1360     else:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py in _do_call(self, fn, *args)
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 

InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [17,17] rhs shape= [37,37]
	 [[node save/Assign_76 (defined at C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'save/Assign_76':
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2854, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2880, in _run_cell
    return runner(coro)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3057, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3248, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-1a6343ceae83>", line 1, in <module>
    train_model(ner_config)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\__init__.py", line 32, in train_model
    train_evaluate_model_from_config(config, download=download, recursive=recursive)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\commands\train.py", line 121, in train_evaluate_model_from_config
    trainer.train(iterator)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\trainers\nn_trainer.py", line 333, in train
    self.fit_chainer(iterator)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\trainers\fit_trainer.py", line 104, in fit_chainer
    component = from_params(component_config, mode='train')
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\common\params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_backend.py", line 76, in __call__
    obj.__init__(*args, **kwargs)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py", line 529, in __init__
    **kwargs)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py", line 259, in __init__
    self.load()
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py", line 457, in load
    return super().load(exclude_scopes=exclude_scopes, **kwargs)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_model.py", line 251, in load
    return super().load(exclude_scopes=exclude_scopes, **kwargs)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_model.py", line 54, in load
    saver = tf.train.Saver(var_list)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 350, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\training\saving\saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\ops\state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_state_ops.py", line 65, in assign
    use_locking=use_locking, name=name)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-6-1a6343ceae83> in <module>
----> 1 train_model(ner_config)

~\AppData\Roaming\Python\Python37\site-packages\deeppavlov\__init__.py in train_model(config, download, recursive)
     30     # TODO: make better
     31     def train_model(config: [str, Path, dict], download: bool = False, recursive: bool = False) -> Chainer:
---> 32         train_evaluate_model_from_config(config, download=download, recursive=recursive)
     33         return build_model(config, load_trained=True)
     34 

~\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\commands\train.py in train_evaluate_model_from_config(config, iterator, to_train, evaluation_targets, to_validate, download, start_epoch_num, recursive)
    119 
    120     if to_train:
--> 121         trainer.train(iterator)
    122 
    123     res = {}

~\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\trainers\nn_trainer.py in train(self, iterator)
    331     def train(self, iterator: DataLearningIterator) -> None:
    332         """Call :meth:`~fit_chainer` and then :meth:`~train_on_batches` with provided data iterator as an argument"""
--> 333         self.fit_chainer(iterator)
    334         if callable(getattr(self._chainer, 'train_on_batch', None)):
    335             try:

~\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\trainers\fit_trainer.py in fit_chainer(self, iterator)
    102             raise RuntimeError('Cannot fit already built chainer')
    103         for component_index, component_config in enumerate(self.chainer_config['pipe'], 1):
--> 104             component = from_params(component_config, mode='train')
    105             if 'fit_on' in component_config:
    106                 component: Estimator

~\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\common\params.py in from_params(params, mode, serialized, **kwargs)
    104                 kwargs['mode'] = mode
    105 
--> 106             component = obj(**dict(config_params, **kwargs))
    107             try:
    108                 _refs[config_params['id']] = component

~\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_backend.py in __call__(cls, *args, **kwargs)
     74                     wrapped_attr = _graph_wrap(attr, obj.graph)
     75                 setattr(obj, meth, wrapped_attr)
---> 76         obj.__init__(*args, **kwargs)
     77         return obj

~\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_backend.py in _wrapped(*args, **kwargs)
     26     def _wrapped(*args, **kwargs):
     27         with graph.as_default():
---> 28             return func(*args, **kwargs)
     29 
     30     return _wrapped

~\AppData\Roaming\Python\Python37\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py in __init__(self, n_tags, keep_prob, bert_config_file, pretrained_bert, attention_probs_keep_prob, hidden_keep_prob, use_crf, encoder_layer_ids, encoder_dropout, optimizer, weight_decay_rate, use_birnn, birnn_cell_type, birnn_hidden_size, ema_decay, ema_variables_on_cpu, return_probas, freeze_embeddings, learning_rate, bert_learning_rate, min_learning_rate, learning_rate_drop_patience, learning_rate_drop_div, load_before_drop, clip_norm, **kwargs)
    527                          load_before_drop=load_before_drop,
    528                          clip_norm=clip_norm,
--> 529                          **kwargs)
    530 
    531     def _init_graph(self) -> None:

~\AppData\Roaming\Python\Python37\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py in __init__(self, keep_prob, bert_config_file, pretrained_bert, attention_probs_keep_prob, hidden_keep_prob, encoder_layer_ids, encoder_dropout, optimizer, weight_decay_rate, ema_decay, ema_variables_on_cpu, freeze_embeddings, learning_rate, bert_learning_rate, min_learning_rate, learning_rate_drop_patience, learning_rate_drop_div, load_before_drop, clip_norm, **kwargs)
    257 
    258         if self.load_path is not None:
--> 259             self.load()
    260 
    261         if self.ema:

~\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_backend.py in _wrapped(*args, **kwargs)
     26     def _wrapped(*args, **kwargs):
     27         with graph.as_default():
---> 28             return func(*args, **kwargs)
     29 
     30     return _wrapped

~\AppData\Roaming\Python\Python37\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py in load(self, exclude_scopes, **kwargs)
    455                              'EMA/BackupVariables'),
    456              **kwargs) -> None:
--> 457         return super().load(exclude_scopes=exclude_scopes, **kwargs)
    458 
    459 

~\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_model.py in load(self, exclude_scopes, **kwargs)
    249                                                    'momentum'),
    250              **kwargs):
--> 251         return super().load(exclude_scopes=exclude_scopes, **kwargs)
    252 
    253     def process_event(self, *args, **kwargs):

~\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_model.py in load(self, exclude_scopes, path)
     53             var_list = self._get_saveable_variables(exclude_scopes)
     54             saver = tf.train.Saver(var_list)
---> 55             saver.restore(self.sess, path)
     56 
     57     def deserialize(self, weights: Iterable[Tuple[str, np.ndarray]]) -> None:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py in restore(self, sess, save_path)
   1324       # We add a more reasonable error message here to help users (b/110263146)
   1325       raise _wrap_restore_error_with_msg(
-> 1326           err, "a mismatch between the current graph and the graph")
   1327 
   1328   @staticmethod

InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [17,17] rhs shape= [37,37]
	 [[node save/Assign_76 (defined at C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'save/Assign_76':
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2854, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2880, in _run_cell
    return runner(coro)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3057, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3248, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-1a6343ceae83>", line 1, in <module>
    train_model(ner_config)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\__init__.py", line 32, in train_model
    train_evaluate_model_from_config(config, download=download, recursive=recursive)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\commands\train.py", line 121, in train_evaluate_model_from_config
    trainer.train(iterator)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\trainers\nn_trainer.py", line 333, in train
    self.fit_chainer(iterator)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\trainers\fit_trainer.py", line 104, in fit_chainer
    component = from_params(component_config, mode='train')
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\common\params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_backend.py", line 76, in __call__
    obj.__init__(*args, **kwargs)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py", line 529, in __init__
    **kwargs)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py", line 259, in __init__
    self.load()
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py", line 457, in load
    return super().load(exclude_scopes=exclude_scopes, **kwargs)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_model.py", line 251, in load
    return super().load(exclude_scopes=exclude_scopes, **kwargs)
  File "C:\Users\GSC-30397\AppData\Roaming\Python\Python37\site-packages\deeppavlov\core\models\tf_model.py", line 54, in load
    saver = tf.train.Saver(var_list)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 350, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\training\saving\saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\ops\state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_state_ops.py", line 65, in assign
    use_locking=use_locking, name=name)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Users\GSC-30397\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
""""

**Comment by yoptar** [comment]
Hi @shivambatra76,
If you have a different set of tags, you should train your model from scratch. The amount of different tag types affects the model structure, that's why you're getting this error.

**Comment by shivambatra76** [comment]
hi @yoptar 
I dont want to add new tags I just want to improve the old ones .For example ,B-Person does not identifies the Indian Names so i just wanted to train the model with Indian names.

**Comment by yoptar** [comment]
@shivambatra76,
Then I advise you to merge your data with the base dataset and still train from scratch. If your really don't want to do that and are sure that you have a subset of original tag types, you can remove the `"fit_on": ["y"],` line from the config description of the `tag_vocab` component. But that way the model can forget something.
