### ISSUE TITLE
Key squad/output_bias not found in checkpoint

### ISSUE THREAD

**Issue by praneethgb** [deepmipt/DeepPavlov#1091]
Hi,

I am trying to load the BERT model finetuned on the Squad 2.0 data set by providing the path of the model checkpoint in squad_bert.json. 

 "save_path": "{DOWNLOADS_PATH}/bert_models/cased_L-12_H-768_A-12/model.ckpt-8144",
        "load_path": "{DOWNLOADS_PATH}/bert_models/cased_L-12_H-768_A-12/model.ckpt-8144",

I am getting the below error: 

Traceback (most recent call last):
  File "/anaconda3/envs/QandA/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/anaconda3/envs/QandA/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/anaconda3/envs/QandA/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key squad/output_bias not found in checkpoint
	 [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/QandA/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/anaconda3/envs/QandA/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/anaconda3/envs/QandA/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/anaconda3/envs/QandA/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/anaconda3/envs/QandA/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key squad/output_bias not found in checkpoint
	 [[node save/RestoreV2 (defined at anaconda3/envs/QandA/lib/python3.6/site-packages/deeppavlov/core/models/tf_model.py:55) ]]

Before looking into deeper, I want to check with the DeepPavlov team about the support of the BERT finetuned model on Squad 2.0 dataset already present to leverage it or Can you guys help me with the above issue?

**Comment by yurakuratov** [comment]
Hi!
Can you give some more details on how you you built `model.ckpt-8144` file? Is it result of pre-training BERT with MLM and NSP tasks (tasks that Google originally used to pre-train BERT on text data) on SQuAD 2.0 data? Or is it result of training BERT on QA task on SQuAD 2.0 data?

To be more clear why this is important let's take a look into [squad_bert.json](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/squad/squad_bert.json) file: 
`pretrained_bert ` parameter is a general purpose pre-trained BERT (e.g., Google's one).
`save_path`/`load_path` is a path to model trained on QA task to be saved/loaded.

About an error message: it says that there are no parameters for QA task in your checkpoint.

**Comment by praneethgb** [comment]
Hi @yurakuratov,

I am using this open-source model: https://ngc.nvidia.com/catalog/models/nvidia:bert_tf_v2_base_fp16_384

**Comment by yurakuratov** [comment]
This checkpoint is not compatible with our implementation of BERT for SQuAD.

To load this checkpoint you have to build exactly the same graph as NVIDIA used in `run_squad.py:587-625` (from here: https://ngc.nvidia.com/catalog/model-scripts/nvidia:bert_for_tensorflow/files), e.g. change Tensorflow graph defenition in implementation of [BertSQuADModel](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/models/bert/bert_squad.py#L38).
