### ISSUE TITLE
ValueError: invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by AI-4** [deepmipt/DeepPavlov#1093]
```
2019-12-05 23:29:44.356 ERROR in 'deeppavlov.core.common.params'['params'] at line 110: Exception in <class 'deeppavlov.core.data.simple_vocab.SimpleVocabulary'>
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/chat_bot_test/lib/python3.7/site-packages/deeppavlov/core/common/params.py", line 104, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "/home/user/anaconda3/envs/chat_bot_test/lib/python3.7/site-packages/deeppavlov/core/data/simple_vocab.py", line 61, in __init__
    self.load()
  File "/home/user/anaconda3/envs/chat_bot_test/lib/python3.7/site-packages/deeppavlov/core/data/simple_vocab.py", line 117, in load
    counts.append(int(cnt))
ValueError: invalid literal for int() with base 10: ' Служба технической поддержки.\t8\n'
Traceback (most recent call last):
  File "/home/user/PycharmProjects/untitled5/main.py", line 10, in <module>
    train=True)
  File "/home/user/anaconda3/envs/chat_bot_test/lib/python3.7/site-packages/deeppavlov/contrib/skills/similarity_matching_skill/similarity_matching_skill.py", line 68, in __init__
    self.model = train_model(model_config, download=True)
  File "/home/user/anaconda3/envs/chat_bot_test/lib/python3.7/site-packages/deeppavlov/__init__.py", line 31, in train_model
    train_evaluate_model_from_config(config, download=download, recursive=recursive)
  File "/home/user/anaconda3/envs/chat_bot_test/lib/python3.7/site-packages/deeppavlov/core/commands/train.py", line 137, in train_evaluate_model_from_config
    res = trainer.evaluate(iterator, evaluation_targets, print_reports=True)
  File "/home/user/anaconda3/envs/chat_bot_test/lib/python3.7/site-packages/deeppavlov/core/trainers/fit_trainer.py", line 251, in evaluate
    self._load()
  File "/home/user/anaconda3/envs/chat_bot_test/lib/python3.7/site-packages/deeppavlov/core/trainers/fit_trainer.py", line 157, in _load
    self._chainer = build_model({'chainer': self.chainer_config}, load_trained=self._saved)
  File "/home/user/anaconda3/envs/chat_bot_test/lib/python3.7/site-packages/deeppavlov/core/commands/infer.py", line 61, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "/home/user/anaconda3/envs/chat_bot_test/lib/python3.7/site-packages/deeppavlov/core/common/params.py", line 104, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "/home/user/anaconda3/envs/chat_bot_test/lib/python3.7/site-packages/deeppavlov/core/data/simple_vocab.py", line 61, in __init__
    self.load()
  File "/home/user/anaconda3/envs/chat_bot_test/lib/python3.7/site-packages/deeppavlov/core/data/simple_vocab.py", line 117, in load
    counts.append(int(cnt))
```
Why and how string cnt should be converted to int? ' Служба технической поддержки.\t8\n' is part of the one of answers in my dataset, which looks like:
```
Question,Answer
"Текст вопроса 1", "Текст ответа 1"
"Текст вопроса 2", "Текст ответа 2"
e.t.c.
```
My code looks like
```
faq = SimilarityMatchingSkill(data_path='/path_to_my_dataset/data.csv',
                              x_col_name='Question',
                              y_col_name='Answer',
                              save_load_path='./model_test',
                              config_type='tfidf_logreg_autofaq',
                              edit_dict={},
                              train=True)
...
print(faq(['Какой-то тестовый вопрос?'], [], []))
```

**Comment by yoptar** [comment]
Hi @AI-4,
This could be caused by tabulation and new lines in your texts. We'll try to fix this in future releases fut for now you can replace `\t` and `\n` in your questions and answers with a space.

**Comment by AI-4** [comment]
> Hi @AI-4,
> This could be caused by tabulation and new lines in your texts. We'll try to fix this in future releases fut for now you can replace `\t` and `\n` in your questions and answers with a space.

Yes, it was \t symbols. Answers with a space should be in roadmap, i think.
