### ISSUE TITLE
Problem with training my own TF-IDF Ranker on Windows 10.

### ISSUE THREAD

**Issue by matherialist** [deepmipt/DeepPavlov#1123]
Hello, I created my own config file based on ru_ranker_tfidf_wiki.json:
```
{
  "dataset_reader": {
    "class_name": "odqa_reader",
    "data_path": "~/Desktop/ODQA/train_data",
    "save_path": "~/Desktop/ODQA/tfidf.db",
    "dataset_format": "txt"
  },
  "dataset_iterator": {
    "class_name": "sqlite_iterator",
    "shuffle": false,
    "load_path": "~/Desktop/ODQA/tfidf.db"
  },
  "chainer": {
    "in": [
      "docs"
    ],
    "in_y": [
      "doc_ids",
      "doc_nums"
    ],
    "out": [
      "tfidf_doc_ids"
    ],
    "pipe": [
      {
        "class_name": "hashing_tfidf_vectorizer",
        "id": "vectorizer",
        "fit_on": [
          "docs",
          "doc_ids",
          "doc_nums"
        ],
        "save_path": "~/Desktop/ODQA/tfidf_matrix.npz",
        "load_path": "~/Desktop/ODQA/tfidf_matrix.npz",
        "tokenizer": {
          "class_name": "ru_tokenizer",
          "lemmas": true,
          "ngram_range": [
            1,
            2
          ]
        }
      },
      {
        "class_name": "tfidf_ranker",
        "top_n": 5,
        "in": [
          "docs"
        ],
        "out": [
          "tfidf_doc_ids",
          "tfidf_doc_scores"
        ],
        "vectorizer": "#vectorizer"
      }
    ]
  },
  "train": {
    "validate_best": false,
    "test_best": false,
    "batch_size": 10000
  },
  "metadata": {
    "variables": {
      "ROOT_PATH": "~/.deeppavlov",
      "DOWNLOADS_PATH": "{ROOT_PATH}/downloads",
      "MODELS_PATH": "{ROOT_PATH}/models"
    },
    "requirements": [],
    "labels": {
      "server_utils": "Ranker"
    }
  }
}
```
When I'm trying to train the ranker, I'm facing the next problem:
```
C:\Users\apantiuk\AppData\Local\Continuum\anaconda3\envs\bot_env\python.exe C:/Users/apantiuk/Desktop/ODQA/main.py
2020-01-28 13:41:46.721 INFO in 'deeppavlov.dataset_readers.odqa_reader'['odqa_reader'] at line 57: Reading files...
2020-01-28 13:41:46.722 INFO in 'deeppavlov.dataset_readers.odqa_reader'['odqa_reader'] at line 134: Building the database...
  0%|          | 0/300 [00:00<?, ?it/s]
0it [00:00, ?it/s]2020-01-28 13:41:48.416 INFO in 'deeppavlov.dataset_readers.odqa_reader'['odqa_reader'] at line 57: Reading files...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\apantiuk\AppData\Local\Continuum\anaconda3\envs\bot_env\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\apantiuk\AppData\Local\Continuum\anaconda3\envs\bot_env\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\apantiuk\AppData\Local\Continuum\anaconda3\envs\bot_env\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\apantiuk\AppData\Local\Continuum\anaconda3\envs\bot_env\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\apantiuk\AppData\Local\Continuum\anaconda3\envs\bot_env\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\apantiuk\AppData\Local\Continuum\anaconda3\envs\bot_env\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\apantiuk\AppData\Local\Continuum\anaconda3\envs\bot_env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\apantiuk\Desktop\ODQA\main.py", line 9, in <module>
    ranker = train_model(model_config)
  File "C:\Users\apantiuk\AppData\Local\Continuum\anaconda3\envs\bot_env\lib\site-packages\deeppavlov\__init__.py", line 32, in train_model
    train_evaluate_model_from_config(config, download=download, recursive=recursive)
  File "C:\Users\apantiuk\AppData\Local\Continuum\anaconda3\envs\bot_env\lib\site-packages\deeppavlov\core\commands\train.py", line 92, in train_evaluate_model_from_config
    data = read_data_by_config(config)
  File "C:\Users\apantiuk\AppData\Local\Continuum\anaconda3\envs\bot_env\lib\site-packages\deeppavlov\core\commands\train.py", line 58, in read_data_by_config
    return reader.read(data_path, **reader_config)
  File "C:\Users\apantiuk\AppData\Local\Continuum\anaconda3\envs\bot_env\lib\site-packages\deeppavlov\dataset_readers\odqa_reader.py", line 81, in read
    self._build_db(save_path, dataset_format, expand_path(data_path))
  File "C:\Users\apantiuk\AppData\Local\Continuum\anaconda3\envs\bot_env\lib\site-packages\deeppavlov\dataset_readers\odqa_reader.py", line 130, in _build_db
    Path(save_path).unlink()
  File "C:\Users\apantiuk\AppData\Local\Continuum\anaconda3\envs\bot_env\lib\pathlib.py", line 1294, in unlink
    self._accessor.unlink(self)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\apantiuk\\Desktop\\ODQA\\tfidf.db'
```
Execution of the program doesn't stop and goes into a loop while showing the error.
I runs into this problem only on my local Windows 10 Pro machine, everything  is fine on Google Colab.

**Comment by yoptar** [comment]
Hi @matherialist,
> `The process cannot access the file because it is being used by another process: 'C:\\Users\\apantiuk\\Desktop\\ODQA\\tfidf.db'`

Are you sure there is no other process that uses this database?

**Comment by matherialist** [comment]
The program was creating several processes (I don't know why). `if __name__ == '__main__'` solved the problem.
