### ISSUE TITLE
running deeppavlov transcribe

### ISSUE THREAD

**Issue by Steboss** [deepmipt/DeepPavlov#1206]
Hi everybody,

I am trying to run a transcribe model on google colab, as:
```
from deeppavlov import build_model, configs

model = build_model(configs.nemo.asr)
text_batch = model("my_path")
```
I had an initial problem with `model=build_model(configs.nemo.asr)`  because model `nemo` was not found, even if it was installed. Thus I solved this issue installing nemo from Nvidia repository as:
`!pip install git+https://github.com/NVIDIA/NeMo.git`
However, I am facing this new issue:
```
2020-05-11 10:47:37.536 ERROR in 'deeppavlov.core.common.params'['params'] at line 112: Exception in <class 'deeppavlov.models.nemo.asr.NeMoASR'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/models/nemo/asr.py", line 163, in __init__
    **self.nemo_params['AudioToMelSpectrogramPreprocessor']
  File "/usr/local/lib/python3.6/dist-packages/nemo/collections/asr/audio_preprocessing.py", line 362, in __init__
    super().__init__(n_window_size, n_window_stride)
  File "/usr/local/lib/python3.6/dist-packages/nemo/collections/asr/audio_preprocessing.py", line 74, in __init__
    super().__init__()
  File "/usr/local/lib/python3.6/dist-packages/nemo/backends/pytorch/nm.py", line 136, in __init__
    NeuralModule.__init__(self, name)  # For NeuralModule API
  File "/usr/local/lib/python3.6/dist-packages/nemo/core/neural_modules.py", line 70, in __init__
    super().__init__()
  File "/usr/local/lib/python3.6/dist-packages/nemo/core/neural_interface.py", line 41, in __init__
    self._app_state = nemo.utils.app_state.AppState()
  File "/usr/local/lib/python3.6/dist-packages/nemo/utils/metaclasses.py", line 36, in __call__
    cls.__instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nemo/utils/app_state.py", line 43, in __init__
    self._device = nemo.core.DeviceType.GPU
AttributeError: module 'nemo' has no attribute 'core'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-54-5e369d1d15ef> in <module>()
----> 1 model = build_model(configs.nemo.asr)

9 frames
/usr/local/lib/python3.6/dist-packages/nemo/utils/app_state.py in __init__(self, device)
     41         # Had to set it to None in argument to avoid circular import at the class initialization phase.
     42         if device is None:
---> 43             self._device = nemo.core.DeviceType.GPU
     44         else:
     45             self._device = device

AttributeError: module 'nemo' has no attribute 'core'

```

Should I install nemo in some other way or is there a solution for this?
Thanks very much 

Stefano

**Comment by Steboss** [comment]
Update:

I restart the runtime and I got this issue right now:

```
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to /root/nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
################################################################################
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kaldi-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profile)
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
################################################################################

/usr/local/lib/python3.6/dist-packages/nemo/collections/asr/audio_preprocessing.py:57: UserWarning: Could not import torchaudio. Some features might not work.
  warnings.warn('Could not import torchaudio. Some features might not work.')
/usr/local/lib/python3.6/dist-packages/nemo/collections/asr/audio_preprocessing.py:61: UserWarning: Unable to import APEX. Mixed precision and distributed training will not work.
  warnings.warn("Unable to import APEX. Mixed precision and distributed training will not work.")
[NeMo I 2020-05-11 10:59:34 features:144] PADDING: 16
[NeMo I 2020-05-11 10:59:34 features:152] STFT using conv
2020-05-11 10:59:34.545 ERROR in 'deeppavlov.core.common.params'['params'] at line 112: Exception in <class 'deeppavlov.models.nemo.asr.NeMoASR'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/models/nemo/asr.py", line 165, in __init__
    self.jasper_encoder = JasperEncoder(**self.nemo_params['JasperEncoder'])
TypeError: __init__() missing 1 required positional argument: 'feat_in'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-5e369d1d15ef> in <module>()
----> 1 model = build_model(configs.nemo.asr)

2 frames
/usr/local/lib/python3.6/dist-packages/deeppavlov/models/nemo/asr.py in __init__(self, load_path, nemo_params_path, **kwargs)
    163             **self.nemo_params['AudioToMelSpectrogramPreprocessor']
    164         )
--> 165         self.jasper_encoder = JasperEncoder(**self.nemo_params['JasperEncoder'])
    166         self.jasper_decoder = JasperDecoderForCTC(num_classes=len(self.labels), **self.nemo_params['JasperDecoder'])
    167         self.greedy_decoder = GreedyCTCDecoder()

TypeError: __init__() missing 1 required positional argument: 'feat_in'
```

**Comment by IgnatovFedor** [comment]
Hi, @Steboss 
Did you run `! python -m deeppavlov install asr_tts` before running `model = build_model(configs.nemo.asr)`? Could you write all executed commands before `AttributeError: module 'nemo' has no attribute 'core'` appeared?
Also, please send all code that led to the `TypeError: __init__() missing 1 required positional argument: 'feat_in'`. Did you modify either DeepPavlov asr config or NeMo modules configuration file?

**Comment by Steboss** [comment]
Hi @IgnatovFedor 
Thanks for your reply!

I am trying now to run ` python -m deeppavlov install asr_tts` before all so I'll let you know asap. 

These are all the commands I run:

```
!pip install deeppavlov
!pip install git+https://github.com/NVIDIA/NeMo.git
!pip install frozendict
!pip install kaldi_io
!pip install unidecode
!pip install torch_stft
!pip install soundfile
!pip install braceexpand
!pip install webdataset
``` 
I am sorry for the so many pip install, but everytime I was running the `build_model` command I got a missing module

**Comment by Steboss** [comment]
Hi @IgnatovFedor 

After running `! python -m deeppavlov install asr_tts` :

```
!pip install deeppavlov
!pip install git+https://github.com/NVIDIA/NeMo.git
!pip install frozendict
!pip install kaldi_io
!pip install unidecode
!pip install torch_stft
!pip install soundfile
!pip install braceexpand
!pip install webdataset
from deeppavlov import build_model, configs
! python -m deeppavlov install asr_tts

model = build_model(configs.nemo.asr)
```
I have this output:

```
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to /root/nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
################################################################################
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kaldi-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profile)
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
################################################################################

/usr/local/lib/python3.6/dist-packages/nemo/collections/asr/audio_preprocessing.py:57: UserWarning: Could not import torchaudio. Some features might not work.
  warnings.warn('Could not import torchaudio. Some features might not work.')
/usr/local/lib/python3.6/dist-packages/nemo/collections/asr/audio_preprocessing.py:61: UserWarning: Unable to import APEX. Mixed precision and distributed training will not work.
  warnings.warn("Unable to import APEX. Mixed precision and distributed training will not work.")
[NeMo I 2020-05-11 10:59:34 features:144] PADDING: 16
[NeMo I 2020-05-11 10:59:34 features:152] STFT using conv
2020-05-11 10:59:34.545 ERROR in 'deeppavlov.core.common.params'['params'] at line 112: Exception in <class 'deeppavlov.models.nemo.asr.NeMoASR'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/models/nemo/asr.py", line 165, in __init__
    self.jasper_encoder = JasperEncoder(**self.nemo_params['JasperEncoder'])
TypeError: __init__() missing 1 required positional argument: 'feat_in'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-5e369d1d15ef> in <module>()
----> 1 model = build_model(configs.nemo.asr)

2 frames
/usr/local/lib/python3.6/dist-packages/deeppavlov/models/nemo/asr.py in __init__(self, load_path, nemo_params_path, **kwargs)
    163             **self.nemo_params['AudioToMelSpectrogramPreprocessor']
    164         )
--> 165         self.jasper_encoder = JasperEncoder(**self.nemo_params['JasperEncoder'])
    166         self.jasper_decoder = JasperDecoderForCTC(num_classes=len(self.labels), **self.nemo_params['JasperDecoder'])
    167         self.greedy_decoder = GreedyCTCDecoder()

TypeError: __init__() missing 1 required positional argument: 'feat_in'
```

**Comment by IgnatovFedor** [comment]
@Steboss, you don't have to run all this pip install commands. After running `python -m deeppavlov install asr_tts` all necessary dependencies will be installed. Please, try following code:
```
! pip install deeppavlov
! python -m deeppavlov install asr
! python -m deeppavlov download asr
from deeppavlov import build_mode, configs
model = build_model(configs.nemo.asr)
```
The issue was in absence of necessary model files that downloaded with `python -m deeppavlov download asr`. Alternative way of downloading files is using `download=True` additional kwarg in build_model.

**Comment by Steboss** [comment]
Thanks @IgnatovFedor now everything's working fine :) 
I am trying to convert a wav file into text running  `model([ "path_to_my_wav.wav"])` but I have this error:
```
[NeMo I 2020-05-11 16:24:12 actions:728] Evaluating batch 0 out of 1
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-4e492d812e9b> in <module>()
----> 1 text_batch = model(["linee_test.wav"])

17 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in _pad(input, pad, mode, value)
   3406             assert len(pad) == 4, '4D tensors expect 4 values for padding'
   3407             if mode == 'reflect':
-> 3408                 return torch._C._nn.reflection_pad2d(input, pad)
   3409             elif mode == 'replicate':
   3410                 return torch._C._nn.replication_pad2d(input, pad)

RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (256, 256) at dimension 3 of input 4
```
my wav file is about 150 MB and 15 minutes long
Thanks a million

Stefano

**Comment by IgnatovFedor** [comment]
As mentioned in [documentation](http://docs.deeppavlov.ai/en/0.9.1/features/models/nemo.html), models work with single channel wav files. This error is most likely occurs due to your file is multi-channel.
If `linee_test.wav` is multi channel, you could create single channel version using following code:
```
from scipy.io.wavfile import read, write
sr, data = read('linee_test.wav')
with open('linee_test_mono.wav', 'wb') as fout:
    write(fout, sr, data[:, 0])
'''

**Comment by Steboss** [comment]
Ouch
that's great. Now it works fine
I just changed the title of the issue, so it's better and more related to what discussed.
Thanks very much @IgnatovFedor 
I am closing the issue
