### ISSUE TITLE
ModuleNotFoundError: No module named 'bert_dp'

### ISSUE THREAD

**Issue by aixuedegege** [deepmipt/DeepPavlov#1216]
my code is :

from deeppavlov import build_model, configs
config_path = r"D:\code\python\DeepPavlov-master\tests\test_configs\squad\squad_zh_bert_zh.json"
model = build_model(config_path, download=False)
model(['DeepPavlov is library for NLP and dialog systems.'], ['What is DeepPavlov?'])

but i get an error:

[nltk_data] Error loading punkt: <urlopen error [Errno 11004]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading stopwords: <urlopen error [Errno 11004]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading perluniprops: <urlopen error [Errno 11004]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading nonbreaking_prefixes: <urlopen error [Errno
[nltk_data]     11004] getaddrinfo failed>
Traceback (most recent call last):
  File "D:/code/python/DeepPavlov-master/tests/squad.py", line 15, in <module>
    model = build_model(config_path, download=False)
  File "D:\code\python\DeepPavlov-master\deeppavlov\core\commands\infer.py", line 62, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "D:\code\python\DeepPavlov-master\deeppavlov\core\common\params.py", line 95, in from_params
    obj = get_model(cls_name)
  File "D:\code\python\DeepPavlov-master\deeppavlov\core\common\registry.py", line 72, in get_model
    return cls_from_str(_REGISTRY[name])
  File "D:\code\python\DeepPavlov-master\deeppavlov\core\common\registry.py", line 40, in cls_from_str
    return getattr(importlib.import_module(module_name), cls_name)
  File "D:\app\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\code\python\DeepPavlov-master\deeppavlov\models\preprocessors\bert_preprocessor.py", line 19, in <module>
    from bert_dp.preprocessing import convert_examples_to_features, InputExample, InputFeatures
ModuleNotFoundError: No module named 'bert_dp'

and my python in pycharm as same as python in terminal. I saw this :https://github.com/deepmipt/DeepPavlov/issues/1058

pip install bert_dp is not helpful. Could you help me？Thanks a lot!

**Comment by yurakuratov** [comment]
Hi!

Did you run `python -m deeppavlov install squad_zh_bert_zh ` like described here https://github.com/deepmipt/DeepPavlov/issues/808#issuecomment-484113024

**Comment by aixuedegege** [comment]
Thank you very much for your solution！
