### ISSUE TITLE
Paraphrase model requires fasttext of version that doesn't exist

### ISSUE THREAD

**Issue by alissiawells** [deepmipt/DeepPavlov#1234]
I have wrote a script using Deeppavlov. It works on my machine. When I try to run the script on a remote server, it fails with the Import Module Error: fastText not found. Paraphrase model requires fasttext==0.8.22, however there are only 0.8.2 and 0.8.3 versions
![1590688385194](https://user-images.githubusercontent.com/35057128/83175879-50d1a580-a125-11ea-9283-6cfb3ca63cd2.jpg)

**Comment by yoptar** [comment]
Hi @alissiawells,
Can you post the full error message that comes up when you try to run the model?

**Comment by alissiawells** [comment]
root@80-78-248-95:~# sudo python3 paraphrase_matrix.py texts.txt
2020-05-29 00:20:01.600 INFO in 'deeppavlov.download'['download'] at line 117: Skipped http://files.deeppavlov.ai/datasets/paraphraser_gold.zip download because of matching hashes
2020-05-29 00:20:32.929 INFO in 'deeppavlov.download'['download'] at line 117: Skipped http://files.deeppavlov.ai/embeddings/ft_native_300_ru_wiki_lenta_lower_case/ft_native_300_ru_wiki_lenta_lower_case.bin download because of matching hashes
2020-05-29 00:20:32.986 INFO in 'deeppavlov.download'['download'] at line 117: Skipped http://files.deeppavlov.ai/deeppavlov_data/paraphrase_ident_paraphraser_tuned.tar.gz download because of matching hashes
2020-05-29 00:20:33.55 INFO in 'deeppavlov.download'['download'] at line 117: Skipped http://files.deeppavlov.ai/datasets/paraphraser.zip download because of matching hashes
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to /root/nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
Traceback (most recent call last):
  File "/root/DeepPavlov/deeppavlov/models/embedders/fasttext_embedder.py", line 19, in <module>
    import fastText
ModuleNotFoundError: No module named 'fastText'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "paraphrase_matrix.py", line 27, in <module>
    para_model = buldmodel()
  File "paraphrase_matrix.py", line 13, in buldmodel
    para_model = build_model(configs.ranking.paraphrase_ident_tune_interact, download=True)
  File "/root/DeepPavlov/deeppavlov/core/commands/infer.py", line 61, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "/root/DeepPavlov/deeppavlov/core/common/params.py", line 99, in from_params
    config_params = {k: _init_param(v, mode) for k, v in config_params.items()}
  File "/root/DeepPavlov/deeppavlov/core/common/params.py", line 99, in <dictcomp>
    config_params = {k: _init_param(v, mode) for k, v in config_params.items()}
  File "/root/DeepPavlov/deeppavlov/core/common/params.py", line 52, in _init_param
    param = from_params(param, mode=mode)
  File "/root/DeepPavlov/deeppavlov/core/common/params.py", line 95, in from_params
    obj = get_model(cls_name)
  File "/root/DeepPavlov/deeppavlov/core/common/registry.py", line 72, in get_model
    return cls_from_str(_REGISTRY[name])
  File "/root/DeepPavlov/deeppavlov/core/common/registry.py", line 40, in cls_from_str
    return getattr(importlib.import_module(module_name), cls_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/DeepPavlov/deeppavlov/models/embedders/fasttext_embedder.py", line 29, in <module>
    raise ModuleNotFoundError(f'{e}\n\nYou can install fastText by running\n'
ModuleNotFoundError: No module named 'fastText'

You can install fastText by running
/usr/bin/python3 -m pip install pybind11==2.2.3 git+https://github.com/deepmipt/fastText.git#egg=fastText==0.8.22
or for your deeppavlov pipeline configuration
/usr/bin/python3 -m deeppavlov install <config_path>

**Comment by alissiawells** [comment]
~# sudo python3 paraphrase_matrix.py texts.txt
2020-05-29 00:20:01.600 INFO in 'deeppavlov.download'['download'] at line 117: Skipped http://files.deeppavlov.ai/datasets/paraphraser_gold.zip download because of matching hashes
2020-05-29 00:20:32.929 INFO in 'deeppavlov.download'['download'] at line 117: Skipped http://files.deeppavlov.ai/embeddings/ft_native_300_ru_wiki_lenta_lower_case/ft_native_300_ru_wiki_lenta_lower_case.bin download because of matching hashes
2020-05-29 00:20:32.986 INFO in 'deeppavlov.download'['download'] at line 117: Skipped http://files.deeppavlov.ai/deeppavlov_data/paraphrase_ident_paraphraser_tuned.tar.gz download because of matching hashes
2020-05-29 00:20:33.55 INFO in 'deeppavlov.download'['download'] at line 117: Skipped http://files.deeppavlov.ai/datasets/paraphraser.zip download because of matching hashes
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to /root/nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
Traceback (most recent call last):
  File "/root/DeepPavlov/deeppavlov/models/embedders/fasttext_embedder.py", line 19, in <module>
    import fastText
ModuleNotFoundError: No module named 'fastText'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "paraphrase_matrix.py", line 27, in <module>
    para_model = buldmodel()
  File "paraphrase_matrix.py", line 13, in buldmodel
    para_model = build_model(configs.ranking.paraphrase_ident_tune_interact, download=True)
  File "/root/DeepPavlov/deeppavlov/core/commands/infer.py", line 61, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "/root/DeepPavlov/deeppavlov/core/common/params.py", line 99, in from_params
    config_params = {k: _init_param(v, mode) for k, v in config_params.items()}
  File "/root/DeepPavlov/deeppavlov/core/common/params.py", line 99, in <dictcomp>
    config_params = {k: _init_param(v, mode) for k, v in config_params.items()}
  File "/root/DeepPavlov/deeppavlov/core/common/params.py", line 52, in _init_param
    param = from_params(param, mode=mode)
  File "/root/DeepPavlov/deeppavlov/core/common/params.py", line 95, in from_params
    obj = get_model(cls_name)
  File "/root/DeepPavlov/deeppavlov/core/common/registry.py", line 72, in get_model
    return cls_from_str(_REGISTRY[name])
  File "/root/DeepPavlov/deeppavlov/core/common/registry.py", line 40, in cls_from_str
    return getattr(importlib.import_module(module_name), cls_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/DeepPavlov/deeppavlov/models/embedders/fasttext_embedder.py", line 29, in <module>
    raise ModuleNotFoundError(f'{e}\n\nYou can install fastText by running\n'
ModuleNotFoundError: No module named 'fastText'

You can install fastText by running
/usr/bin/python3 -m pip install pybind11==2.2.3 git+https://github.com/deepmipt/fastText.git#egg=fastText==0.8.22
or for your deeppavlov pipeline configuration
/usr/bin/python3 -m deeppavlov install <config_path>

**Comment by yoptar** [comment]
There's a suggestion on how to fix that at the end of this error message:
> You can install fastText by running 
`/usr/bin/python3 -m pip install pybind11==2.2.3 git+https://github.com/deepmipt/fastText.git#egg=fastText==0.8.22`
or for your deeppavlov pipeline configuration
`/usr/bin/python3 -m deeppavlov install <config_path>`

You can also try and update to a version of DeepPavlov `0.8.0` or higher that uses `fasttext==0.9.1` from pypi.

**Comment by alissiawells** [comment]
I started the tred with the screenshot: there's no fasttext==0.8.22, only 0.8.2, 0.8.3 versions and so on. I see this error message, when I run:

/usr/bin/python3 -m pip install pybind11==2.2.3 git+https://github.com/deepmipt/fastText.git#egg=fastText==0.8.22

**Comment by yoptar** [comment]
There is no `fasttext==0.8.22` on pypi but you can install it from github using the command above.
The error you showed in the first message is for when you try to install it from pypi and not from github.

Can you post the error message that you get when you run the command for installing it from github?
```bash
/usr/bin/python3 -m pip install pybind11==2.2.3 git+https://github.com/deepmipt/fastText.git#egg=fastText==0.8.22
```

**Comment by alissiawells** [comment]
I've tried to update to a version of DeepPavlov 0.8.0 but cannot run my script because of the Exception: fastText: Cannot load /root/.deeppavlov/downloads/embeddings/ft_native_300_ru_wiki_lenta_lower_case.bin due to C++ extension failed to allocate the memory

**Comment by yoptar** [comment]
>I've tried to update to a version of DeepPavlov 0.8.0 but cannot run my script because of the Exception: fastText: Cannot load /root/.deeppavlov/downloads/embeddings/ft_native_300_ru_wiki_lenta_lower_case.bin due to C++ extension failed to allocate the memory

What version of fastText do you have installed? It should be `fasttext==0.9.1`

**Comment by kotbegemot** [comment]
I have a version fasttext==0.9.1  fasttext==0.9.1 . What version of tensorflow should I install?

**Comment by kotbegemot** [comment]
@yoptar

**Comment by yoptar** [comment]
@kotbegemot, you can find an answer in the [readme](https://github.com/deepmipt/DeepPavlov#gpu-requirements).
Afterwards, please post questions like this on the [forum](https://forum.deeppavlov.ai/) and not in a closed issue on an unrelated to your question subject.
