### ISSUE TITLE
Problem when restoring model after saving it

### ISSUE THREAD

**Issue by menajosep** [deepmipt/DeepPavlov#1256]
**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):
Version: 0.10.0
**Python version**:
Python 3.6.9
**Operating system** (ubuntu linux, windows, ...):
Google colab
**Issue**:
After training a NER model and saving it, I'm not able to restore it for using it to predict new sentences.
I train the model using:
`ner_model = train_model(ner_config, download=True)`
and after training it for some epochs I save it running:
`ner_model.save()`
If I restart the colab notebook or try to run the saved model in another machine by calling:
`ner_model = build_model(ner_config)`

**Before both training and restore the model I run this configuration**:
```
    with configs.ner.ner_ontonotes_bert_mult.open(encoding='utf8') as f:
        ner_config = json.load(f)

    # directory with train.txt, valid.txt and test.txt files
    ner_config['dataset_reader']['data_path'] = ner_path
    # do not download data, use own
    ner_config['metadata']['download'] = [
        ner_config['metadata']['download'][-1]]  # do not download the pretrained ontonotes model
    ner_config['metadata']['variables']['NER_PATH'] = os.path.join(os.path.dirname(ner_path), 'my_saved_model')
```

**Error (including full traceback)**:
```
2020-06-22 10:50:48.526 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 115: [loading vocabulary from /content/drive/My Drive/chatbot/DeepPavlov/DeepPavlov_code/datasets/cameras/my_saved_model/tag.dict]
2020-06-22 10:51:11.87 INFO in 'deeppavlov.core.models.tf_model'['tf_model'] at line 51: [loading model from /content/drive/My Drive/chatbot/DeepPavlov/DeepPavlov_code/datasets/cameras/my_saved_model/model]
INFO:tensorflow:Restoring parameters from /content/drive/My Drive/chatbot/DeepPavlov/DeepPavlov_code/datasets/cameras/my_saved_model/model
2020-06-22 10:51:12.279 ERROR in 'deeppavlov.core.common.params'['params'] at line 112: Exception in <class 'deeppavlov.models.bert.bert_sequence_tagger.BertSequenceTagger'>
Traceback (most recent call last):
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: Read less bytes than requested
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_451]]
  (1) Out of range: Read less bytes than requested
	 [[{{node save/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_backend.py", line 76, in __call__
    obj.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 529, in __init__
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 259, in __init__
    self.load()
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 457, in load
    return super().load(exclude_scopes=exclude_scopes, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_model.py", line 251, in load
    return super().load(exclude_scopes=exclude_scopes, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_model.py", line 55, in load
    saver.restore(self.sess, path)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: Read less bytes than requested
	 [[node save/RestoreV2 (defined at /tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[save/RestoreV2/_451]]
  (1) Out of range: Read less bytes than requested
	 [[node save/RestoreV2 (defined at /tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelapp.py", line 499, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-13883b9f79cd>", line 2, in <module>
    ner_model = build_model(ner_config)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/commands/infer.py", line 62, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_backend.py", line 76, in __call__
    obj.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 529, in __init__
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 259, in __init__
    self.load()
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 457, in load
    return super().load(exclude_scopes=exclude_scopes, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_model.py", line 251, in load
    return super().load(exclude_scopes=exclude_scopes, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_model.py", line 54, in load
    saver = tf.train.Saver(var_list)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

---------------------------------------------------------------------------
OutOfRangeError                           Traceback (most recent call last)
/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

17 frames
OutOfRangeError: 2 root error(s) found.
  (0) Out of range: Read less bytes than requested
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_451]]
  (1) Out of range: Read less bytes than requested
	 [[{{node save/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

OutOfRangeError                           Traceback (most recent call last)
/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1382                     '\nsession_config.graph_options.rewrite_options.'
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 
   1386   def _extend_graph(self):

OutOfRangeError: 2 root error(s) found.
  (0) Out of range: Read less bytes than requested
	 [[node save/RestoreV2 (defined at /tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[save/RestoreV2/_451]]
  (1) Out of range: Read less bytes than requested
	 [[node save/RestoreV2 (defined at /tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelapp.py", line 499, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-13883b9f79cd>", line 2, in <module>
    ner_model = build_model(ner_config)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/commands/infer.py", line 62, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_backend.py", line 76, in __call__
    obj.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 529, in __init__
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 259, in __init__
    self.load()
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 457, in load
    return super().load(exclude_scopes=exclude_scopes, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_model.py", line 251, in load
    return super().load(exclude_scopes=exclude_scopes, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_model.py", line 54, in load
    saver = tf.train.Saver(var_list)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by yoptar** [comment]
Hi @menajosep,

Will it behave the same way if you do not run the `ner_model.save()` command?

When you run `ner_model = train_model(ner_config, download=True)` you get a model that's already loaded from a saved checkpoint.

**Comment by menajosep** [comment]
HI @yoptar ,
I tried doingthe same without explicitely calling the save method but i got the same result:
```
OutOfRangeError: 2 root error(s) found.
  (0) Out of range: Read less bytes than requested
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_451]]
  (1) Out of range: Read less bytes than requested
	 [[{{node save/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.
```
It looks to me like it only works when in the same session. Any idea about how to fix this?

**Comment by menajosep** [comment]
Hi again, 
Another weird thing that I realized now is that after training the model:
```
2020-06-22 15:14:59.988 INFO in 'deeppavlov.core.trainers.nn_trainer'['nn_trainer'] at line 211: Did not improve on the ner_f1 of 94.5122
{"valid": {"eval_examples_count": 129, "metrics": {"ner_f1": 92.9231, "ner_token_f1": 95.0249}, "time_spent": "0:28:51", "epochs_done": 29, "batches_seen": 860, "train_examples_seen": 13470, "impatience": 33, "patience_limit": 100}}
2020-06-22 15:15:19.970 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 115: [loading vocabulary from /content/drive/My Drive/chatbot/DeepPavlov/DeepPavlov_code/datasets/cameras/my_saved_model/tag.dict]
2020-06-22 15:15:47.929 INFO in 'deeppavlov.core.models.tf_model'['tf_model'] at line 51: [loading model from /content/drive/My Drive/chatbot/DeepPavlov/DeepPavlov_code/datasets/cameras/my_saved_model/model]
INFO:tensorflow:Restoring parameters from /content/drive/My Drive/chatbot/DeepPavlov/DeepPavlov_code/datasets/cameras/my_saved_model/model
2020-06-22 15:15:55.248 DEBUG in 'deeppavlov.metrics.fmeasure'['fmeasure'] at line 397: processed 5822 tokens with 160 phrases; found: 168 phrases; correct: 0.

precision:  92.26%; recall:  96.88%; FB1:  94.51
```
it is not generating the file model.data-00000-of-00001 in the target folder.
By the way, the Tensorflow version used is '1.15.2'

**Comment by yoptar** [comment]
That's what i was experimenting with right now, actually.
My guess is that you don't have enough space on your Google Drive, so the `model.data-00000-of-00001` file is created and usable in the same colab session, but it's not synchronized because of the lack of space. So when you reboot the instance or start a new one your drive is restored as is.

**Comment by menajosep** [comment]
You were right, it was a problem of my Google Drive, I run out of space and it was not able to store the model. My fault! thank you so much anyway.
By the way, how did you know it?

**Comment by yoptar** [comment]
> By the way, how did you know it?

A quick google search told me that this error happens if a model file is incomplete, so I was trying to understand how you could transfer the file between instances, how you would damage it in process, and why would it affect the same instance after restarting.
And your message about not having the file at all and the fact that your model is saved to `/content/drive/My Drive` provided an answer to those questions.

I'm glad I could help.
