### ISSUE TITLE
Unexpected keyword argument 'hidden' when installing deeppavlov

### ISSUE THREAD

**Issue by antoinecomp** [deepmipt/DeepPavlov#1258]
**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):
```
(base) antoi@LAPTOP-UTL8OHHO:/mnt/c/Users/antoi/Documents/Programming/Scraping/Python$ pip show deeppavlov
Name: deeppavlov
Version: 0.10.0
Summary: An open source library for building end-to-end dialog systems and training chatbots.
Home-page: https://github.com/deepmipt/DeepPavlov
Author: Neural Networks and Deep Learning lab, MIPT
Author-email: info@deeppavlov.ai
License: Apache License, Version 2.0
Location: /home/antoi/anaconda3/lib/python3.7/site-packages
Requires: pandas, pymorphy2-dicts-ru, scipy, uvicorn, sacremoses, requests, tqdm, numpy, pyopenssl, fastapi, nltk, aio-pika, ruamel.yaml, pydantic, pytelegrambotapi, h5py, pymorphy2, scikit-learn, overrides, pytz, Cython, rusenttokenize
Required-by:
```
**Python version**:

Python3.7

**Operating system** (ubuntu linux, windows, ...):

Windows 10

**Issue**:
I want to get the intents in questions so I'm trying to install deeppavlov following [the docs][1]. Yet I got a TypeError: unexpected keyword argument 'hidden' when installing it. 

  [1]: http://docs.deeppavlov.ai/en/master/features/models/classifiers.html

**Content or a name of a configuration file**:
```

```

**Command that led to error**:
```
    (base) antoi@LAPTOP-UTL8OHHO:/mnt/c/Users/antoi/Documents/Programming/Scraping/Python$ python -m deeppavlov install intents_snips
```

**Error (including full traceback)**:
```
    Traceback (most recent call last):
      File "/home/antoi/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/home/antoi/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/antoi/anaconda3/lib/python3.7/site-packages/deeppavlov/__main__.py", line 2, in <module>
        from .deep import main
      File "/home/antoi/anaconda3/lib/python3.7/site-packages/deeppavlov/deep.py", line 23, in <module>
        from deeppavlov.utils.agent import start_rabbit_service
      File "/home/antoi/anaconda3/lib/python3.7/site-packages/deeppavlov/utils/agent/__init__.py", line 1, in <module>
        from .server import start_rabbit_service
      File "/home/antoi/anaconda3/lib/python3.7/site-packages/deeppavlov/utils/agent/server.py", line 22, in <module>
        from deeppavlov.utils.agent.rabbitmq import RabbitMQServiceGateway
      File "/home/antoi/anaconda3/lib/python3.7/site-packages/deeppavlov/utils/agent/rabbitmq.py", line 33, in <module>
        from deeppavlov.utils.server import get_server_params
      File "/home/antoi/anaconda3/lib/python3.7/site-packages/deeppavlov/utils/server/__init__.py", line 1, in <module>
        from .server import get_server_params, get_ssl_params, redirect_root_to_docs, start_model_server
      File "/home/antoi/anaconda3/lib/python3.7/site-packages/deeppavlov/utils/server/server.py", line 22, in <module>
        import uvicorn
      File "/home/antoi/anaconda3/lib/python3.7/site-packages/uvicorn/__init__.py", line 2, in <module>
        from uvicorn.main import Server, main, run
      File "/home/antoi/anaconda3/lib/python3.7/site-packages/uvicorn/main.py", line 285, in <module>
        use_colors: bool,
      File "/home/antoi/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 170, in decorator
        _param_memo(f, OptionClass(param_decls, **attrs))
      File "/home/antoi/anaconda3/lib/python3.7/site-packages/click/core.py", line 1460, in __init__
        Parameter.__init__(self, param_decls, type=type, **attrs)
    TypeError: __init__() got an unexpected keyword argument 'hidden'
```

**Comment by yoptar** [comment]
Hi @antoinecomp,

Thank you for reporting this error, I was able to reproduce it.
It looks like you have an older version of the `click` package.
To fix it you can run `pip install click==7.1.2`.
We will lock the version requirement in the next DeepPavlov release.
