### ISSUE TITLE
Installation of squad_bert fails. Tensorflow not found.

### ISSUE THREAD

**Issue by kashyap-aditya** [deepmipt/DeepPavlov#1267]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

Please enter all the information below, otherwise your issue may be closed without a warning. 

**DeepPavlov version** (you can look it up by running `pip show deeppavlov`): 0.11.0

**Python version**: 3.6.9

**Operating system** (ubuntu linux, windows, ...): Ubuntu 18.04

**Issue**:
Ran: 
```
pip install deeppavlov
python -m deeppavlov install squad_bert

```
and got the error:
Could not find a version that satisfies the requirement tensorflow==1.15.2

Then ran:
`pip install tensorflow`
and tried again. Same error
Tried 
`pip install tensorflow==1.15.2` but that failed too

**Content or a name of a configuration file**:
```
squad_bert
```

**Command that led to error**:
```
python -m deeppavlov install squad_bert
```

**Error (including full traceback)**:
```
2020-07-05 03:14:09.451 INFO in 'deeppavlov.core.common.file'['file'] at line 32: Interpreting 'squad_bert' as '/home/adi/Codes/.env/lib/python3.6/site-packages/deeppavlov/configs/squad/squad_bert.json'
Collecting git+https://github.com/deepmipt/bert.git@feat/multi_gpu
  Cloning https://github.com/deepmipt/bert.git (to feat/multi_gpu) to /tmp/pip-m50xf074-build
  Requirement already satisfied (use --upgrade to upgrade): bert-dp==1.0 from git+https://github.com/deepmipt/bert.git@feat/multi_gpu in ./.env/lib/python3.6/site-packages
Collecting tensorflow==1.15.2
  Could not find a version that satisfies the requirement tensorflow==1.15.2 (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow==1.15.2
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/adi/Codes/.env/lib/python3.6/site-packages/deeppavlov/__main__.py", line 4, in <module>
    main()
  File "/home/adi/Codes/.env/lib/python3.6/site-packages/deeppavlov/deep.py", line 130, in main
    install_from_config(pipeline_config_path)
  File "/home/adi/Codes/.env/lib/python3.6/site-packages/deeppavlov/utils/pip_wrapper/pip_wrapper.py", line 71, in install_from_config
    install(r)
  File "/home/adi/Codes/.env/lib/python3.6/site-packages/deeppavlov/utils/pip_wrapper/pip_wrapper.py", line 38, in install
    env=os.environ.copy())
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/adi/Codes/.env/bin/python', '-m', 'pip', 'install', 'tensorflow==1.15.2']' returned non-zero exit status 1.
```

**Comment by kashyap-aditya** [comment]
Solved by running 
pip install --upgrade pip
