### ISSUE TITLE
NER :  ModuleNotFoundError: No module named 'bert_dp'

### ISSUE THREAD

**Issue by WilliamTambellini** [deepmipt/DeepPavlov#1345]
Please enter all the information below, otherwise your issue may be closed without a warning. 

```
from deeppavlov import configs, build_model
ner_model = build_model(configs.ner.ner_ontonotes_bert_mult, download=True)
ner_model(['Curling World Championship will be held in Antananarivo'])

2020-11-17 13:06:14.334 INFO in 'deeppavlov.core.data.utils'['utils'] at line 94: Downloading from http://files.deeppavlov.ai/deeppavlov_data/ner_ontonotes_bert_mult_v1.tar.gz to /home/wtambellini/.deeppavlov/ner_ontonotes_bert_mult_v1.tar.gz
2020-11-17 13:10:01.62 INFO in 'deeppavlov.core.data.utils'['utils'] at line 268: Extracting /home/wtambellini/.deeppavlov/ner_ontonotes_bert_mult_v1.tar.gz archive into /home/wtambellini/.deeppavlov/models
2020-11-17 13:10:25.924 INFO in 'deeppavlov.download'['download'] at line 138: Skipped http://files.deeppavlov.ai/deeppavlov_data/bert/multi_cased_L-12_H-768_A-12.zip download because of matching hashes
[nltk_data] Downloading package punkt to
[nltk_data]     /home/wtambellini/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/wtambellini/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package perluniprops to
[nltk_data]     /home/wtambellini/nltk_data...
[nltk_data]   Unzipping misc/perluniprops.zip.
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /home/wtambellini/nltk_data...
[nltk_data]   Unzipping corpora/nonbreaking_prefixes.zip.
Traceback (most recent call last):
  File "dpner.py", line 3, in <module>
    ner_model = build_model(configs.ner.ner_ontonotes_bert_mult, download=True)
  File "/home/wtambellini/tmp/dpenv/lib/python3.7/site-packages/deeppavlov/core/commands/infer.py", line 62, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "/home/wtambellini/tmp/dpenv/lib/python3.7/site-packages/deeppavlov/core/common/params.py", line 95, in from_params
    obj = get_model(cls_name)
  File "/home/wtambellini/tmp/dpenv/lib/python3.7/site-packages/deeppavlov/core/common/registry.py", line 72, in get_model
    return cls_from_str(_REGISTRY[name])
  File "/home/wtambellini/tmp/dpenv/lib/python3.7/site-packages/deeppavlov/core/common/registry.py", line 40, in cls_from_str
    return getattr(importlib.import_module(module_name), cls_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wtambellini/tmp/dpenv/lib/python3.7/site-packages/deeppavlov/models/preprocessors/bert_preprocessor.py", line 19, in <module>
    from bert_dp.preprocessing import convert_examples_to_features, InputExample, InputFeatures
ModuleNotFoundError: No module named 'bert_dp'
```

**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):
```
$ pip3.7 show deeppavlov
Name: deeppavlov
Version: 0.13.0
Summary: An open source library for building end-to-end dialog systems and training chatbots.
Home-page: https://github.com/deepmipt/DeepPavlov
Author: Neural Networks and Deep Learning lab, MIPT
Author-email: info@deeppavlov.ai
License: Apache License, Version 2.0
Location: /home/wtambellini/tmp/dpenv/lib/python3.7/site-packages
Requires: fastapi, pydantic, numpy, tqdm, pymorphy2, overrides, ruamel.yaml, rusenttokenize, nltk, filelock, scipy, h5py, uvicorn, Cython, pytz, pytelegrambotapi, sacremoses, aio-pika, pyopenssl, pandas, pymorphy2-dicts-ru, prometheus-client, scikit-learn, requests, click
```

**Python version**: 3.7

**Operating system** (ubuntu linux, windows, ...): ubuntu16

**Issue**:
ModuleNotFoundError: No module named 'bert_dp'

**Command that led to error**:
```
from deeppavlov import configs, build_model
ner_model = build_model(configs.ner.ner_ontonotes_bert_mult, download=True)
ner_model(['Curling World Championship will be held in Antananarivo'])
```

**Comment by WilliamTambellini** [comment]
https://github.com/deepmipt/DeepPavlov/blob/b4dc56a3bf337007f9fb15fd47f6b57d21911ddf/deeppavlov/models/preprocessors/bert_preprocessor.py#L19
the install guide does not refer to any bert_dp package, just 
pip install deeppavlov

**Comment by yurakuratov** [comment]
Hi!

Did you run `python -m deeppavlov install ner_ontonotes_bert_mult` (from [quick start guide](http://docs.deeppavlov.ai/en/master/intro/quick_start.html))?
You can also check similar issue: https://github.com/deepmipt/DeepPavlov/issues/808#issuecomment-484113024

**Comment by WilliamTambellini** [comment]
ok sorry, did nt see that one from the github readme. Thanks.
