### ISSUE TITLE
проблема при выполнении build_model(configs.ner.ner_collection3_m1, download=True)

### ISSUE THREAD

**Issue by emaximen** [deepmipt/DeepPavlov#1347]
Добрый день

вот что получаю при выполнении указанной выше build_model. Другие build работают нормально. Это баг или фича )) ?

спасибо.
Евгений

model.load_binary_data(encoding=encoding)
  File "/usr/local/lib64/python3.6/site-packages/gensim/models/deprecated/fasttext_wrapper.py", line 299, in load_binary_data
    with open(self.file_name, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/anh/.deeppavlov/downloads/embeddings/lenta_lower_100.bin'
Traceback (most recent call last):
  File "dp_in.py", line 19, in <module>
    ner_model_m1 = build_model(configs.ner.ner_collection3_m1, download=True)
  File "/usr/local/lib/python3.6/site-packages/deeppavlov/core/commands/infer.py", line 62, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "/usr/local/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/deeppavlov/core/models/tf_backend.py", line 76, in __call__
    obj.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/deeppavlov/models/ner/NER_model.py", line 108, in __init__
    word_embeddings = self.load_pretrained_word_emb(word_emb_path, word_emb_name, word_dim, word2id)
  File "/usr/local/lib/python3.6/site-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/deeppavlov/models/ner/NER_model.py", line 306, in load_pretrained_word_emb
    ft_model = FastText.load_fasttext_format(model_path)
  File "/usr/local/lib64/python3.6/site-packages/gensim/models/deprecated/fasttext_wrapper.py", line 274, in load_fasttext_format
    model.load_binary_data(encoding=encoding)
  File "/usr/local/lib64/python3.6/site-packages/gensim/models/deprecated/fasttext_wrapper.py", line 299, in load_binary_data
    with open(self.file_name, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/anh/.deeppavlov/downloads/embeddings/lenta_lower_100.bin'

**Comment by yurakuratov** [comment]
Hi!

Thanks for pointing out to this problem, we will fix this configuration file in future releases.
For now, you can change `word_emb_path` to `{DOWNLOADS_PATH}/embeddings/lenta_lower_100.bin`.

**Comment by emaximen** [comment]
Спасибо 

Отправлено с iPhone
