### ISSUE TITLE
Error occurs while training ner_ontonotes_bert_probas model

### ISSUE THREAD

**Issue by ravishpankar** [deepmipt/DeepPavlov#1398]
**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):
0.12.1
**Python version**:
3.7.7

**Operating system** (ubuntu linux, windows, ...):
Windows 10
**Issue**:
I'm training the ner_ontonotes_bert empty model with the ontonotes bio dataset. I'm appending my bio annotations of sentences at the end of train.txt with newline inbetween sentences and then train the model. I'm pasting the code which does the training. I'm not downloading the pretrained weights but pointing to already existing downloads folder in the config file.
Code that does the training:
---------------------------------
logger(log, "Setting the configuration for training...")
    l_pe = output_model_path.split('/')
    out_root_path = '/'.join(l_pe[0:-1])
    l_pe = training_dataset.split('/')
    ds_path = '/'.join(l_pe[0:-1])
    with open(in_root_path + '/' + cfg_name, "r") as f:
        ner_config = json.load(f)
    with open(in_root_path + '/' + cfg_name, "r") as f:
        out_ner_config = json.load(f)
    ner_config['metadata']['variables']['ROOT_PATH'] = in_root_path
    out_ner_config['metadata']['variables']['ROOT_PATH'] = out_root_path
    ner_config['dataset_reader']['data_path'] = ds_path
    ner_config['chainer']['pipe'][1]['save_path'] = output_model_path + '/' + 'tag.dict'
    ner_config['chainer']['pipe'][2]['save_path'] = output_model_path + '/' + 'model'
    ner_config['train']['epochs'] = n_epochs
    logger(log, "Done.")
    logger(log, "Copying config file and downloads folder to output model root...")
    with open(out_root_path + '/' + cfg_name, "w") as f:
        f.write(json.dumps(out_ner_config))
    out_downloads_dir = Path(out_root_path + '/downloads')
    out_downloads_dir.mkdir()
    copy_tree(in_root_path + '/downloads', out_root_path + '/downloads')
    logger(log, "Done.")    
    logger(log, "Training...")
    ner_model = train_model(ner_config) # this one fails
    logger(log, "Done.")
    

**Content or a name of a configuration file**:
```
ner_ontonotes_bert_probas.json unchanged.
```

**Command that led to error**:
```
train_model()
```

**Error (including full traceback)**:
```
2021-02-08 15:37:16.281 INFO in 'deeppavlov.core.trainers.fit_trainer'['fit_trainer'] at line 68: NNTrainer got additional init parameters ['pytest_max_batches', 'pytest_batch_size'] that will be ignored:
WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\core\trainers\nn_trainer.py:150: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\bert_dp\tokenization.py:125: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

2021-02-08 15:38:42.177 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 101: [saving vocabulary to F:\trained_models\models\2021-02-0815-36-33-314121\DEEPPAVLOV_NER_MODEL\ner_ontonotes_bert\tag.dict]
WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\core\models\tf_model.py:37: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\core\models\tf_model.py:222: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\core\models\tf_model.py:222: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\core\models\tf_model.py:193: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py:236: The name tf.ConfigProto
is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py:314: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\bert_dp\modeling.py:178: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\bert_dp\modeling.py:418: The name tf.get_variable is deprecated. Please use
tf.compat.v1.get_variable instead.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\bert_dp\modeling.py:499: The name tf.assert_less_equal is deprecated. Please use tf.compat.v1.assert_less_equal instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\bert_dp\modeling.py:366: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\bert_dp\modeling.py:680: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\tensorflow_core\python\layers\core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\bert_dp\modeling.py:283: The name tf.erf is deprecated. Please use tf.math.erf instead.

WARNING:tensorflow:Variable *= will be deprecated. Use `var.assign(var * other)` if you want assignment to the variable value or `x = x * y` if you want a new python Tensor object.
WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py:75: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\tensorflow_core\contrib\crf\python\ops\crf.py:213: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\core\models\tf_model.py:234: The name tf.train.AdadeltaOptimizer
is deprecated. Please use tf.compat.v1.train.AdadeltaOptimizer instead.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\core\models\tf_model.py:131: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\core\models\tf_model.py:131: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\core\models\tf_model.py:94: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\tensorflow_core\python\training\moving_averages.py:433: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py:671: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py:244: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py:249: checkpoint_exists (from
tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2021-02-08 15:40:23.578 INFO in 'deeppavlov.models.bert.bert_sequence_tagger'['bert_sequence_tagger'] at line 251: [initializing model with Bert from
F:\jdparser_feedback_service\nlp\models\DEEPPAVLOV_NER_MODEL\downloads\bert_models\cased_L-12_H-768_A-12\bert_model.ckpt]
WARNING:tensorflow:From f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py:255: The name tf.train.Saver
is deprecated. Please use tf.compat.v1.train.Saver instead.

f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\metrics\fmeasure.py:274: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if tag != 'O':
Traceback (most recent call last):
  File ".\jdpf\trainers.py", line 48, in train
    deeppavlov_train_model(self.cfg_name, self.in_root_path, self.training_dataset, self.output_model_path, self.n_epochs, log, stop_flag)
  File ".\nlp\train.py", line 268, in deeppavlov_train_model
    ner_model = train_model(ner_config)
  File "f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\__init__.py", line 29, in train_model
    train_evaluate_model_from_config(config, download=download, recursive=recursive)
  File "f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\core\commands\train.py", line 121, in train_evaluate_model_from_config
    trainer.train(iterator)
  File "f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\core\trainers\nn_trainer.py", line 337, in train
    self.train_on_batches(iterator)
  File "f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\core\trainers\nn_trainer.py", line 277, in train_on_batches
    self._validate(iterator)
  File "f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\core\trainers\nn_trainer.py", line 169, in _validate
    start_time=self.start_time)
  File "f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\core\trainers\fit_trainer.py", line 220, in test
    value = metric.fn(*[outputs[i] for i in metric.inputs])
  File "f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\metrics\fmeasure.py", line 34, in ner_f1
    print_results=True)
  File "f:\miniconda3\envs\train_models\lib\site-packages\deeppavlov\metrics\fmeasure.py", line 276, in precision_recall_f1
    tags.add(current_tag)
TypeError: unhashable type: 'numpy.ndarray'

```

**Comment by ravishpankar** [comment]
Please help.

**Comment by ravishpankar** [comment]
Probabilities instead of tags are processed in metrics calculation function. I changed the config file a I got rid of the error.

**Comment by ravishpankar** [comment]
I'm closing this because config file change solved the issue.
