### ISSUE TITLE
Error while building Knowledge Base Question Answering (KBQA) model: ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by Aryagm** [deepmipt/DeepPavlov#1438]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

Please enter all the information below, otherwise your issue may be closed without a warning. 

**DeepPavlov version** (you can look it up by running `pip show deeppavlov`): Version: 0.14.0

**Python version**: Python 3.6.13

**Operating system** (ubuntu linux, windows, ...): Windows 10 Pro

**Issue**: Error with numpy while building Knowledge Base Question Answering (KBQA) model.

**Content or a name of a configuration file**: 
```
deeppavlov.configs.kbqa.kbqa_cq
```

**Command that led to error**:
```
from deeppavlov import configs, build_model

kbqa_model = build_model(configs.kbqa.kbqa_cq)
```

**Error (including full traceback)**:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-e19717954803> in <module>
      1 from deeppavlov import configs, build_model
      2 
----> 3 kbqa_model = build_model(configs.kbqa.kbqa_cq)

~\AppData\Roaming\Python\Python38\site-packages\deeppavlov\core\commands\infer.py in build_model(config, mode, load_trained, download, serialized)
     60             component_serialized = None
     61 
---> 62         component = from_params(component_config, mode=mode, serialized=component_serialized)
     63 
     64         if 'id' in component_config:

~\AppData\Roaming\Python\Python38\site-packages\deeppavlov\core\common\params.py in from_params(params, mode, serialized, **kwargs)
     93         log.exception(e)
     94         raise e
---> 95     obj = get_model(cls_name)
     96 
     97     if inspect.isclass(obj):

~\AppData\Roaming\Python\Python38\site-packages\deeppavlov\core\common\registry.py in get_model(name)
     70             raise ConfigError("Model {} is not registered.".format(name))
     71         return cls_from_str(name)
---> 72     return cls_from_str(_REGISTRY[name])
     73 
     74 

~\AppData\Roaming\Python\Python38\site-packages\deeppavlov\core\common\registry.py in cls_from_str(name)
     38                           .format(name))
     39 
---> 40     return getattr(importlib.import_module(module_name), cls_name)
     41 
     42 

~\anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

~\anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~\anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~\anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\anaconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

~\anaconda3\lib\importlib\_bootstrap_external.py in exec_module(self, module)

~\anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~\AppData\Roaming\Python\Python38\site-packages\deeppavlov\models\__init__.py in <module>
     15 import os
     16 
---> 17 import nltk
     18 
     19 from deeppavlov.core.common.prints import RedirectedPrints

~\AppData\Roaming\Python\Python38\site-packages\nltk\__init__.py in <module>
    141 ###########################################################
    142 
--> 143 from nltk.chunk import *
    144 from nltk.classify import *
    145 from nltk.inference import *

~\AppData\Roaming\Python\Python38\site-packages\nltk\chunk\__init__.py in <module>
    155 from nltk.data import load
    156 
--> 157 from nltk.chunk.api import ChunkParserI
    158 from nltk.chunk.util import (
    159     ChunkScore,

~\AppData\Roaming\Python\Python38\site-packages\nltk\chunk\api.py in <module>
     11 ##//////////////////////////////////////////////////////
     12 
---> 13 from nltk.parse import ParserI
     14 
     15 from nltk.chunk.util import ChunkScore

~\AppData\Roaming\Python\Python38\site-packages\nltk\parse\__init__.py in <module>
     98 from nltk.parse.malt import MaltParser
     99 from nltk.parse.evaluate import DependencyEvaluator
--> 100 from nltk.parse.transitionparser import TransitionParser
    101 from nltk.parse.bllip import BllipParser
    102 from nltk.parse.corenlp import CoreNLPParser, CoreNLPDependencyParser

~\AppData\Roaming\Python\Python38\site-packages\nltk\parse\transitionparser.py in <module>
     20     from numpy import array
     21     from scipy import sparse
---> 22     from sklearn.datasets import load_svmlight_file
     23     from sklearn import svm
     24 except ImportError:

~\anaconda3\lib\site-packages\sklearn\__init__.py in <module>
     74 else:
     75     from . import __check_build
---> 76     from .base import clone
     77     from .utils._show_versions import show_versions
     78 

~\anaconda3\lib\site-packages\sklearn\base.py in <module>
     14 
     15 from . import __version__
---> 16 from .utils import _IS_32BIT
     17 
     18 _DEFAULT_TAGS = {

~\anaconda3\lib\site-packages\sklearn\utils\__init__.py in <module>
     13 from scipy.sparse import issparse
     14 
---> 15 from .murmurhash import murmurhash3_32
     16 from .class_weight import compute_class_weight, compute_sample_weight
     17 from . import _joblib

__init__.pxd in init sklearn.utils.murmurhash()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by IgnatovFedor** [comment]
@Aryagm, could you please send the output of `pip freeze` command?

**Comment by Aryagm** [comment]
I'm sorry I forgot to state that the piece of code was run from a Jupyter notebook cell! The error when I run it from a python file is:

```
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Workstation\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Workstation\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to
[nltk_data]     C:\Users\Workstation\AppData\Roaming\nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!        
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     C:\Users\Workstation\AppData\Roaming\nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
WARNING:tensorflow:From C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\bert_dp\tokenization.py:125: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

2021-05-07 08:50:25.229 ERROR in 'deeppavlov.core.common.params'['params'] at line 112: Exception in <class 'deeppavlov.models.preprocessors.bert_preprocessor.BertNerPreprocessor'>
Traceback (most recent call last):
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\deeppavlov\core\common\params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\deeppavlov\models\preprocessors\bert_preprocessor.py", line 120, in __init__
    do_lower_case=do_lower_case)
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\bert_dp\tokenization.py", line 165, in __init__
    self.vocab = load_vocab(vocab_file)
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\bert_dp\tokenization.py", line 127, in load_vocab
    token = convert_to_unicode(reader.readline())
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 178, in readline
    self._preread_check()
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 84, in _preread_check     
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\Workstation\.deeppavlov\downloads\bert_models_kbqa\cased_L-12_H-768_A-12\vocab.txt : The system cannot find the path specified.
; No such process
Traceback (most recent call last):
  File "c:/Users/Workstation/OneDrive - Peel District School Board/Python/PROBLEM_SOLVING/test.py", line 3, in <module>
    kbqa_model = build_model(configs.kbqa.kbqa_cq)
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\deeppavlov\core\commands\infer.py", line 62, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\deeppavlov\core\common\params.py", line 81, in from_params
    model = build_model(config, serialized=serialized)
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\deeppavlov\core\commands\infer.py", line 62, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\deeppavlov\core\common\params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\deeppavlov\models\preprocessors\bert_preprocessor.py", line 120, in __init__
    do_lower_case=do_lower_case)
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\bert_dp\tokenization.py", line 165, in __init__
    self.vocab = load_vocab(vocab_file)
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\bert_dp\tokenization.py", line 127, in load_vocab
    token = convert_to_unicode(reader.readline())
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 178, in readline
    self._preread_check()
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 84, in _preread_check     
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\Workstation\.deeppavlov\downloads\bert_models_kbqa\cased_L-12_H-768_A-12\vocab.txt : The system cannot find the path specified.
; No such process
```

And the `pip freeze` output is:
```
(deeplov) C:\Users\Workstation>pip freeze
absl-py==0.12.0
aio-pika==6.4.1
aiormq==3.3.1
astor==0.8.1
bert-dp @ git+https://github.com/deepmipt/bert.git@741d9bed9d52c6a9409ca27d8bf284615645618b
certifi==2020.12.5
cffi==1.14.5
chardet==3.0.4
click==7.1.2
cryptography==3.4.7
Cython==0.29.14
dataclasses==0.8
DAWG-Python==0.7.2
deeppavlov==0.14.0
docopt==0.6.2
fastapi==0.47.1
filelock==3.0.12
gast==0.2.2
google-pasta==0.2.0
grpcio==1.37.1
h11==0.9.0
h5py==2.10.0
idna==2.8
importlib-metadata==4.0.1
joblib==1.0.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
Markdown==3.3.4
multidict==5.1.0
nltk==3.4.5
numpy==1.18.0
opt-einsum==3.3.0
overrides==2.7.0
pamqp==2.3.0
pandas==0.25.3
prometheus-client==0.7.1
protobuf==3.16.0
pycparser==2.20
pydantic==1.3
pymorphy2==0.8
pymorphy2-dicts==2.4.393442.3710985
pymorphy2-dicts-ru==2.4.417127.4579844
pyOpenSSL==19.1.0
pyTelegramBotAPI==3.6.7
python-dateutil==2.8.1
pytz==2019.1
requests==2.22.0
ruamel.yaml==0.15.100
rusenttokenize==0.0.5
sacremoses==0.0.35
scikit-learn==0.21.2
scipy==1.4.1
six==1.16.0
starlette==0.12.9
tensorboard==1.15.0
tensorflow==1.15.2
tensorflow-estimator==1.15.1
termcolor==1.1.0
tqdm==4.41.1
typing-extensions==3.10.0.0
urllib3==1.25.11
uvicorn==0.11.7
websockets==8.1
Werkzeug==1.0.1
wincertstore==0.2
wrapt==1.12.1
yarl==1.6.3
zipp==3.4.1
```

**Comment by Aryagm** [comment]
There was an error while installing the model using `python -m deeppavlov install kbqa_cq`:

```
(deeplov) C:\Users\Workstation>python -m deeppavlov install kbqa_cq
2021-05-07 09:08:50.216 INFO in 'deeppavlov.core.common.file'['file'] at line 32: Interpreting 'kbqa_cq' as 'C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\deeppavlov\configs\kbqa\kbqa_cq.json'
Collecting rapidfuzz==0.7.6
  Using cached rapidfuzz-0.7.6-cp36-cp36m-win_amd64.whl (57 kB)
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-0.7.6
Collecting whapi==0.6.2
  Using cached whapi-0.6.2-py3-none-any.whl (5.8 kB)
Requirement already satisfied: requests in c:\users\workstation\anaconda3\envs\deeplov\lib\site-packages (from whapi==0.6.2) (2.22.0)
Collecting bs4
  Using cached bs4-0.0.1-py3-none-any.whl
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting soupsieve>1.2
  Using cached soupsieve-2.2.1-py3-none-any.whl (33 kB)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\workstation\anaconda3\envs\deeplov\lib\site-packages (from requests->whapi==0.6.2) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\workstation\anaconda3\envs\deeplov\lib\site-packages (from requests->whapi==0.6.2) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\workstation\anaconda3\envs\deeplov\lib\site-packages (from requests->whapi==0.6.2) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\workstation\anaconda3\envs\deeplov\lib\site-packages (from requests->whapi==0.6.2) (2020.12.5)
Installing collected packages: soupsieve, beautifulsoup4, bs4, whapi
Successfully installed beautifulsoup4-4.9.3 bs4-0.0.1 soupsieve-2.2.1 whapi-0.6.2
Collecting beautifulsoup4==4.9.0
  Using cached beautifulsoup4-4.9.0-py3-none-any.whl (109 kB)
Requirement already satisfied: soupsieve>1.2 in c:\users\workstation\anaconda3\envs\deeplov\lib\site-packages (from beautifulsoup4==4.9.0) (2.2.1)
Installing collected packages: beautifulsoup4
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.9.3
    Uninstalling beautifulsoup4-4.9.3:
      Successfully uninstalled beautifulsoup4-4.9.3
Successfully installed beautifulsoup4-4.9.0
Collecting fasttext==0.9.1
  Using cached fasttext-0.9.1-cp36-cp36m-win_amd64.whl
Requirement already satisfied: numpy in c:\users\workstation\anaconda3\envs\deeplov\lib\site-packages (from fasttext==0.9.1) (1.18.0)
Collecting pybind11>=2.2
  Using cached pybind11-2.6.2-py2.py3-none-any.whl (191 kB)
Requirement already satisfied: setuptools>=0.7.0 in c:\users\workstation\anaconda3\envs\deeplov\lib\site-packages (from fasttext==0.9.1) (49.6.0.post20210108)
Installing collected packages: pybind11, fasttext
Successfully installed fasttext-0.9.1 pybind11-2.6.2
Collecting faiss-gpu==1.6.3
  Using cached faiss-gpu-1.6.3.tar.gz (17 kB)
Requirement already satisfied: numpy in c:\users\workstation\anaconda3\envs\deeplov\lib\site-packages (from faiss-gpu==1.6.3) (1.18.0)
Building wheels for collected packages: faiss-gpu
  Building wheel for faiss-gpu (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Workstation\anaconda3\envs\deeplov\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\WORKST~1\\AppData\\Local\\Temp\\pip-install-nivt86vi\\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\\setup.py'"'"'; __file__='"'"'C:\\Users\\WORKST~1\\AppData\\Local\\Temp\\pip-install-nivt86vi\\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\WORKST~1\AppData\Local\Temp\pip-wheel-lleznrv2'
       cwd: C:\Users\WORKST~1\AppData\Local\Temp\pip-install-nivt86vi\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\
  Complete output (36 lines):
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\WORKST~1\AppData\Local\Temp\pip-install-nivt86vi\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\setup.py", line 111, in <module>
      ext_modules=[_swigfaiss]
    File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\setuptools\__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\WORKST~1\AppData\Local\Temp\pip-install-nivt86vi\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\setup.py", line 45, in run
      build_ext.run(self)
    File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Users\WORKST~1\AppData\Local\Temp\pip-install-nivt86vi\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\setup.py", line 50, in build_extensions
      self._remove_flag('-Wstrict-prototypes')
    File "C:\Users\WORKST~1\AppData\Local\Temp\pip-install-nivt86vi\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\setup.py", line 58, in _remove_flag
      compiler = self.compiler.compiler
  AttributeError: 'MSVCCompiler' object has no attribute 'compiler'
  ----------------------------------------
  ERROR: Failed building wheel for faiss-gpu
  Running setup.py clean for faiss-gpu
Failed to build faiss-gpu
Installing collected packages: faiss-gpu
    Running setup.py install for faiss-gpu ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Workstation\anaconda3\envs\deeplov\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\WORKST~1\\AppData\\Local\\Temp\\pip-install-nivt86vi\\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\\setup.py'"'"'; __file__='"'"'C:\\Users\\WORKST~1\\AppData\\Local\\Temp\\pip-install-nivt86vi\\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\WORKST~1\AppData\Local\Temp\pip-record-o32esfep\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Workstation\anaconda3\envs\deeplov\Include\faiss-gpu'
         cwd: C:\Users\WORKST~1\AppData\Local\Temp\pip-install-nivt86vi\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\
    Complete output (38 lines):
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\WORKST~1\AppData\Local\Temp\pip-install-nivt86vi\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\setup.py", line 111, in <module>
        ext_modules=[_swigfaiss]
      File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\setuptools\__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\WORKST~1\AppData\Local\Temp\pip-install-nivt86vi\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\setup.py", line 45, in run
        build_ext.run(self)
      File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\WORKST~1\AppData\Local\Temp\pip-install-nivt86vi\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\setup.py", line 50, in build_extensions
        self._remove_flag('-Wstrict-prototypes')
      File "C:\Users\WORKST~1\AppData\Local\Temp\pip-install-nivt86vi\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\setup.py", line 58, in _remove_flag
        compiler = self.compiler.compiler
    AttributeError: 'MSVCCompiler' object has no attribute 'compiler'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Workstation\anaconda3\envs\deeplov\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\WORKST~1\\AppData\\Local\\Temp\\pip-install-nivt86vi\\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\\setup.py'"'"'; __file__='"'"'C:\\Users\\WORKST~1\\AppData\\Local\\Temp\\pip-install-nivt86vi\\faiss-gpu_6a5f06040a6744db9b6c26d71f33cd6c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\WORKST~1\AppData\Local\Temp\pip-record-o32esfep\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Workstation\anaconda3\envs\deeplov\Include\faiss-gpu' Check the logs for full command output.
Traceback (most recent call last):
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\deeppavlov\__main__.py", line 4, in <module>
    main()
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\deeppavlov\deep.py", line 130, in main
    install_from_config(pipeline_config_path)
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\deeppavlov\utils\pip_wrapper\pip_wrapper.py", line 71, in install_from_config
    install(r)
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\site-packages\deeppavlov\utils\pip_wrapper\pip_wrapper.py", line 38, in install
    env=os.environ.copy())
  File "C:\Users\Workstation\anaconda3\envs\deeplov\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Workstation\\anaconda3\\envs\\deeplov\\python.exe', '-m', 'pip', 'install', 'faiss-gpu==1.6.3']' returned non-zero exit status 1.
```
