### ISSUE TITLE
Windows support for DeepPavlov v0.14.1 and v0.15.0

### ISSUE THREAD

**Issue by priyankshah7** [deepmipt/DeepPavlov#1467]
**DeepPavlov version** : 0.14.1 and 0.15.0
**Python version**: 3.7
**Operating system** (ubuntu linux, windows, ...): Windows 10

**Issue**: 
Attempting to upgrade to v0.14.1 or v0.15.0 encounters an error on Windows as uvloop is not supported on Windows. Is this a noted issue or are there any workarounds? 

See installation error traceback (file paths removed):

**Error (including full traceback)**:
```
(venv) C:\...>pip install --upgrade deeppavlov==0.14.1
Collecting deeppavlov==0.14.1
  Using cached deeppavlov-0.14.1-py3-none-any.whl (988 kB)
Requirement already satisfied: numpy==1.18.0 in c:\... (from deeppavlov==0.14.1) (1.18.0)
Requirement already satisfied: overrides==2.7.0 in c:\... (from deeppavlov==0.14.1) (2.7.0)
Requirement already satisfied: h5py==2.10.0 in c:\... (from deeppavlov==0.14.1) (2.10.0)
Requirement already satisfied: click==7.1.2 in c:\... (from deeppavlov==0.14.1) (7.1.2)
Requirement already satisfied: rusenttokenize==0.0.5 in c:\... (from deeppavlov==0.14.1) (0.0.5)
Requirement already satisfied: pytelegrambotapi==3.6.7 in c:\... (from deeppavlov==0.14.1) (3.6.7)
Requirement already satisfied: pandas==0.25.3 in c:\... (from deeppavlov==0.14.1) (0.25.3)
Requirement already satisfied: scikit-learn==0.21.2 in c:\... (from deeppavlov==0.14.1) (0.21.2)
Requirement already satisfied: aio-pika==6.4.1 in c:\... (from deeppavlov==0.14.1) (6.4.1)
Requirement already satisfied: pytz==2019.1 in c:\... (from deeppavlov==0.14.1) (2019.1)
Requirement already satisfied: Cython==0.29.14 in c:\... (from deeppavlov==0.14.1) (0.29.14)
Requirement already satisfied: scipy==1.4.1 in c:\... (from deeppavlov==0.14.1) (1.4.1)
Requirement already satisfied: pymorphy2==0.8 in c:\... (from deeppavlov==0.14.1) (0.8)
Requirement already satisfied: sacremoses==0.0.35 in c:\... (from deeppavlov==0.14.1) (0.0.35)
Requirement already satisfied: pyopenssl==19.1.0 in c:\... (from deeppavlov==0.14.1) (19.1.0)
Requirement already satisfied: pymorphy2-dicts-ru in c:\... (from deeppavlov==0.14.1) (2.4.417127.4579844)
Requirement already satisfied: prometheus-client==0.7.1 in c:\... (fromdeeppavlov==0.14.1) (0.7.1)
Requirement already satisfied: ruamel.yaml==0.15.100 in c:\... (from deeppavlov==0.14.1) (0.15.100)
Requirement already satisfied: filelock==3.0.12 in c:\... (from deeppavlov==0.14.1) (3.0.12)
Requirement already satisfied: fastapi==0.47.1 in c:\... (from deeppavlov==0.14.1) (0.47.1)
Requirement already satisfied: tqdm==4.41.1 in c:\... (from deeppavlov==0.14.1) (4.41.1)
Requirement already satisfied: requests==2.22.0 in c:\... (from deeppavlov==0.14.1) (2.22.0)
Requirement already satisfied: pydantic==1.3 in c:\... (from deeppavlov==0.14.1) (1.3)
Collecting uvloop==0.14.0
  Using cached uvloop-0.14.0.tar.gz (2.0 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\...\venv\scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\...\\AppData\\Local\\Temp\\pip-install-_6m26rhl\\uvloop_f3b1771d349c4f5facada899f0c22cec\\setup.py'"'"'; __file__='"'"'C:\\...\\AppData\\Local\\Temp\\pip-install-_6m26rhl\\uvloop_f3b1771d349c4f5facada899f0c22cec\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.re
ad().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\...\AppData\Local\Temp\pip-pip-egg-info-x2q39lc9'
         cwd: C:\...\AppData\Local\Temp\pip-install-_6m26rhl\uvloop_f3b1771d349c4f5facada899f0c22cec\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\...\AppData\Local\Temp\pip-install-_6m26rhl\uvloop_f3b1771d349c4f5facada899f0c22cec\setup.py", line 15, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/84/2e/462e7a25b787d2b40cf6c9864a9e702f358349fc9cfb77e83c38acb73048/uvloop-0.14.0.ta
r.gz#sha256=123ac9c0c7dd71464f58f1b4ee0bbd81285d96cdda8bc3519281b8973e3a461e (from https://pypi.org/simple/uvloop/). Command errored out with e
xit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement uvloop==0.14.0 (from deeppavlov) (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4
.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23,
 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30, 0.4.31, 0.4.32, 0.4.33, 0.4.34, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.5
, 0.6.6, 0.6.7, 0.6.8, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0r
c1, 0.12.0, 0.12.1, 0.12.2, 0.13.0rc1, 0.13.0, 0.14.0rc1, 0.14.0rc2, 0.14.0, 0.15.0, 0.15.1, 0.15.2, 0.15.3)
ERROR: No matching distribution found for uvloop==0.14.0

```

**Comment by xelandar** [comment]
Same problem here when installing latest (to the date of this comment) version of DeepPavlov. It seems that this bug is still, well, a bug?

**Comment by Twenkid** [comment]
I faced that uvloop error too, Windows 10, a fresh Python 3.7.8, current DeepPavlov 0.17.2

![image](https://user-images.githubusercontent.com/23367640/156857555-0b19b29f-db15-4d09-a41a-0c1f800b59ab.png)

Collecting uvloop==0.14.0
  Using cached uvloop-0.14.0.tar.gz (2.0 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\py37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\toshb\\AppData\\Local\\Temp\\pip-install-5bopor8t\\uvloop\\setup.py'"'"'; __file__='"'"'C:\\Users\\toshb\\AppData\\Local\\Temp\\pip-install-5bopor8t\\uvloop\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\toshb\AppData\Local\Temp\pip-pip-egg-info-asul5dr_'
         cwd: C:\Users\toshb\AppData\Local\Temp\pip-install-5bopor8t\uvloop\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\toshb\AppData\Local\Temp\pip-install-5bopor8t\uvloop\setup.py", line 15, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 22.0.3 is available.
You should consider upgrading via the 'c:\py37\python.exe -m pip install --upgrade pip' command.

**Comment by IgnatovFedor** [comment]
We have issues with the Windows support. In 1.0.0rc0 Windows is removed from the list of supported platforms. We hope to return Windows support after 1.0.0 release.

**Comment by blinov-89** [comment]
Same problem here when installing latest (to the date of this comment) version of DeepPavlov in pycharm.

**Comment by blinov-89** [comment]
I installed the version 1.0.0rc0 and it was installed successfully

**Comment by Twenkid** [comment]
> I installed the version 1.0.0rc0 and it was installed successfully

@blinov-89 Thanks for reporting! Now I also managed to install it successfully on Python 3.9.7, Win 10, pip. It worked without conda. For now I just installed, imported etc.; I'll test it in action later.

```Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeppavlov
>>> dir(deeppavlov)
['Chainer', 'Element', 'Model', 'Path', '__author__', '__builtins__', '__cached__', '__description__', '__doc__', '__email__', '__file__', '__keywords__', '__license__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_meta', 'build_model', 'configs', 'core', 'deep_download', 'dot_dp_path', 'download', 'evaluate_model', 'init_logger', 'sys', 'train_evaluate_model_from_config', 'train_model']
>>> help(deeppavlov.train_model)
Help on function train_model in module deeppavlov:

train_model(config: [<class 'str'>, <class 'pathlib.Path'>, <class 'dict'>], download: bool = False, recursive: bool = False) -> deeppavlov.core.common.chainer.Chainer
    # TODO: make better

>>> dir(deeppavlov.download)
['ArgumentParser', 'Dict', 'FileLock', 'Iterable', 'List', 'Namespace', 'Optional', 'Path', 'Set', 'Tuple', 'Union', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'check_md5', 'deep_download', 'deeppavlov', 'defaultdict', 'download', 'download_decompress', 'download_resource', 'download_resources', 'expand_path', 'file_md5', 'getLogger', 'get_all_elems_from_json', 'get_config_downloads', 'get_configs_downloads', 'get_download_token', 'log', 'main', 'parse_config', 'parser', 'path_set_md5', 'requests', 'secrets', 'set_query_parameter', 'shutil', 'sys', 'urlparse']
>>>```
