### ISSUE TITLE
train the model on a new data  

### ISSUE THREAD

**Issue by Oumaimalh** [deepmipt/DeepPavlov#1468]
Hi i was trying to retrain the pretrained ner_ru_bert model on my data but when I run the following command
```
**    with configs.ner.ner_rus_bert.open(encoding='utf8') as f:
        ner_config = json.load(f)

    ner_config['chainer'] = {'in': ['x'],
                            'in_y': ['y'],
     'pipe': [{'class_name': 'bert_ner_preprocessor',
               'vocab_file': '{BERT_PATH}/vocab.txt',
               'do_lower_case': False,
               'max_seq_length': 512,
               'max_subword_length': 15,
               'token_masking_prob': 0.0,
               'in': ['x'],
               'out': ['x_tokens',
                       'x_subword_tokens',
                       'x_subword_tok_ids',
                       'startofword_markers',
                       'attention_mask']},
              {'id': 'tag_vocab',
               'class_name': 'simple_vocab',
               'unk_token': ['O'],
               'pad_with_zeros': True,
               'save_path': '',
               "load_path": "",

               'in': ['y'],
               'out': ['y_ind']},
              {'class_name': 'bert_sequence_tagger',
               "n_tags": "#tag_vocab.len",
               'keep_prob': 0.1,
               'bert_config_file': '{BERT_PATH}/bert_config.json',
               'pretrained_bert': '{BERT_PATH}/bert_model.ckpt',
               'attention_probs_keep_prob': 0.5,
               'use_crf': True,
               'ema_decay': 0.9,
               'return_probas': False,
               'encoder_layer_ids': [-1],
               'optimizer': 'tf.train:AdamOptimizer',
               'learning_rate': 0.001,
               'bert_learning_rate': 2e-05,
               'min_learning_rate': 1e-07,
               'learning_rate_drop_patience': 30,
               'learning_rate_drop_div': 1.5,
               'load_before_drop': True,
               'clip_norm': 'NULL',
               'save_path': '',
               "load_path":'',
               'in': ['x_subword_tok_ids', 'attention_mask', 'startofword_markers'],
               'in_y': ['y_ind'],
               'out': ['y_pred_ind']},
              {'ref': 'tag_vocab', 'in': ['y_pred_ind'], 'out': ['y_pred']}],
     'out': ['x_tokens', 'y_pred']}

    ner_config['dataset_reader']['data_path'] = path

    ner_model = build_model(configs.ner.ner_rus_bert, download=True)
    ner_model = train_model(ner_config,download=True)

**
```
 I'm getting this error:

```

**
2021-07-22 17:03:57.562 WARNING in 'deeppavlov.core.models.serializable'['serializable'] at line 52: No load path is set for SimpleVocabulary!
2021-07-22 17:03:57.567 WARNING in 'deeppavlov.core.models.serializable'['serializable'] at line 52: No load path is set for BertSequenceTagger!
2021-07-22 17:04:03.4 ERROR in 'deeppavlov.core.common.params'['params'] at line 112: Exception in <class 'deeppavlov.models.bert.bert_sequence_tagger.BertSequenceTagger'>
Traceback (most recent call last):
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 528, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1273, in internal_convert_to_tensor
    (dtype.name, value.dtype.name, value))
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype string: <tf.Tensor 'Optimizer_1/clip_by_norm/mul_1/y:0' shape=() dtype=string>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/common/params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_backend.py", line 76, in __call__
    obj.__init__(*args, **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 529, in __init__
    **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 242, in __init__
    self._init_optimizer()
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 348, in _init_optimizer
    optimizer_scope_name='Optimizer')
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 378, in get_train_op
    **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_model.py", line 241, in get_train_op
    return TFModel.get_train_op(self, loss, **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_model.py", line 148, in get_train_op
    for grad, var in grads_and_vars]
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_model.py", line 148, in <listcomp>
    for grad, var in grads_and_vars]
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_model.py", line 142, in clip_if_not_none
    return tf.clip_by_norm(grad, clip_norm)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/tensorflow_core/python/ops/clip_ops.py", line 174, in clip_by_norm
    intermediate = values * clip_norm
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 912, in binary_op_wrapper
    return func(x, y, name=name)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 1206, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 6701, in mul
    "Mul", x=x, y=y, name=name)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 564, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Mul' Op has type string that does not match type float32 of argument 'x'.
Traceback (most recent call last):
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 528, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1273, in internal_convert_to_tensor
    (dtype.name, value.dtype.name, value))
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype string: <tf.Tensor 'Optimizer_1/clip_by_norm/mul_1/y:0' shape=() dtype=string>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/oumaimalahiani/Documents/labelling-api/labelling/russian_train.py", line 92, in <module>
    cli()
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/oumaimalahiani/Documents/labelling-api/labelling/russian_train.py", line 81, in train_rubert
    ner_model = train_model(ner_config,download=True)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/__init__.py", line 29, in train_model
    train_evaluate_model_from_config(config, download=download, recursive=recursive)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/commands/train.py", line 121, in train_evaluate_model_from_config
    trainer.train(iterator)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/trainers/nn_trainer.py", line 334, in train
    self.fit_chainer(iterator)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/trainers/fit_trainer.py", line 104, in fit_chainer
    component = from_params(component_config, mode='train')
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/common/params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_backend.py", line 76, in __call__
    obj.__init__(*args, **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 529, in __init__
    **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 242, in __init__
    self._init_optimizer()
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 348, in _init_optimizer
    optimizer_scope_name='Optimizer')
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/models/bert/bert_sequence_tagger.py", line 378, in get_train_op
    **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_model.py", line 241, in get_train_op
    return TFModel.get_train_op(self, loss, **kwargs)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_model.py", line 148, in get_train_op
    for grad, var in grads_and_vars]
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_model.py", line 148, in <listcomp>
    for grad, var in grads_and_vars]
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/deeppavlov/core/models/tf_model.py", line 142, in clip_if_not_none
    return tf.clip_by_norm(grad, clip_norm)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/tensorflow_core/python/ops/clip_ops.py", line 174, in clip_by_norm
    intermediate = values * clip_norm
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 912, in binary_op_wrapper
    return func(x, y, name=name)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 1206, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 6701, in mul
    "Mul", x=x, y=y, name=name)
  File "/Users/oumaimalahiani/.virtualenvs/labelling-api/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 564, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Mul' Op has type string that does not match type float32 of argument 'x'.
**:
```

```

**Comment by Ihab-Asaad** [comment]
Hi, use clip_norm = None instead of clip_norm = 'NULL'
Also you have to add "fit_on": ["y"], and provide save_path in config.
