### ISSUE TITLE
NER ModuleNotFoundError: No module named 'bert_dp' 

### ISSUE THREAD

**Issue by uk2804** [deepmipt/DeepPavlov#1512]
Hi, When trying to check the pre-trained NER I got the below error..!!

code:
>>> from deeppavlov import configs, build_model
>>> ner_model = build_model(configs.ner.ner_ontonotes_bert)

Error: 

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\UdhayaNavi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\UdhayaNavi\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package perluniprops to
[nltk_data]     C:\Users\UdhayaNavi\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping misc\perluniprops.zip.
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     C:\Users\UdhayaNavi\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\nonbreaking_prefixes.zip.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\AI\Anaconda3\envs\UKNEW\lib\site-packages\deeppavlov\core\commands\infer.py", line 62, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "D:\AI\Anaconda3\envs\UKNEW\lib\site-packages\deeppavlov\core\common\params.py", line 95, in from_params
    obj = get_model(cls_name)
  File "D:\AI\Anaconda3\envs\UKNEW\lib\site-packages\deeppavlov\core\common\registry.py", line 72, in get_model
    return cls_from_str(_REGISTRY[name])
  File "D:\AI\Anaconda3\envs\UKNEW\lib\site-packages\deeppavlov\core\common\registry.py", line 40, in cls_from_str
    return getattr(importlib.import_module(module_name), cls_name)
  File "D:\AI\Anaconda3\envs\UKNEW\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\AI\Anaconda3\envs\UKNEW\lib\site-packages\deeppavlov\models\preprocessors\bert_preprocessor.py", line 19, in <module>
    from bert_dp.preprocessing import convert_examples_to_features, InputExample, InputFeatures
ModuleNotFoundError: No module named 'bert_dp'

**Comment by 645187919** [comment]
I have the same problem...

**Comment by dimakarp1996** [comment]
You should have done python -m deeppavlov install ner_ontonotes_bert.json first. Then bert_dp will be in place.
