### ISSUE TITLE
deeppavlov.core.common.errors.ConfigError: 'Model torch_transformers_ner_preprocessor is not registered.'

### ISSUE THREAD

**Issue by 645187919** [deepmipt/DeepPavlov#1518]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

Please enter all the information below, otherwise your issue may be closed without a warning. 

**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):
Name: deeppavlov
Version: 0.14.0
**Python version**:
3.6
**Operating system** (ubuntu linux, windows, ...):
windows
**Issue**:
deeppavlov.core.common.errors.ConfigError: 'Model torch_transformers_ner_preprocessor is not registered.'

**Content or a name of a configuration file**:
```

```

**Command that led to error**:
```

```

**Error (including full traceback)**:
```

from deeppavlov import configs, build_model
ner_model = build_model("ner_ontonotes_bert_torch.json", download=True)
ner_model(['Computer Sciences Corp . , El Segundo , Calif . , said it is close to making final an agreement to buy Cleveland Consulting Associates'])

run log:
D:\anaconda\envs\deeplove\lib\site-packages\cryptography\hazmat\backends\openssl\x509.py:17: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  utils.DeprecatedIn35,
2022-01-27 14:33:23.540 INFO in 'deeppavlov.core.data.utils'['utils'] at line 94: Downloading from http://files.deeppavlov.ai/v1/ner/ner_ontonotes_bert_torch.tar.gz to C:\Users\64518\.deeppavlov\ner_ontonotes_bert_torch.tar.gz
100%|██████████| 1.12G/1.12G [17:09<00:00, 1.09MB/s]
2022-01-27 14:50:35.351 INFO in 'deeppavlov.core.data.utils'['utils'] at line 268: Extracting C:\Users\64518\.deeppavlov\ner_ontonotes_bert_torch.tar.gz archive into C:\Users\64518\.deeppavlov\models
Traceback (most recent call last):
  File "D:/my_demo/NER/deeppavlov_demo.py", line 10, in <module>
    ner_model = build_model("ner_ontonotes_bert_torch.json", download=True)
  File "D:\anaconda\envs\deeplove\lib\site-packages\deeppavlov\core\commands\infer.py", line 62, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "D:\anaconda\envs\deeplove\lib\site-packages\deeppavlov\core\common\params.py", line 95, in from_params
    obj = get_model(cls_name)
  File "D:\anaconda\envs\deeplove\lib\site-packages\deeppavlov\core\common\registry.py", line 70, in get_model
    raise ConfigError("Model {} is not registered.".format(name))
deeppavlov.core.common.errors.ConfigError: 'Model torch_transformers_ner_preprocessor is not registered.'
```

**Comment by dimakarp1996** [comment]
The bug was fixed in 0.15.0.
