### ISSUE TITLE
Could not find a version that satisfies the requirement uvloop==0.14.0 (from deeppavlov)

### ISSUE THREAD

**Issue by 645187919** [deepmipt/DeepPavlov#1519]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

Please enter all the information below, otherwise your issue may be closed without a warning. 

**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):

**Python version**:
python==3.6
**Operating system** (ubuntu linux, windows, ...):
windows
**Issue**:

**Content or a name of a configuration file**:
```

```

**Command that led to error**:
```
pip install deeppavlov==0.17.0
pip install deeppavlov==0.15.0
```

**Error (including full traceback)**:
```
Collecting pymorphy2==0.8
  Using cached pymorphy2-0.8-py2.py3-none-any.whl (46 kB)
Collecting uvloop==0.14.0
  Using cached uvloop-0.14.0.tar.gz (2.0 MB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\anaconda\envs\deeplove\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\64518\\AppData\\Local\\Temp\\pip-install-l6up2mdb\\uvloop_b30d837ca1cd4ee69a0d711ff1872366\\setup.py'"'"'; __file__=
'"'"'C:\\Users\\64518\\AppData\\Local\\Temp\\pip-install-l6up2mdb\\uvloop_b30d837ca1cd4ee69a0d711ff1872366\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools imp
ort setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\64518\AppData\Local\Temp\pip-pip-egg-info-ucpd9os3'
         cwd: C:\Users\64518\AppData\Local\Temp\pip-install-l6up2mdb\uvloop_b30d837ca1cd4ee69a0d711ff1872366\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\64518\AppData\Local\Temp\pip-install-l6up2mdb\uvloop_b30d837ca1cd4ee69a0d711ff1872366\setup.py", line 15, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/84/2e/462e7a25b787d2b40cf6c9864a9e702f358349fc9cfb77e83c38acb73048/uvloop-0.14.0.tar.gz#sha256=123ac9c0c7dd71464f58f1b4ee0bbd81285d96cdda8bc3519281b8973e3a461e (from https://pypi.org/si
mple/uvloop/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement uvloop==0.14.0 (from deeppavlov) (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 0.4.18
, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30, 0.4.31, 0.4.32, 0.4.33, 0.4.34, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9
.0, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0rc1, 0.12.0, 0.12.1, 0.12.2, 0.13.0rc1, 0.13.0, 0.14.0rc1, 0.14.0rc2, 0.14.0, 0.15.0, 0.15.1)
ERROR: No matching distribution found for uvloop==0.14.0

```

**Comment by Twenkid** [comment]
Also with Python 3.7.8, deeppavlov 0.17.2 
```
(env) Z:\DeepPavlov-master>c:\py37\python.exe -m pip install deeppavlov
Collecting deeppavlov
  Using cached deeppavlov-0.17.2-py3-none-any.whl (880 kB)
  (...)

Collecting click==7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting uvloop==0.14.0
  Using cached uvloop-0.14.0.tar.gz (2.0 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\py37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\toshb\\AppData\\Local\\Temp\\pip-install-5bopor8t\\uvloop\\setup.py'"'"'; __file__='"'"'C:\\Users\\toshb\\AppData\\Local\\Temp\\pip-install-5bopor8t\\uvloop\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\toshb\AppData\Local\Temp\pip-pip-egg-info-asul5dr_'
         cwd: C:\Users\toshb\AppData\Local\Temp\pip-install-5bopor8t\uvloop\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\toshb\AppData\Local\Temp\pip-install-5bopor8t\uvloop\setup.py", line 15, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 22.0.3 is available.
You should consider upgrading via the 'c:\py37\python.exe -m pip install --upgrade pip' command.
```

**Comment by IgnatovFedor** [comment]
Unfortunately we have problems with Windows support. In the pre-release 1.0.0rc0 we removed Windows from the list of supported platforms. We hope to return to this problem after the release 1.0.0.
