### ISSUE TITLE
ValueError: Cannot feed value of shape (1, 1, 802) for Tensor 'features:0', which has shape '(?, ?, 830)' ]

### ISSUE THREAD

**Issue by dixiematt8** [deepmipt/DeepPavlov#155]
I fired the following command to train from scratch...

` python -m deeppavlov.deep train deeppavlov/configs/go_bot/gobot_dstc2_all.json `

I get the following error.

```
[Traceback (most recent call last):
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/deep.py", line 62, in <module>
    main()
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/deep.py", line 49, in main
    train_model_from_config(pipeline_config_path)
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/core/commands/train.py", line 127, in train_model_from_config
    _train_batches(model, iterator, train_config, metrics_functions)
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/core/commands/train.py", line 229, in _train_batches
    y_predicted = list(model(list(x)))
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/core/common/chainer.py", line 88, in __call__
    res = component(*[mem[k] for k in in_params])
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/skills/go_bot/bot.py", line 251, in __call__
    return [self._infer_dialog(x) for x in batch]
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/skills/go_bot/bot.py", line 251, in <listcomp>
    return [self._infer_dialog(x) for x in batch]
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/skills/go_bot/bot.py", line 245, in _infer_dialog
    res.append(self._infer(context['text'], context.get('db_result')))
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/skills/go_bot/bot.py", line 220, in _infer
    prob=True
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/skills/go_bot/network.py", line 62, in __call__
    self._action_mask: action_mask
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 1, 802) for Tensor 'features:0', which has shape '(?, ?, 830)'
]
```

**Comment by seliverstov** [comment]
Can you update code and re-download models?
```
git pull
python -m deeppavlov.download
```

**Comment by yanavvo** [comment]
really appreciate you can share how to train the go_bot model from scratch. I got similar error:
ValueError: Cannot feed value of shape (1, 1, 493) for Tensor 'features:0', which has shape '(1, ?, 530)'

**Comment by vikmary** [comment]
You should find `"obs_size"` parameter in `"network"` section  of your config file and set it to "to number of `"bow_embedder"` features, `"embedder"` features, `"intent_classifier"` features, context features(=2) plus `"tracker"` state size plus action size" as it is said in the [`deeppavlov/skills/go_bot/README.md`](https://github.com/deepmipt/DeepPavlov/tree/master/deeppavlov/skills/go_bot/README.md).

You can skip the calculation of the sum and just set `"obs_size": "493"`, because according to your ValueError a feature (observation) vector with the dimension of "493" is being fed to network (while dimension size equal to 530 is expected).

**Comment by dixiematt8** [comment]
@vikmary : I did as you said, but I get the following error next.

```
Traceback (most recent call last):
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/deep.py", line 62, in <module>
    main()
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/deep.py", line 49, in main
    train_model_from_config(pipeline_config_path)
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/core/commands/train.py", line 127, in train_model_from_config
    _train_batches(model, iterator, train_config, metrics_functions)
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/core/commands/train.py", line 229, in _train_batches
    y_predicted = list(model(list(x)))
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/core/common/chainer.py", line 88, in __call__
    res = component(*[mem[k] for k in in_params])
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/skills/go_bot/bot.py", line 251, in __call__
    return [self._infer_dialog(x) for x in batch]
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/skills/go_bot/bot.py", line 251, in <listcomp>
    return [self._infer_dialog(x) for x in batch]
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/skills/go_bot/bot.py", line 245, in _infer_dialog
    res.append(self._infer(context['text'], context.get('db_result')))
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/skills/go_bot/bot.py", line 218, in _infer
    [[self._encode_context(context, db_result)]],
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/skills/go_bot/bot.py", line 123, in _encode_context
    self.tracker.update_state(self.slot_filler([tokenized])[0])
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/models/ner/slotfill.py", line 105, in __call__
    tags_batch = self._ner_network.predict_for_token_batch(batch)
  File "/n/w1-mdixie/Others_Models/DeepPavlov_Train/DeepPavlov/deeppavlov/models/ner/network.py", line 397, in predict_for_token_batch
    viterbi_seq, viterbi_score = tf.contrib.crf.viterbi_decode(logit, trans_params)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/tensorflow/contrib/crf/python/ops/crf.py", line 317, in viterbi_decode
    trellis[t] = score[t] + np.max(v, 0)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2320, in amax
    out=out, **kwargs)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity

```

**Comment by yanavvo** [comment]
The problem is that when we start train_model_from_config, the initial model needs to be loaded. There are five files: checkpoint, model.data-00000-of-00001, model.index, model.json, and model.meta. Though I modified obs_size from 530 to 493 in both gobot_dstc2.json and model.json, I still got errors below. Now the question is how to train the model from config and which initial model meta data can be deleted. Thank you.

tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [493,64] rhs shape= [530,64]

**Comment by vikmary** [comment]
In case you want to train your model from scratch, change `load_path` and `save_path` to a new name. It will not load the pretrained model then.

Be ware that in order to train your model from [configs/go_bot/gobot_dstc2.json](https://github.com/deepmipt/DeepPavlov/tree/master/deeppavlov/configs/go_bot/gobot_dstc2.json) you need firstly to train correspoding
1. `slot_filler` model [configs/ner/slotfill_dstc2.json](https://github.com/deepmipt/DeepPavlov/tree/master/deeppavlov/configs/ner/slotfill_dstc2.json)
2. `intent_classifier` model [configs/intents/intents_dstc2.json](https://github.com/deepmipt/DeepPavlov/tree/master/deeppavlov/configs/intents/intents_dstc2.json)

If you want a minimal model without slot filling and intent classification, use [configs/go_bot/gobot_dstc2_minimal.json](https://github.com/deepmipt/DeepPavlov/tree/master/deeppavlov/configs/go_bot/gobot_dstc2_minimla.json) -- it doesn't require any pretrained models.

**Comment by yanavvo** [comment]
Great, thanks for the advice! Let me try it.

**Comment by mu-arkhipov** [comment]
@dixiematt8 Please check that the data you pass to the slot filler contains no empty sequences. If it is not the case than please try to provide the token sequence on which the error occurs.
