### ISSUE TITLE
ERROR while training rel_ranking model of KBQA pipeline

### ISSUE THREAD

**Issue by Kefan-pauline** [deepmipt/DeepPavlov#1583]
**DeepPavlov version**: 0.14.0 and 0.17.4

**Python version**: 3.7.9 and 3.7.12

**Operating system** (ubuntu linux, windows, ...): Windows and Linux

**Issue**:

*ValueError: Classification metrics can't handle a mix of binary and multiclass-multioutput targets* occurs while training **rel_ranking** model of **KBQA** pipeline with Python 3.7, both with DeepPavlov 0.17.4 on Linux and DeepPavlov 0.14.0 on Windows.

The training data (**paraphrases.xml** and **paraphrases_gold.xml**) is downloaded from DeepPavlov's website, thus it is the same as what is used to train the original rel_ranking model. After investigation, I think that *y_true* is binary and *y_pred* is multiclass-multioutput. I guess that the prediction is in terms of probability given that it is a ranker.

The original rel_ranking model works with
```
q = ['What is vehicle normally used for Convertible ?']
rels =  ['category main topic', 'vehicle normally used', 'has use', 'has part or parts', 'item for this sense', 'automotive.generation.platforms', 'architecture.engineering_firm.projects']
rel_ranking_model(q, rels)
```

 But my goal was to do transfer learning, i.e., to further train this model with my own data in order to better adapt the model to a closed-domain (e.g., medical domain).

**Additional questions:**
*  Is it possible to further train a pre-trained model with own data?
*  If it is not possible, is there any better practice other than concatenating your training data with my own training data or training only with my own data?

**Content or a name of a configuration file**:
```
configs/ranking/rel_ranking.json
```

**Code**:
```
import json
from deeppavlov import train_model, configs

CONFIG_PATH = configs.ranking.rel_ranking
with CONFIG_PATH.open(encoding='utf8') as f:
    rr_config = json.load(f)
    
rr_config['dataset_reader']['data_path'] = 'C:/Users/kefsun1a/Documents/Project/kefan-sun/transfer_learning/data' 
rr_config['metadata']['variables']['MODEL_PATH'] = '{MODELS_PATH}/rel_ranking_customized' 

query_pr = train_model(rr_config, download = True)
```

**Error (including full traceback)**:
```
(deploy) C:\Users\kefsun1a>python C:\Users\kefsun1a\Documents\Project\kefan-sun\transfer_learning\main.py
C:\Users\kefsun1a\deploy\lib\site-packages\cryptography\hazmat\backends\openssl\x509.py:17: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  utils.DeprecatedIn35,
2022-07-25 11:27:44.882 INFO in 'deeppavlov.download'['download'] at line 138: Skipped http://files.deeppavlov.ai/embeddings/reddit_fastText/wordpunct_tok_reddit_comments_2017_11_300.bin download because of matching hashes
2022-07-25 11:27:45.455 INFO in 'deeppavlov.download'['download'] at line 138: Skipped http://files.deeppavlov.ai/kbqa/models/rel_ranking.tar.gz download because of matching hashes
2022-07-25 11:27:46.371 INFO in 'deeppavlov.download'['download'] at line 138: Skipped http://files.deeppavlov.ai/kbqa/datasets/rel_ranking.tar.gz download because of matching hashes
2022-07-25 11:28:08.948 INFO in 'deeppavlov.core.trainers.fit_trainer'['fit_trainer'] at line 68: NNTrainer got additional init parameters ['pytest_max_batches'] that will be ignored:
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kefsun1a\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kefsun1a\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to
[nltk_data]     C:\Users\kefsun1a\AppData\Roaming\nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     C:\Users\kefsun1a\AppData\Roaming\nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\core\trainers\nn_trainer.py:150: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2022-07-25 11:28:16.629 INFO in 'deeppavlov.models.embedders.fasttext_embedder'['fasttext_embedder'] at line 53: [loading fastText embeddings from `C:\Users\kefsun1a\.deeppavlov\downloads\embeddings\wordpunct_tok_reddit_comments_2017_11_300.bin`]
Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\core\models\tf_model.py:37: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\core\models\tf_model.py:222: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\core\models\tf_model.py:222: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\core\models\tf_model.py:193: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\models\ranking\rel_ranker.py:62: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2022-07-25 11:28:21.816277: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\models\ranking\rel_ranker.py:82: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\models\ranking\rel_ranker.py:92: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\tensorflow_core\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py:122: GRUCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.GRUCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\models\squad\utils.py:76: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\models\squad\utils.py:87: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\models\squad\utils.py:101: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\models\squad\utils.py:104: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\tensorflow_core\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py:133: Layer.add_variable (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.add_weight` method instead.
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\tensorflow_core\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py:139: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\tensorflow_core\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py:155: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\models\squad\utils.py:109: calling reverse_sequence (from tensorflow.python.ops.array_ops) with seq_dim is deprecated and will be removed in a future version.
Instructions for updating:
seq_dim is deprecated, use seq_axis instead
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\tensorflow_core\python\util\deprecation.py:507: calling reverse_sequence (from tensorflow.python.ops.array_ops) with batch_dim is deprecated and will be removed in a future version.
Instructions for updating:
batch_dim is deprecated, use batch_axis instead
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\models\ranking\rel_ranker.py:98: calling reduce_sum_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\models\ranking\rel_ranker.py:103: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\tensorflow_core\python\layers\core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\tensorflow_core\python\ops\nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\core\models\tf_model.py:127: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\core\models\tf_model.py:127: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\models\ranking\rel_ranker.py:112: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING:tensorflow:From C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\core\models\tf_model.py:50: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "C:\Users\kefsun1a\Documents\Project\kefan-sun\transfer_learning\main.py", line 19, in <module>
    query_pr = train_model(rr_config, download = True)
  File "C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\__init__.py", line 29, in train_model
    train_evaluate_model_from_config(config, download=download, recursive=recursive)
  File "C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\core\commands\train.py", line 121, in train_evaluate_model_from_config
    trainer.train(iterator)
  File "C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\core\trainers\nn_trainer.py", line 337, in train
    self.train_on_batches(iterator)
  File "C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\core\trainers\nn_trainer.py", line 277, in train_on_batches
    self._validate(iterator)
  File "C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\core\trainers\nn_trainer.py", line 169, in _validate
    start_time=self.start_time)
  File "C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\core\trainers\fit_trainer.py", line 220, in test
    value = metric.fn(*[outputs[i] for i in metric.inputs])
  File "C:\Users\kefsun1a\deploy\lib\site-packages\deeppavlov\metrics\fmeasure.py", line 199, in round_f1
    return f1_score(y_true, predictions)
  File "C:\Users\kefsun1a\deploy\lib\site-packages\sklearn\metrics\classification.py", line 1059, in f1_score
    sample_weight=sample_weight)
  File "C:\Users\kefsun1a\deploy\lib\site-packages\sklearn\metrics\classification.py", line 1182, in fbeta_score
    sample_weight=sample_weight)
  File "C:\Users\kefsun1a\deploy\lib\site-packages\sklearn\metrics\classification.py", line 1415, in precision_recall_fscore_support
    pos_label)
  File "C:\Users\kefsun1a\deploy\lib\site-packages\sklearn\metrics\classification.py", line 1239, in _check_set_wise_labels
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "C:\Users\kefsun1a\deploy\lib\site-packages\sklearn\metrics\classification.py", line 81, in _check_targets
    "and {1} targets".format(type_true, type_pred))
ValueError: Classification metrics can't handle a mix of binary and multiclass-multioutput targets
```

**Comment by dmitrijeuseew** [comment]
@Kefan-pauline I suggest trying to set "return_probas": false
https://github.com/deepmipt/DeepPavlov/blob/eddb44542b43eb0aeacf954a0d98710a3ef3b0ed/deeppavlov/configs/ranking/rel_ranking.json#L44
because "return_probas": true is in inference mode and in training mode the model should output labels.
