### ISSUE TITLE
Stuck post install

### ISSUE THREAD

**Issue by pboz** [deepmipt/DeepPavlov#240]
Hi,

I've gotten DeepPavlov set up on an Ubuntu server with a NVIDIA Tesla K80 GPU, but I can't get DeepPavlov to run any of the download or other commands. I'm at the point where I'm trying to run one of these:

python -m deeppavlov.deep download deeppavlov/configs/squad/squad.json -d
python -m deeppavlov.deep download deeppavlov/configs/go_bot/*.json

I've tried a number of things, but I always end up with this error:

`
/home/pboz/testenv3/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from 'float' to 'np.floating' is deprecated. In future, it will be treated as 'np.float64 == np.dtype(float).type'.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[nltk_data] Downloading package punkt to /home/pboz/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/pboz/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
2018-05-19 21:35:24.547 INFO in 'gensim.utils'['utils'] at line 53: smart_open library not found; falling back to local-filesystem-only
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/pboz/DeepPavlov/deeppavlov/__init__.py", line 44, in <module>
    import deeppavlov.models.embedders.glove_embedder
  File "/home/pboz/DeepPavlov/deeppavlov/models/embedders/glove_embedder.py", line 22, in <module>
    from gensim.models import KeyedVectors
  File "/home/pboz/testenv3/local/lib/python3.6/site-packages/gensim/__init__.py", line 6, in <module>
    from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
  File "/home/pboz/testenv3/local/lib/python3.6/site-packages/gensim/models/__init__.py", line 7, in <module>
    from .coherencemodel import CoherenceModel
  File "/home/pboz/testenv3/local/lib/python3.6/site-packages/gensim/models/coherencemodel.py", line 30, in <module>
    from gensim.models.wrappers import LdaVowpalWabbit, LdaMallet
  File "/home/pboz/testenv3/local/lib/python3.6/site-packages/gensim/models/wrappers/__init__.py", line 5, in <module>
    from .ldamallet import LdaMallet
  File "/home/pboz/testenv3/local/lib/python3.6/site-packages/gensim/models/wrappers/ldamallet.py", line 43, in <module>
    from smart_open import smart_open
  File "/home/pboz/testenv3/local/lib/python3.6/site-packages/smart_open/__init__.py", line 1, in <module>
    from .smart_open_lib import *
  File "/home/pboz/testenv3/local/lib/python3.6/site-packages/smart_open/smart_open_lib.py", line 34, in <module>
    import boto.s3.connection
  File "/home/pboz/testenv3/local/lib/python3.6/site-packages/boto/s3/connection.py", line 30, in <module>
    from boto.auth import detect_potential_s3sigv4
  File "/home/pboz/testenv3/local/lib/python3.6/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
AttributeError: module 'boto' has no attribute 'plugin'
`

As a side note, I'm more of a Java guy, Python isn't my strongest language.

Any help is greatly appreciated.

**Comment by pboz** [comment]
Update... I changed some things and now it works, but even with my notes, I can't tell you which of those things did the trick.
