### ISSUE TITLE
Error while trying to "interact" with intent classifier

### ISSUE THREAD

**Issue by BelowzeroA** [deepmipt/DeepPavlov#252]
dima@HAL9000:~/dev/DeepPavlov/deeppavlov$ python deep.py interact ./configs/intents/intents_dstc2.json
/home/dima/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[nltk_data] Downloading package punkt to /home/dima/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/dima/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
2018-05-30 13:18:09.959 INFO in 'summarizer.preprocessing.cleaner'['textcleaner'] at line 37: 'pattern' package not found; tag filters are not available for English
/home/dima/anaconda3/lib/python3.6/site-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
2018-05-30 13:18:12.732 INFO in 'deeppavlov.models.embedders.fasttext_embedder'['fasttext_embedder'] at line 51: [loading embeddings from `/home/dima/dev/DeepPavlov/download/embeddings/dstc2_fastText_model.bin`]
2018-05-30 13:18:12.776 ERROR in 'deeppavlov.core.common.params'['params'] at line 112: Exception in <class 'deeppavlov.models.embedders.fasttext_embedder.FasttextEmbedder'>
Traceback (most recent call last):
  File "fasttext/fasttext.pyx", line 152, in fasttext.fasttext.load_model
RuntimeError: vector::_M_default_append

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dima/dev/DeepPavlov/deeppavlov/core/common/params.py", line 106, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "/home/dima/dev/DeepPavlov/deeppavlov/models/embedders/fasttext_embedder.py", line 40, in __init__
    self.model = self.load()
  File "/home/dima/dev/DeepPavlov/deeppavlov/models/embedders/fasttext_embedder.py", line 53, in load
    model = Fasttext.load_model(model_file)
  File "fasttext/fasttext.pyx", line 154, in fasttext.fasttext.load_model
Exception: fastText: Cannot load /home/dima/dev/DeepPavlov/download/embeddings/dstc2_fastText_model.bin due to C++ extension failed to allocate the memory
Traceback (most recent call last):
  File "fasttext/fasttext.pyx", line 152, in fasttext.fasttext.load_model
RuntimeError: vector::_M_default_append

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deep.py", line 77, in <module>
    main()
  File "deep.py", line 64, in main
    interact_model(pipeline_config_path)
  File "/home/dima/dev/DeepPavlov/deeppavlov/core/commands/infer.py", line 104, in interact_model
    model = build_model_from_config(config)
  File "/home/dima/dev/DeepPavlov/deeppavlov/core/commands/infer.py", line 43, in build_model_from_config
    component = from_params(component_config, vocabs=[], mode=mode)
  File "/home/dima/dev/DeepPavlov/deeppavlov/core/common/params.py", line 106, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "/home/dima/dev/DeepPavlov/deeppavlov/models/embedders/fasttext_embedder.py", line 40, in __init__
    self.model = self.load()
  File "/home/dima/dev/DeepPavlov/deeppavlov/models/embedders/fasttext_embedder.py", line 53, in load
    model = Fasttext.load_model(model_file)
  File "fasttext/fasttext.pyx", line 154, in fasttext.fasttext.load_model
Exception: fastText: Cannot load /home/dima/dev/DeepPavlov/download/embeddings/dstc2_fastText_model.bin due to C++ extension failed to allocate the memory

32 Gb RAM on the machine

**Comment by dilyararimovna** [comment]
This problem can arise in two cases:
1. if memory is already allocated by another programs
2. if you use old fastText version. Current binary models are trained with fastText==0.8.22 version. Try to reinstall fastText form requirements, and if needed, re-download fastText models.
