### ISSUE TITLE
'Usage of cuDNN RNN layers require GPU along with cuDNN library

### ISSUE THREAD

**Issue by michaelpetrutick** [deepmipt/DeepPavlov#258]
Good day, I can`t start DeepPavlov on my notebook..

python -m deeppavlov.deep interact ./deeppavlov/configs/ner/ner_rus.json
/home/mpoder/Projects/DeepPavlov/venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/home/mpoder/Projects/DeepPavlov/venv/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[nltk_data] Downloading package punkt to /home/mpoder/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/mpoder/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
2018-06-04 15:42:32.709 DEBUG in 'gensim.models.doc2vec'['doc2vec'] at line 73: Fast version of gensim.models.doc2vec is being used
2018-06-04 15:42:32.715 INFO in 'summa.preprocessing.cleaner'['textcleaner'] at line 20: 'pattern' package not found; tag filters are not available for English
2018-06-04 15:42:34.101 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 92: [loading vocabulary from /home/mpoder/Projects/DeepPavlov/DeepPavlov/download/ner_rus/word.dict]
2018-06-04 15:42:34.154 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 92: [loading vocabulary from /home/mpoder/Projects/DeepPavlov/DeepPavlov/download/ner_rus/tag.dict]
2018-06-04 15:42:34.155 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 92: [loading vocabulary from /home/mpoder/Projects/DeepPavlov/DeepPavlov/download/ner_rus/char.dict]
2018-06-04 15:42:34.155 INFO in 'deeppavlov.models.embedders.fasttext_embedder'['fasttext_embedder'] at line 51: [loading embeddings from `/home/mpoder/Projects/DeepPavlov/DeepPavlov/download/embeddings/lenta_lower_100.bin`]
2018-06-04 15:42:36.597520: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2018-06-04 15:42:36.598 ERROR in 'deeppavlov.core.common.params'['params'] at line 112: Exception in <class 'deeppavlov.models.ner.network.NerNetwork'>
Traceback (most recent call last):
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/core/common/params.py", line 106, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 47, in __call__
    obj.__init__(*args, **kwargs)
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/models/ner/network.py", line 102, in __init__
    units = self._build_cudnn_rnn(features, n_hidden_list, cell_type, intra_layer_dropout, self.mask_ph)
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/models/ner/network.py", line 168, in _build_cudnn_rnn
    raise RuntimeError('Usage of cuDNN RNN layers require GPU along with cuDNN library')
RuntimeError: Usage of cuDNN RNN layers require GPU along with cuDNN library
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/deep.py", line 77, in <module>
    main()
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/deep.py", line 64, in main
    interact_model(pipeline_config_path)
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/core/commands/infer.py", line 104, in interact_model
    model = build_model_from_config(config)
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/core/commands/infer.py", line 43, in build_model_from_config
    component = from_params(component_config, vocabs=[], mode=mode)
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/core/common/params.py", line 106, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 47, in __call__
    obj.__init__(*args, **kwargs)
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/models/ner/network.py", line 102, in __init__
    units = self._build_cudnn_rnn(features, n_hidden_list, cell_type, intra_layer_dropout, self.mask_ph)
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/home/mpoder/Projects/DeepPavlov/DeepPavlov/deeppavlov/models/ner/network.py", line 168, in _build_cudnn_rnn
    raise RuntimeError('Usage of cuDNN RNN layers require GPU along with cuDNN library')
RuntimeError: Usage of cuDNN RNN layers require GPU along with cuDNN library

**Comment by mu-arkhipov** [comment]
The network relies on cuDNN implementation of RNN, henceforth you need a GPU to run the model
