### ISSUE TITLE
Problem with train model

### ISSUE THREAD

**Issue by Sneg42** [deepmipt/DeepPavlov#305]
I try training intents with me data and get this mistake
ValueError: Dimension 1 in both shapes must be equal, but are 17 and 2. Shapes are [100,17] and [100,2]. for 'Assign_24' (op: 'Assign') with input shapes: [100,17], [100,2].
How I can fix this?

**Comment by dilyararimovna** [comment]
Hello!
Could you, please, provide more information about error (lines of code where error arised, for example).

**Comment by Sneg42** [comment]
@dilyararimovna 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/core/common/params.py", line 117, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 47, in __call__
    obj.__init__(*args, **kwargs)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/models/classifiers/intents/intent_model.py", line 113, in __init__
    self.model = self.load(**params)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/core/models/keras_model.py", line 157, in load
    model.load_weights(str(weights_path))
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/keras/engine/topology.py", line 2622, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/keras/engine/topology.py", line 3143, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2247, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 615, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 283, in assign
    validate_shape=validate_shape)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 17 and 7. Shapes are [100,17] and [100,7]. for 'Assign_24' (op: 'Assign') with input shapes: [100,17], [100,7].
Traceback (most recent call last):
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 17 and 7. Shapes are [100,17] and [100,7]. for 'Assign_24' (op: 'Assign') with input shapes: [100,17], [100,7].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/__main__.py", line 3, in <module>
    main()
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/deep.py", line 64, in main
    train_evaluate_model_from_config(pipeline_config_path)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/core/commands/train.py", line 157, in train_evaluate_model_from_config
    model = fit_chainer(config, iterator)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/core/commands/train.py", line 73, in fit_chainer
    component = from_params(component_config, mode='train')
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/core/common/params.py", line 117, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 47, in __call__
    obj.__init__(*args, **kwargs)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/models/classifiers/intents/intent_model.py", line 113, in __init__
    self.model = self.load(**params)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/DeepPavlov/deeppavlov/core/models/keras_model.py", line 157, in load
    model.load_weights(str(weights_path))
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/keras/engine/topology.py", line 2622, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/keras/engine/topology.py", line 3143, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2247, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 615, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 283, in assign
    validate_shape=validate_shape)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/mnt/c/Users/User/1_MY_WORK/1_Data_Scientist_and_ML_Project/GoodLine/DeepPavlov/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 17 and 7. Shapes are [100,17] and [100,7]. for 'Assign_24' (op: 'Assign') with input shapes: [100,17], [100,7].

**Comment by dilyararimovna** [comment]
You are trying to load some pre-trained model which shapes do not coincide with input shapes for current launch.
Please, try to check all input shapes to be the same as for pre-trained model.

**Comment by Sneg42** [comment]
ty. in pre-treained model 7 classes, but in my data i have 15 classes. I cann't find where i must change shape 7 on 15. If i use only 7 classes in my data - the model is work? but i need 15.
can you help me?

**Comment by dilyararimovna** [comment]
You should change all save and load paths (`save_path` and `load_path`) including vocab's paths (now it tries to load SNIPS pre-trained model with its 7 classes that even do not coincide with yours) and model's paths.

**Comment by dilyararimovna** [comment]
You are welcome!
