### ISSUE TITLE
Cannot run NER

### ISSUE THREAD

**Issue by zoomwe** [deepmipt/DeepPavlov#323]
Hi, thank you very much for such a great tool!

I am trying to run NER (ner_conll2003.json) model in API  mode with the following command

`python -m deeppavlov riseapi deeppavlov/configs/ner/ner_conll2003.json`

I set use_cudnn_rnn: false because I don't have GPU

But still for some reason I got an error message

```
python -m deeppavlov riseapi deeppavlov/configs/ner/ner_conll2003_pos.json 
/home/com/miniconda2/envs/py362/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[nltk_data] Downloading package punkt to /home/com/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/com/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to /home/com/nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /home/com/nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
2018-07-13 19:11:00.725 DEBUG in 'gensim.models.doc2vec'['doc2vec'] at line 73: Fast version of gensim.models.doc2vec is being used
2018-07-13 19:11:00.731 INFO in 'summa.preprocessing.cleaner'['textcleaner'] at line 20: 'pattern' package not found; tag filters are not available for English
2018-07-13 19:11:11.118 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 94: [loading vocabulary from /home/com/Shared/DeepPavlov/download/ner_conll2003/word.dict]
2018-07-13 19:11:11.145 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 94: [loading vocabulary from /home/com/Shared/DeepPavlov/download/ner_conll2003/tag.dict]
2018-07-13 19:11:11.146 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 94: [loading vocabulary from /home/com/Shared/DeepPavlov/download/ner_conll2003/char.dict]
2018-07-13 19:11:11.147 INFO in 'deeppavlov.models.embedders.glove_embedder'['glove_embedder'] at line 60: [loading embeddings from `/home/com/Shared/DeepPavlov/download/embeddings/glove.6B.100d.txt`]
2018-07-13 19:11:11.147 INFO in 'gensim.models.keyedvectors'['keyedvectors'] at line 204: loading projection weights from /home/com/Shared/DeepPavlov/download/embeddings/glove.6B.100d.txt
2018-07-13 19:11:11.148 DEBUG in 'smart_open.smart_open_lib'['smart_open_lib'] at line 149: {'kw': {}, 'mode': 'rb', 'uri': '/home/com/Shared/DeepPavlov/download/embeddings/glove.6B.100d.txt'}
2018-07-13 19:11:11.149 DEBUG in 'smart_open.smart_open_lib'['smart_open_lib'] at line 621: encoding_wrapper: {'errors': 'strict', 'encoding': None, 'mode': 'rb', 'fileobj': <_io.BufferedReader name='/home/com/Shared/DeepPavlov/download/embeddings/glove.6B.100d.txt'>}
2018-07-13 19:11:56.690 INFO in 'gensim.models.keyedvectors'['keyedvectors'] at line 266: loaded (400000, 100) matrix from /home/com/Shared/DeepPavlov/download/embeddings/glove.6B.100d.txt
2018-07-13 19:11:57.751 ERROR in 'deeppavlov.core.common.params'['params'] at line 123: Exception in <class 'deeppavlov.models.ner.network.NerNetwork'>
Traceback (most recent call last):
  File "/home/com/Shared/DeepPavlov/deeppavlov/core/common/params.py", line 117, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "/home/com/Shared/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 47, in __call__
    obj.__init__(*args, **kwargs)
  File "/home/com/Shared/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/home/com/Shared/DeepPavlov/deeppavlov/models/ner/network.py", line 104, in __init__
    units = self._build_rnn(features, n_hidden_list, cell_type, intra_layer_dropout, self.mask_ph,)
  File "/home/com/Shared/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
TypeError: _build_rnn() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "/home/com/miniconda2/envs/py362/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/com/miniconda2/envs/py362/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/com/Shared/DeepPavlov/deeppavlov/__main__.py", line 3, in <module>
    main()
  File "/home/com/Shared/DeepPavlov/deeppavlov/deep.py", line 75, in main
    start_model_server(pipeline_config_path)
  File "/home/com/Shared/DeepPavlov/utils/server_utils/server.py", line 91, in start_model_server
    model = init_model(model_config_path)
  File "/home/com/Shared/DeepPavlov/utils/server_utils/server.py", line 25, in init_model
    model = build_model_from_config(model_config)
  File "/home/com/Shared/DeepPavlov/deeppavlov/core/commands/infer.py", line 42, in build_model_from_config
    component = from_params(component_config, mode=mode)
  File "/home/com/Shared/DeepPavlov/deeppavlov/core/common/params.py", line 117, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "/home/com/Shared/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 47, in __call__
    obj.__init__(*args, **kwargs)
  File "/home/com/Shared/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/home/com/Shared/DeepPavlov/deeppavlov/models/ner/network.py", line 104, in __init__
    units = self._build_rnn(features, n_hidden_list, cell_type, intra_layer_dropout, self.mask_ph,)
  File "/home/com/Shared/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
TypeError: _build_rnn() takes 5 positional arguments but 6 were given
```

**Comment by Timopheym** [comment]
Btw. it needs gensim to run it, and it's not in requirements.txt, should i make PR?

**Comment by seliverstov** [comment]
Fixed. Gensim was added to the requirements section in `ner_conll2003_pos.json` file.
