### ISSUE TITLE
train_evaluate_model_from_config failed when train in config is empty

### ISSUE THREAD

**Issue by ismaslov** [deepmipt/DeepPavlov#366]
Конфигурация для Vocab. Тренировка не нужна, поэтому в конфигурации передаётся пустой train.
В итоге всё падает со следующим стектрейсом:

```
Traceback (most recent call last):
  File "/home/imaslov/Sand/pytest/src/test.py", line 6, in <module>
    train_evaluate_model_from_config('config/dstc2_vocab_config.json')
  File "/home/imaslov/Sand/pytest/lib/python3.6/site-packages/deeppavlov/core/commands/train.py", line 187, in train_evaluate_model_from_config
    show_examples=train_config['show_examples'])
  File "/home/imaslov/Sand/pytest/lib/python3.6/site-packages/deeppavlov/core/commands/train.py", line 211, in _test_model
    y_predicted = list(model(list(x)))
  File "/home/imaslov/Sand/pytest/lib/python3.6/site-packages/deeppavlov/core/common/chainer.py", line 102, in __call__
    return self._predict(*args, **kwargs)
  File "/home/imaslov/Sand/pytest/lib/python3.6/site-packages/deeppavlov/core/common/chainer.py", line 137, in _predict
    res = component(*x)
  File "/home/imaslov/Sand/pytest/lib/python3.6/site-packages/deeppavlov/core/data/vocab.py", line 160, in __call__
    return [self[s] for s in samples]
  File "/home/imaslov/Sand/pytest/lib/python3.6/site-packages/deeppavlov/core/data/vocab.py", line 160, in <listcomp>
    return [self[s] for s in samples]
  File "/home/imaslov/Sand/pytest/lib/python3.6/site-packages/deeppavlov/core/data/vocab.py", line 102, in __getitem__
    raise NotImplementedError("not implemented for type `{}`".format(type(key)))
NotImplementedError: not implemented for type `<class 'list'>`
```

**Comment by ismaslov** [comment]
обходится вот так, но лучше и понятнее передавать просто пустой train
```
"train": {
    "validate_best":null,
    "test_best":null
  },
```

**Comment by vikmary** [comment]
Под пустым train-ом подразумеваешь `{}` или `null`? `"train": {}` идеологически должен работать.

**Comment by ismaslov** [comment]
`{}`
сейчас не работает

**Comment by vikmary** [comment]
Приведи пример неработающего конфига. Для `configs/go_bot/go_bot_minimal.json` с пустой train секцией `"train": {}` работает.

**Comment by ismaslov** [comment]
```
{
  "dataset_reader": {
    "name": "dstc2_reader",
    "data_path": "dstc2"
  },
  "dataset_iterator": {
    "name": "dialog_iterator"
  },
  "deeppavlov_root": "./",
  "metadata": {
    "download": [
      {
        "subdir": "dstc2",
        "url": "http://files.deeppavlov.ai/datasets/dstc2_v2.tar.gz"
      }
    ]
  },
  "train": {
  },
  "chainer": {
    "in": ["utterance"],
    "in_y": [],
    "out": ["utterance_token_indices"],
    "pipe": [
      {
        "name": "default_vocab",
        "load_path": "vocabs/token.dict",
        "save_path": "vocabs/token.dict",
        "fit_on": ["utterance"],
        "in": ["utterance"],
        "out": ["utterance_token_indices"],
        "level": "token",
        "tokenizer": {"name": "split_tokenizer"}
      }
    ]
  }
}
```

```
from deeppavlov.download import deep_download
from deeppavlov.core.commands.train import train_evaluate_model_from_config
deep_download(['--config', 'config/dstc2_vocab_config.json'])
train_evaluate_model_from_config('config/dstc2_vocab_config.json')
print(vocab(['hello']))
```

**Comment by vikmary** [comment]
The config was trained fine, but broke while used for evaluation.
`train_evaluate_model_from_config` not only fits vocab on train data, but also evaluates on test data.
The config is not purposed to be used for evaluation, because inputs required by `fit()` and `__call__` methods differ.
If you intend to train the vocab, use the following config:
```
(tensorflow) [vimary@vimary-pc]: ~/ipavlov/Pilot/deeppavlov>$ vim tmp.json
{
  "dataset_reader": {
    "name": "dstc2_reader",
    "data_path": "dstc2"
  },
  "dataset_iterator": {
    "name": "dialog_iterator"
  },
  "deeppavlov_root": "./",
  "metadata": {
    "download": [
      {
        "subdir": "dstc2",
        "url": "http://files.deeppavlov.ai/datasets/dstc2_v2.tar.gz"
      }
    ]
  },
  "train": {
  },
  "chainer": {
    "in": ["utterance"],
    "in_y": [],
    "out": [],
    "pipe": [
      {
        "name": "default_vocab",
        "load_path": "vocabs/token.dict",
        "save_path": "vocabs/token.dict",
        "fit_on": ["utterance"],
        "level": "token",
        "tokenizer": {"name": "split_tokenizer"}
      }
    ]
  }
}
```

**Comment by ismaslov** [comment]
With your config I cannot build Vocab and test it
```
vocab = build_model_from_config('config/dstc2_vocab_config.json')
print(vocab(['hello']))
```
I already has workaround for my issue (see second message in this topic) but it looks strange and incomprehensible as a user api. IMHO

**Comment by vikmary** [comment]
Yeah, you should use different configs to train and evaluate the vocabulary.
But it is only the case for the `DefaultVocabulary` component and only if you use `"dialog_iterator"` `DatasetIterator`.

**Comment by ismaslov** [comment]
okay, I undertand. Thank you
