### ISSUE TITLE
Memory Error while loading embeddings

### ISSUE THREAD

**Issue by ismaslov** [deepmipt/DeepPavlov#384]
each time when im trying to train or infect my model with big embeddings (en.wiki or ru.wiki+lenta) I catch the memory error
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/imaslov/.virtualenvs/classification/lib/python3.6/site-packages/deeppavlov/__main__.py", line 3, in <module>
    main()
  File "/home/imaslov/.virtualenvs/classification/lib/python3.6/site-packages/deeppavlov/deep.py", line 66, in main
    train_evaluate_model_from_config(pipeline_config_path)
  File "/home/imaslov/.virtualenvs/classification/lib/python3.6/site-packages/deeppavlov/core/commands/train.py", line 164, in train_evaluate_model_from_config
    model = fit_chainer(config, iterator)
  File "/home/imaslov/.virtualenvs/classification/lib/python3.6/site-packages/deeppavlov/core/commands/train.py", line 73, in fit_chainer
    component = from_params(component_config, mode='train')
  File "/home/imaslov/.virtualenvs/classification/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 104, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "/home/imaslov/.virtualenvs/classification/lib/python3.6/site-packages/deeppavlov/models/embedders/fasttext_embedder.py", line 60, in __init__
    self.model = self.load()
  File "/home/imaslov/.virtualenvs/classification/lib/python3.6/site-packages/deeppavlov/models/embedders/fasttext_embedder.py", line 90, in load
    model = Fasttext.load_model(model_file)
  File "/home/imaslov/.virtualenvs/classification/lib/python3.6/site-packages/fastText/FastText.py", line 304, in load_model
    return _FastText(path)
  File "/home/imaslov/.virtualenvs/classification/lib/python3.6/site-packages/fastText/FastText.py", line 37, in __init__
    self.f.loadModel(model)
MemoryError: std::bad_alloc
```
as you can see on screenshot system still have some available free memory
https://i.imgur.com/ARoGp5e.png

so... any recommendations?

**Comment by ismaslov** [comment]
it seems embbeding-file was broken

**Comment by mOeztuerk** [comment]
@ismaslov how did you solve this? I still have this error

**Comment by mOeztuerk** [comment]
@ismaslov how did you solve this error? I still have this problem

**Comment by ismaslov** [comment]
@mOeztuerk
plz be sure that you have enough free memory. 
Also your embedding file can be corrupted. So just remove it and download again

**Comment by mOeztuerk** [comment]
@ismaslov u mean HDD or RAM memory
