### ISSUE TITLE
JSONDecodeError while loading pre trained model

### ISSUE THREAD

**Issue by imsurinder90** [deepmipt/DeepPavlov#406]
Python Version: 3.6

Installed DeepPavlov using:
`pip install DeepPavlov`

Command I ran:

`python -m deeppavlov interact ./bot_kvret_infer.json`

ERROR:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/floyd/home/deeppavlov/__main__.py", line 3, in <module>
    main()
  File "/floyd/home/deeppavlov/deep.py", line 70, in main
    interact_model(pipeline_config_path)
  File "/floyd/home/deeppavlov/core/commands/infer.py", line 93, in interact_model
    config = read_json(config_path)
  File "/floyd/home/deeppavlov/core/common/file.py", line 23, in read_json
    return json.load(fin)
  File "/usr/local/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
```

Please help if I am doing something wrong.

**Comment by vikmary** [comment]
`JsonDecodeError`occurs in case of errors in format of json file `bot_kvret_infer.json`. 
Are you using the same `bot_kvret_infer.json` as in deeppavlov? Or maybe you've edited it and missed a comma?

**Comment by imsurinder90** [comment]
I am still getting error when running following commands:

`python -m deeppavlov interact squad.json` 
`!python -m deeppavlov install squad.json`

Note: squad.json is already downloaded
and deeppavlov is installed using pip
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/deeppavlov/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/deeppavlov/deep.py", line 70, in main
    interact_model(pipeline_config_path)
  File "/usr/local/lib/python3.6/site-packages/deeppavlov/core/commands/infer.py", line 97, in interact_model
    config = read_json(config_path)
  File "/usr/local/lib/python3.6/site-packages/deeppavlov/core/common/file.py", line 21, in read_json
    return json.load(fin)
  File "/usr/local/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
```
Please help

**Comment by imsurinder90** [comment]
@vikmary sorry for the noise.

It was download issue. I provided wrong url when I used wget utitliy.
When I opened up, It was all HTML file.
Now the issue is fixed.
