### ISSUE TITLE
MemoryError: std::bad_alloc

### ISSUE THREAD

**Issue by woolh** [deepmipt/DeepPavlov#453]
Following is the error description when I try to train the config of intents_dstc2_big.json
`2018-09-15 00:13:04.117 INFO in 'deeppavlov.models.embedders.fasttext_sr/local/python36/env/lib/python3.6/site-packages/download/embeddings/
2018-09-15 00:35:24.214 ERROR in 'deeppavlov.core.common.params'['params'] at line 110: Exception in <class 'deeppavlov.models.embedders.fasttext_embedder.FasttextEmbedder'>
Traceback (most recent call last):
  File "/usr/local/python36/env/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 104, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "/usr/local/python36/env/lib/python3.6/site-packages/deeppavlov/models/embedders/fasttext_embedder.py", line 60, in __init__
    self.model = self.load()
  File "/usr/local/python36/env/lib/python3.6/site-packages/deeppavlov/models/embedders/fasttext_embedder.py", line 90, in load
    model = Fasttext.load_model(model_file)
  File "/usr/local/python36/env/lib/python3.6/site-packages/fastText/FastText.py", line 304, in load_model
    return _FastText(path)
  File "/usr/local/python36/env/lib/python3.6/site-packages/fastText/FastText.py", line 37, in __init__
    self.f.loadModel(model)
MemoryError: std::bad_alloc
Traceback (most recent call last):
  File "deep.py", line 85, in <module>
    main()
  File "deep.py", line 66, in main
    train_evaluate_model_from_config(pipeline_config_path)
  File "/usr/local/python36/env/lib/python3.6/site-packages/deeppavlov/core/commands/train.py", line 161, in train_evaluate_model_from_config
    model = fit_chainer(config, iterator)
  File "/usr/local/python36/env/lib/python3.6/site-packages/deeppavlov/core/commands/train.py", line 69, in fit_chainer
    component = from_params(component_config, mode='train')
  File "/usr/local/python36/env/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 104, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "/usr/local/python36/env/lib/python3.6/site-packages/deeppavlov/models/embedders/fasttext_embedder.py", line 60, in __init__
    self.model = self.load()
  File "/usr/local/python36/env/lib/python3.6/site-packages/deeppavlov/models/embedders/fasttext_embedder.py", line 90, in load
    model = Fasttext.load_model(model_file)
  File "/usr/local/python36/env/lib/python3.6/site-packages/fastText/FastText.py", line 304, in load_model
    return _FastText(path)
  File "/usr/local/python36/env/lib/python3.6/site-packages/fastText/FastText.py", line 37, in __init__
    self.f.loadModel(model)
MemoryError: std::bad_alloc`

what can I do now?
Is there any hardware requirements for this project?

**Comment by woolh** [comment]
> 
> 
> Hello!
> The model from `intents_dstc2_big.json` uses (and consequently loads in memory) fasttext embedding file of size 8.5Gb. If have not enough memory to use this model you can try `intents_dstc2.json` which load embedding file of size 800Mb.

Hello,
Thanks for your warm reply.
My physical memory is about 4Gb and the swaping memory is about 15Gb.
I see the occupancy of physical memory is about 99% and swapping is 45% at the first peak, and for the second peak, the physical memory reaches about 99% and swapping reaches 35%, then gradually both of the physical and swapping memory crash to less than 10%, finally the output is "MemoryError: std::bad_alloc".

Anyway, I will try `intents_dstc2.json` later.
