### ISSUE TITLE
can't install to a fresh virtual environment

### ISSUE THREAD

**Issue by tsundokum** [deepmipt/DeepPavlov#50]
`(.vipavlov) marat@dgx1:~/DeepPavlov$ pip3 install -r requirements.txt 
Collecting Cython (from -r requirements.txt (line 1))
  Downloading Cython-0.27.3-cp35-cp35m-manylinux1_x86_64.whl (3.0MB)
    100% |████████████████████████████████| 3.0MB 538kB/s 
Collecting lxml==4.1.1 (from -r requirements.txt (line 2))
  Downloading lxml-4.1.1-cp35-cp35m-manylinux1_x86_64.whl (5.5MB)
    100% |████████████████████████████████| 5.5MB 299kB/s 
Collecting tqdm==4.19.4 (from -r requirements.txt (line 3))
  Downloading tqdm-4.19.4-py2.py3-none-any.whl (50kB)
    100% |████████████████████████████████| 51kB 11.7MB/s 
Collecting requests==2.18.4 (from -r requirements.txt (line 4))
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting gensim==2.3.0 (from -r requirements.txt (line 5))
  Downloading gensim-2.3.0.tar.gz (17.2MB)
    100% |████████████████████████████████| 17.2MB 90kB/s 
Collecting tensorflow==1.4.0 (from -r requirements.txt (line 6))
  Downloading tensorflow-1.4.0-cp35-cp35m-manylinux1_x86_64.whl (40.7MB)
    100% |████████████████████████████████| 40.7MB 38kB/s 
Collecting overrides==1.9 (from -r requirements.txt (line 7))
  Downloading overrides-1.9.tar.gz
Collecting kenlm==0.0.0 (from -r requirements.txt (line 9))
  Downloading kenlm-0.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.5MB 1.0MB/s 
Collecting six==1.11.0 (from -r requirements.txt (line 10))
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting h5py==2.7.1 (from -r requirements.txt (line 11))
  Downloading h5py-2.7.1-cp35-cp35m-manylinux1_x86_64.whl (5.3MB)
    100% |████████████████████████████████| 5.3MB 336kB/s 
Collecting keras==2.1.2 (from -r requirements.txt (line 12))
  Downloading Keras-2.1.2-py2.py3-none-any.whl (304kB)
    100% |████████████████████████████████| 307kB 4.7MB/s 
Collecting pandas==0.21.1 (from -r requirements.txt (line 13))
  Downloading pandas-0.21.1-cp35-cp35m-manylinux1_x86_64.whl (25.7MB)
    100% |████████████████████████████████| 25.7MB 57kB/s 
Collecting fuzzywuzzy==0.16.0 (from -r requirements.txt (line 14))
  Downloading fuzzywuzzy-0.16.0-py2.py3-none-any.whl
Collecting fasttext==0.8.3 (from -r requirements.txt (line 15))
  Downloading fasttext-0.8.3.tar.gz (73kB)
    100% |████████████████████████████████| 81kB 9.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ym9i0nin/fasttext/setup.py", line 3, in <module>
        from Cython.Build import cythonize
    ImportError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ym9i0nin/fasttext/
`

**Comment by tsundokum** [comment]
problem has gone after i manually installed Cython and NumPy
