### ISSUE TITLE
Can't download models with `python download.py`

### ISSUE THREAD

**Issue by tsundokum** [deepmipt/DeepPavlov#51]
`(.vipavlov) marat@dgx1:~/DeepPavlov/deeppavlov$ python download.py
/home/marat/data/taskdialog/.vipavlov/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "download.py", line 24, in <module>
    from deeppavlov.core.data.utils import download, download_decompress
  File "/home/marat/data/taskdialog/.vipavlov/lib/python3.5/site-packages/deeppavlov-0.0.1-py3.5.egg/deeppavlov/__init__.py", line 1, in <module>
    from deeppavlov.core.models.keras_model import KerasModel
  File "/home/marat/data/taskdialog/.vipavlov/lib/python3.5/site-packages/deeppavlov-0.0.1-py3.5.egg/deeppavlov/core/models/keras_model.py", line 38, in <module>
    class KerasModel(Trainable, Inferable, metaclass=TfModelMeta):
  File "/home/marat/data/taskdialog/.vipavlov/lib/python3.5/site-packages/deeppavlov-0.0.1-py3.5.egg/deeppavlov/core/models/keras_model.py", line 145, in KerasModel
    sample_weight_mode=None, weighted_metrics=None, target_tensors=None):
  File "/home/marat/data/taskdialog/.vipavlov/lib/python3.5/site-packages/overrides/overrides.py", line 70, in overrides
    method.__name__)
AssertionError: No super class method found for "load"
`

**Comment by my-master** [comment]
Hi,

You should have installed Python 3.6 on your venv, it is mentioned in the [README:](https://github.com/deepmipt/DeepPavlov/blob/master/README.md#installation)
```
1. Create a virtual environment with Python 3.6
```
We didn't test it with Python 3.5, so the behavior can be unexpected.
