### ISSUE TITLE
deeppavlov.core.common.errors.ConfigError: 'Given fasttext model does NOT match fasttext model used previously to train loaded model'

### ISSUE THREAD

**Issue by dixiematt8** [deepmipt/DeepPavlov#69]
I goy the following error

Traceback (most recent call last):
  File "deep.py", line 63, in <module>
    main()
  File "deep.py", line 55, in main
    interact_model_by_telegram(pipeline_config_path, token)
  File "/home/mdixie/.conda/envs/deeppavlov/lib/python3.6/site-packages/deeppavlov-0.0.1-py3.6.egg/telegram_utils/telegram_ui.py", line 57, in interact_model_by_telegram
    model = build_model_from_config(config)
  File "/home/mdixie/.conda/envs/deeppavlov/lib/python3.6/site-packages/deeppavlov-0.0.1-py3.6.egg/deeppavlov/core/commands/infer.py", line 34, in build_model_from_config
    model = from_params(REGISTRY[model_name], model_config, vocabs=vocabs, mode=mode)
  File "/home/mdixie/.conda/envs/deeppavlov/lib/python3.6/site-packages/deeppavlov-0.0.1-py3.6.egg/deeppavlov/core/common/params.py", line 49, in from_params
    mode=kwargs['mode'])
  File "/home/mdixie/.conda/envs/deeppavlov/lib/python3.6/site-packages/deeppavlov-0.0.1-py3.6.egg/deeppavlov/core/common/params.py", line 52, in from_params
    model = cls(**dict(config_params, **kwargs))
  File "/home/mdixie/.conda/envs/deeppavlov/lib/python3.6/site-packages/deeppavlov-0.0.1-py3.6.egg/deeppavlov/core/models/tf_backend.py", line 47, in __call__
    obj.__init__(*args, **kwargs)
  File "/home/mdixie/.conda/envs/deeppavlov/lib/python3.6/site-packages/deeppavlov-0.0.1-py3.6.egg/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/home/mdixie/.conda/envs/deeppavlov/lib/python3.6/site-packages/deeppavlov-0.0.1-py3.6.egg/deeppavlov/models/classifiers/intents/intent_model.py", line 138, in __init__
    "Given fasttext model does NOT match fasttext model used previously to train loaded model")
deeppavlov.core.common.errors.ConfigError: 'Given fasttext model does NOT match fasttext model used previously to train loaded model'

**Comment by dilyararimovna** [comment]
Could you, please, provide more info: 
do you try to run pre-trained model? 
which embedding model do you use?

**Comment by dixiematt8** [comment]
I followed the instructions and ran the following command...

python deep.py interactbot skills/go_bot/config.json -t <TELEGRAM_TOKEN>

**Comment by dilyararimovna** [comment]
This error arises when one trying to download pre-trained model but provides with another embedding file (not with which it was trained).

**Comment by dilyararimovna** [comment]
This error arises when one tries to run pre-trained model with another embedding file (not this one with which it was trained).
Running the following command:
```
python deep.py interactbot skills/go_bot/config.json -t <TELEGRAM_TOKEN>
```
you are trying to run pre-trained models that previously should be downloaded within the following command:
```
python download.py
```
Did you run this command to download necessary files?

**Comment by dixiematt8** [comment]
Yes, I did as you said. It reads embedding from ../download/embeddings/dstc2_fasttext_model_100.bin 
Just as you showed in the video.

**Comment by dilyararimovna** [comment]
Unfortunately, I tried to reproduce this mistake: I initialized new environment, installed library using instruction from the main README, run go_bot interaction but I didn't faced the error above.
You have to make sure you are using the same embedding file (it should be loaded), for that you can try to calculate md5 hash sum of embedding file using `md5_hashsum` function from
```
deeppavlov/models/classifiers/intents/utils.py
```
and compare it within those one that is given in 
`download/intents/intent_cnn_opt.json`

**Comment by dixiematt8** [comment]
They are not matching. I got this 39d91fd19b0f0240b8aa1e84b4d5fba4 from deeppavlov/models/classifiers/intents/utils.py. It is not matching with 39d91fd19b0f0240b8aa1e84b4d5fba4 from download/intents/intent_cnn_opt.json

**Comment by dilyararimovna** [comment]
Could you, please, re-download model and embeddings?
For that, you have to delete download folder, and then run again:
```
python download.py
```
Maybe there were some troubles during downloading files.

**Comment by dixiematt8** [comment]
it fixed.   Now I get this error 

 python deep.py interactbot skills/go_bot/config.json -t 535843955:AAHh2Li05w27kGcONJN8qH4-Zx2s_5d9kHA
/home/mdixie/.conda/envs/dl/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[loading vocabulary from `../download/vocabs/word.dict`]
[loading vocabulary from `../download/vocabs/token.dict`]
[loading vocabulary from `../download/vocabs/tag.dict`]
[loading vocabulary from `../download/vocabs/char.dict`]
[loading vocabulary from `../download/vocabs/classes.dict`]

:: initializing `GoalOrientedBotNetwork` from saved

:: restoring checkpoint from ../download/go_bot_rnn/model 

session restored
/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:96: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
[ loading slot values from `../download/slots/slot_vals.json` ]

:: initializing `NerNetwork` from saved

:: restoring checkpoint from ../download/ner/dstc_ner_model

[loading embeddings from `../download/embeddings/dstc2_fasttext_model_100.bin`]
/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/deeppavlov-0.0.1-py3.6.egg/deeppavlov/core/models/serializable.py:48: UserWarning: No load path is set for NLTKTokenizer!
  warn("No load path is set for {}!".format(self.__class__.__name__))

:: initializing `KerasIntentModel` from saved

[ loading weights from `intent_cnn.h5` ]
/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/deeppavlov-0.0.1-py3.6.egg/deeppavlov/core/models/serializable.py:48: UserWarning: No load path is set for BoW_encoder!
  warn("No load path is set for {}!".format(self.__class__.__name__))
Exception in <class 'deeppavlov.models.tokenizers.spacy_tokenizer.SpacyTokenizer'>
Traceback (most recent call last):
  File "deep.py", line 63, in <module>
    main()
  File "deep.py", line 55, in main
    interact_model_by_telegram(pipeline_config_path, token)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/deeppavlov-0.0.1-py3.6.egg/telegram_utils/telegram_ui.py", line 57, in interact_model_by_telegram
    model = build_model_from_config(config)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/deeppavlov-0.0.1-py3.6.egg/deeppavlov/core/commands/infer.py", line 34, in build_model_from_config
    model = from_params(REGISTRY[model_name], model_config, vocabs=vocabs, mode=mode)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/deeppavlov-0.0.1-py3.6.egg/deeppavlov/core/common/params.py", line 49, in from_params
    mode=kwargs['mode'])
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/deeppavlov-0.0.1-py3.6.egg/deeppavlov/core/common/params.py", line 52, in from_params
    model = cls(**dict(config_params, **kwargs))
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/deeppavlov-0.0.1-py3.6.egg/deeppavlov/models/tokenizers/spacy_tokenizer.py", line 28, in __init__
    self.NLP = spacy.load('en')
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/spacy/util.py", line 131, in load_model_from_link
    return cls.load(**overrides)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/spacy/util.py", line 176, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/spacy/util.py", line 158, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/spacy/language.py", line 629, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/spacy/util.py", line 521, in from_disk
    reader(path / key)
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/spacy/language.py", line 616, in <lambda>
    ('vocab', lambda p: self.vocab.from_disk(p)),
  File "vocab.pyx", line 376, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 369, in spacy.vectors.Vectors.from_disk
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/spacy/util.py", line 521, in from_disk
    reader(path / key)
  File "vectors.pyx", line 348, in spacy.vectors.Vectors.from_disk.load_key2row
  File "/home/mdixie/.conda/envs/dl/lib/python3.6/site-packages/msgpack_numpy.py", line 179, in unpack
    return _unpacker.unpack(stream, encoding=encoding, **kwargs)
AttributeError: module 'msgpack._unpacker' has no attribute 'unpack'

**Comment by seliverstov** [comment]
Can you provide a little bit more details about "it is not starting on Telegram"?

**Comment by dixiematt8** [comment]
so I gave Telegram token,  and I open my open and typed /start, but it is not saying "Welcome to the UI of ..."

**Comment by seliverstov** [comment]
Have you send to bot any other messages besides of "/start"? What was the response?

**Comment by dixiematt8** [comment]
I get no response for any message.

**Comment by seliverstov** [comment]
Try to update to new version 0.0.2. 
Pull new code from _master_ and run _python setup.py develop_
Re-download pre-trained models (old pre-trained models will not work)
Run command with your own telegram token _python deep.py interactbot configs/go_bot/gobot_dstc2.json -t 464136058:BFGIezin812YaXVYdWhpgguQI0y123Cd0Vw_

**Comment by dixiematt8** [comment]
You can close this. It works.
