### ISSUE TITLE
Getting Invalid syntax Error when installing en_ranker_tfidf_wiki

### ISSUE THREAD

**Issue by TheBigBen1** [deepmipt/DeepPavlov#717]
When running following command in linux (python 3.5):
`python -m deeppavlov install en_ranker_tfidf_wiki`

I get following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/pythonfreak12/venv/lib/python3.5/site-packages/deeppavlov/__init__.py", line 19, in <module>
    from .configs import configs
  File "/home/pythonfreak12/venv/lib/python3.5/site-packages/deeppavlov/configs/__init__.py", line 54
    return f'Struct({repr(self._asdict())})'
                                           ^
SyntaxError: invalid syntax
```

I already tried changing the quotation marks in case this would an f-string related error - unfortunately didnt help

**Comment by my-master** [comment]
Hi @TheBigBen1 
`Python 3.5` is not supported, please try `Python 3.6`.

**Comment by yoptar** [comment]
Closing because of topic inactivity.
