### ISSUE TITLE
What is "'Chainer' object has no attribute 'infer'

### ISSUE THREAD

**Issue by waterwg** [deepmipt/DeepPavlov#75]
2018-03-04 14:09:23,638 (util.py:64 WorkerThread2) ERROR - TeleBot: "AttributeError occurred, args=("'Chainer' object has no attribute 'infer'",)
Traceback (most recent call last):
  File "/Users/developer/DeepPavlov/lib/python3.6/site-packages/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/Users/developer/Project/DeepPavlov/telegram_utils/telegram_ui.py", line 48, in handle_inference
    pred = model.infer(context)
AttributeError: 'Chainer' object has no attribute 'infer'
"
2018-03-04 14:09:23.638 ERROR in 'TeleBot'['util'] at line 64: AttributeError occurred, args=("'Chainer' object has no attribute 'infer'",)
Traceback (most recent call last):
  File "/Users/developer/DeepPavlov/lib/python3.6/site-packages/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/Users/developer/Project/DeepPavlov/telegram_utils/telegram_ui.py", line 48, in handle_inference
    pred = model.infer(context)
AttributeError: 'Chainer' object has no attribute 'infer'

Traceback (most recent call last):
  File "deep.py", line 60, in <module>
    main()
  File "deep.py", line 56, in main
    interact_model_by_telegram(pipeline_config_path, token)
  File "/Users/developer/Project/DeepPavlov/telegram_utils/telegram_ui.py", line 58, in interact_model_by_telegram
    init_bot_for_model(token, model)
  File "/Users/developer/Project/DeepPavlov/telegram_utils/telegram_ui.py", line 52, in init_bot_for_model
    bot.polling()
  File "/Users/developer/DeepPavlov/lib/python3.6/site-packages/telebot/__init__.py", line 264, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/Users/developer/DeepPavlov/lib/python3.6/site-packages/telebot/__init__.py", line 288, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/Users/developer/DeepPavlov/lib/python3.6/site-packages/telebot/util.py", line 107, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/Users/developer/DeepPavlov/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/developer/DeepPavlov/lib/python3.6/site-packages/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/Users/developer/Project/DeepPavlov/telegram_utils/telegram_ui.py", line 48, in handle_inference
    pred = model.infer(context)
AttributeError: 'Chainer' object has no attribute 'infer'

**Comment by waterwg** [comment]
Thanks, the error is fixed, but the bot's reply in telegram is so stranger

![screen shot 2018-03-04 at 2 51 47 pm](https://user-images.githubusercontent.com/37035049/36942993-ac1ab352-1fbb-11e8-8b60-1f7abe5de536.png)
