### ISSUE TITLE
Module fastText not found, fixing it causes memory allocation c++ error

### ISSUE THREAD

**Issue by JediKnightChan** [deepmipt/DeepPavlov#770]
When I try to execute code from goal-oriented bot example
```
from deeppavlov import build_model, configs

bot2 = build_model(configs.go_bot.gobot_dstc2_best, download=True)
bot2(['hi, i want chinese restaurant'])
bot2(['bye'])
```
I get the following error:
```
Traceback (most recent call last):
  File "/home/user/Documents/GenotekResearch2019/StudyTasks/5_deeppavlov/cafes.py", line 8, in <module>
    bot2 = build_model(configs.go_bot.gobot_dstc2_best, download=True)
  File "/home/user/Documents/GenotekResearch2019/StudyTasks/5_deeppavlov/myvenv/lib/python3.6/site-packages/deeppavlov/core/commands/infer.py", line 61, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "/home/user/Documents/GenotekResearch2019/StudyTasks/5_deeppavlov/myvenv/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 93, in from_params
    config_params = {k: _init_param(v, mode) for k, v in config_params.items()}
  File "/home/user/Documents/GenotekResearch2019/StudyTasks/5_deeppavlov/myvenv/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 93, in <dictcomp>
    config_params = {k: _init_param(v, mode) for k, v in config_params.items()}
  File "/home/user/Documents/GenotekResearch2019/StudyTasks/5_deeppavlov/myvenv/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 51, in _init_param
    param = from_params(param, mode=mode)
  File "/home/user/Documents/GenotekResearch2019/StudyTasks/5_deeppavlov/myvenv/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 80, in from_params
    model = build_model(config, serialized=serialized)
  File "/home/user/Documents/GenotekResearch2019/StudyTasks/5_deeppavlov/myvenv/lib/python3.6/site-packages/deeppavlov/core/commands/infer.py", line 61, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "/home/user/Documents/GenotekResearch2019/StudyTasks/5_deeppavlov/myvenv/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 90, in from_params
    cls = get_model(cls_name)
  File "/home/user/Documents/GenotekResearch2019/StudyTasks/5_deeppavlov/myvenv/lib/python3.6/site-packages/deeppavlov/core/common/registry.py", line 72, in get_model
    return cls_from_str(_REGISTRY[name])
  File "/home/user/Documents/GenotekResearch2019/StudyTasks/5_deeppavlov/myvenv/lib/python3.6/site-packages/deeppavlov/core/common/registry.py", line 41, in cls_from_str
    return getattr(importlib.import_module(module_name), cls_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/Documents/GenotekResearch2019/StudyTasks/5_deeppavlov/myvenv/lib/python3.6/site-packages/deeppavlov/models/embedders/fasttext_embedder.py", line 19, in <module>
    import fastText
ModuleNotFoundError: No module named 'fastText'
```

If I change "import fastText" to "import fasttext as fastText", I get the following error:
`Exception: fastText: Cannot load /home/user/.deeppavlov/downloads/embeddings/dstc2_fastText_model.bin due to C++ extension failed to allocate the memory`

**Comment by JediKnightChan** [comment]
I executed `python -m deeppavlov install gobot_dstc2` before

**Comment by vikmary** [comment]
Please try to uninstall all fasttext packages ( or create an empty virtualenv ) and rerun `python -m deeppavlov install gobot_dstc2`.

**Comment by yoptar** [comment]
Closing because of topic inactivity.
