### ISSUE TITLE
No super class method found for "load"?

### ISSUE THREAD

**Issue by lisper-inmove** [deepmipt/DeepPavlov#78]
When i call python download.py with python3.5

> Traceback (most recent call last):
  File "download.py", line 24, in <module>
    from deeppavlov.core.data.utils import download, download_decompress
  File "/home/inmove/code/deeplearning/lib/python3.5/site-packages/deeppavlov-0.0.1-py3.5.egg/deeppavlov/__init__.py", line 1, in <module>
    from deeppavlov.core.models.keras_model import KerasModel
  File "/home/inmove/code/deeplearning/lib/python3.5/site-packages/deeppavlov-0.0.1-py3.5.egg/deeppavlov/core/models/keras_model.py", line 38, in <module>
    class KerasModel(Trainable, Inferable, metaclass=TfModelMeta):
  File "/home/inmove/code/deeplearning/lib/python3.5/site-packages/deeppavlov-0.0.1-py3.5.egg/deeppavlov/core/models/keras_model.py", line 145, in KerasModel
    sample_weight_mode=None, weighted_metrics=None, target_tensors=None):
  File "/home/inmove/code/deeplearning/lib/python3.5/site-packages/overrides/overrides.py", line 70, in overrides
    method.__name__)
AssertionError: No super class method found for "load"

Plz help me thx.

**Comment by seliverstov** [comment]
Hi, can you use python 3.6? It looks like the inconsistent behavior of overrides between python 3.5 and 3.6  when metaclass used for the class creation.
