### ISSUE TITLE
Super-convergence. Division by zero Error

### ISSUE THREAD

**Issue by dilyararimovna** [deepmipt/DeepPavlov#820]
We do have some error with super convergence for both Keras and TF models that raises right after validation:
```{"valid": {"eval_examples_count": 1444, "metrics": {"ner_f1": 26.1706, "per_token_accuracy": 0.7913}, "time_spent": "0:00:01", "epochs_done": 0, "batches_seen": 0, "train_examples_seen": 0, "impatience": 0, "patience_limit": 5}}
Traceback (most recent call last):
  File "/home/dilyara/anaconda3/envs/deep36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dilyara/anaconda3/envs/deep36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dilyara/Documents/GitHub/DeepPavlov/deeppavlov/__main__.py", line 3, in <module>
    main()
  File "/home/dilyara/Documents/GitHub/DeepPavlov/deeppavlov/deep.py", line 85, in main
    start_epoch_num=args.start_epoch_num)
  File "/home/dilyara/Documents/GitHub/DeepPavlov/deeppavlov/core/commands/train.py", line 121, in train_evaluate_model_from_config
    trainer.train(iterator)
  File "/home/dilyara/Documents/GitHub/DeepPavlov/deeppavlov/core/trainers/nn_trainer.py", line 294, in train
    self.train_on_batches(iterator)
  File "/home/dilyara/Documents/GitHub/DeepPavlov/deeppavlov/core/trainers/nn_trainer.py", line 258, in train_on_batches
    self._send_event(event_name='after_batch')
  File "/home/dilyara/Documents/GitHub/DeepPavlov/deeppavlov/core/trainers/nn_trainer.py", line 228, in _send_event
    self._chainer.process_event(event_name=event_name, data=report)
  File "/home/dilyara/Documents/GitHub/DeepPavlov/deeppavlov/core/models/tf_backend.py", line 27, in _wrapped
    return func(*args, **kwargs)
  File "/home/dilyara/Documents/GitHub/DeepPavlov/deeppavlov/models/ner/network.py", line 324, in process_event
    super().process_event(event_name, data)
  File "/home/dilyara/Documents/GitHub/DeepPavlov/deeppavlov/core/models/tf_model.py", line 260, in process_event
    LRScheduledModel.process_event(self, *args, **kwargs)
  File "/home/dilyara/Documents/GitHub/DeepPavlov/deeppavlov/core/models/lr_scheduled_model.py", line 436, in process_event
    self._mom = min(1., max(0., self._mom_schedule.next_val()))
  File "/home/dilyara/Documents/GitHub/DeepPavlov/deeppavlov/core/models/lr_scheduled_model.py", line 122, in next_val
    pct = 10.0 * self.iters / self.nb
ZeroDivisionError: float division by zero
```

Learning rate optimisation part in config file is following:
```
"learning_rate_decay": "trapezoid",
"learning_rate_decay_batches": 10,
"fit_batch_size": 64,
"fit_on": [
  "x_tok_ind",
  "mask",
  "y_ind"
],
"momentum": [
  0.95,
  0.85
],
"momentum_decay": "trapezoid",
"momentum_decay_batches": 10,
```

**Comment by vikmary** [comment]
Fixed in https://github.com/deepmipt/DeepPavlov/pull/806
