### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'seek'

### ISSUE THREAD

**Issue by davidlenz** [deepmipt/DeepPavlov#851]
Hey guys, thanks for the amazing work.
When trying to get the NER (http://docs.deeppavlov.ai/en/master/components/ner.html) running i experience the following error:

```
>>> ner_model = build_model(configs.ner.ner_ontonotes_bert, download=True)
2019-05-25 12:41:01.17 INFO in 'deeppavlov.core.data.utils'['utils'] at line 63: Downloading from http://files.deeppavlov.ai/deeppavlov_data/bert/cased_L-12_H-768_A-12.zip to C:\Users\Dlenz\.deeppavlov\downloads\cased_L-12_H-768_A-12.zip
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 404M/404M [00:44<00:00, 9.07MB/s]
2019-05-25 12:41:45.667 INFO in 'deeppavlov.core.data.utils'['utils'] at line 201: Extracting C:\Users\Dlenz\.deeppavlov\downloads\cased_L-12_H-768_A-12.zip archive into C:\Users\Dlenz\.deeppavlov\downloads\bert_models
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Dlenz\Anaconda3\envs\pavlov\lib\site-packages\deeppavlov\core\commands\infer.py", line 40, in build_model
    deep_download(config)
  File "C:\Users\Dlenz\Anaconda3\envs\pavlov\lib\site-packages\deeppavlov\download.py", line 146, in deep_download
    download_resource(url, dest_paths)
  File "C:\Users\Dlenz\Anaconda3\envs\pavlov\lib\site-packages\deeppavlov\download.py", line 119, in download_resource
    download_decompress(url, download_path, dest_paths)
  File "C:\Users\Dlenz\Anaconda3\envs\pavlov\lib\site-packages\deeppavlov\core\data\utils.py", line 209, in download_decompress
    with zipfile.ZipFile(arch_file_path, 'r') as zip_ref:
  File "C:\Users\Dlenz\Anaconda3\envs\pavlov\lib\zipfile.py", line 1100, in __init__
    elif mode in ('w', 'x'):
  File "C:\Users\Dlenz\Anaconda3\envs\pavlov\lib\zipfile.py", line 1163, in _RealGetContents
    except OSError:
  File "C:\Users\Dlenz\Anaconda3\envs\pavlov\lib\zipfile.py", line 241, in _EndRecData
    #   fpin.seek(0, 2)
AttributeError: 'WindowsPath' object has no attribute 'seek'
```

It was working like a charm when using the SQUAD Model yesterday, but just keeps failing here. Google search did not really bring something up. Is the zip file maybe corrupted?

**Comment by Skvortsovg** [comment]
Hello, David! 
I just checked on my system, the zip file is OK. I believe that there is an error in the path to the file (probably with the slashes). I recommend trying to use the Centos or MacOS for development. There are no such problems there.

**Comment by davidlenz** [comment]
Hi Skvortsovg,
thanks a lot for double checking, I'll try on another OS then.

**Comment by yoptar** [comment]
Hi,

I've just tried running `ner_model = build_model(configs.ner.ner_ontonotes_bert, download=True)` on a Windows machine and it worked fine.

Is this file downloaded every time with the same result?

**Comment by davidlenz** [comment]
It is working now, great! I am unsure what happened though, so i will shortly elaborate on the issue.

So the model downloaded every time @yoptar . When i tried to reproduce this behaviour a few mins ago, it would not download at all but throw a `TimeoutError: [WinError 10060]`:
```
>>> ner_model = build_model(configs.ner.ner_ontonotes_bert, download=True)
Traceback (most recent call last):
  File "C:\Users\Dlenz\Anaconda3\envs\pavlov\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\Dlenz\Anaconda3\envs\pavlov\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\Dlenz\Anaconda3\envs\pavlov\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 
```

I decided to set `download=False` and the following error would let me know that I am missing the BERT cased model. Consequently I placed the corresponding BERT model in the directory the error pointed to and tried again, and now it is working.

I am unsure what happened, maybe you can draw more conclusions from what i described. 
I suggest closing the issue now as it is resolved. Thanks for good responsiveness!

**Comment by xelandar** [comment]
Hi! Unfortunatly I have the same issue. I'm under windows and sadly can't test on any other OS. I'm under winpython 3.6.1.0Qt5. I've installed deeppavlov by:

`pip install deeppavlov==0.5.0`

and then

`python -m deeppavlov install squad_bert`

Then I'm trying to run this code:
```
from deeppavlov import configs, build_model
ner_model = build_model(configs.ner.ner_ontonotes_bert, download=True)
ner_model(['Bob Ross lived in Florida'])
```
But after downloading and getting this on the screen:
```
2019-08-19 19:51:58.223 INFO in 'deeppavlov.core.data.utils'['utils'] at line 64: Downloading from http://files.deeppavlov.ai/deeppavlov_data/bert/cased_L-12_H-768_A-12.zip to C:\WinPython-64bit-3.6.1.0Qt5\settings\.deeppavlov\downloads\cased_L-12_H-768_A-12.zip
100%|███████████████████████████████████████| 404M/404M [01:33<00:00, 4.31MB/s]
2019-08-19 19:53:32.25 INFO in 'deeppavlov.core.data.utils'['utils'] at line 216: Extracting C:\WinPython-64bit-3.6.1.0Qt5\settings\.deeppavlov\downloads\cased_L-12_H-768_A-12.zip archive into C:\WinPython-64bit-3.6.1.0Qt5\settings\.deeppavlov\downloads\bert_models
```
I get this error:

`AttributeError: 'WindowsPath' object has no attribute 'seek'`

Any clues, how can overcome this?

**Comment by yoptar** [comment]
Hi @xelandar,
I could not reproduce this error on Windows. Could you send us a full stack trace for it?

**Comment by xelandar** [comment]
Hi @yoptar,

Thank you for your swift reply.

Try python 3.6.x to reproduce.

However, like I noted in my edit to original post I've already resolved this problem by upgrading to most recent version of winpython (and subsequently python itself).
