### ISSUE TITLE
When DeepPavlov servers are down, DeepPavlov crashes

### ISSUE THREAD

**Issue by my-master** [deepmipt/DeepPavlov#854]
Sometimes, when DeepPavlov servers are down, the old code stop working even if models are already downloaded.

```
[nltk_data] Downloading package punkt to /home/olga/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/olga/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to
[nltk_data]     /home/olga/nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /home/olga/nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
Traceback (most recent call last):
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f16091e3ac8>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='files.deeppavlov.ai', port=80): Max retries exceeded with url: /deeppavlov_data/ru_odqa.tar.gz.md5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16091e3ac8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/olga/Data/projects/qa_metrics/count_metrics.py", line 177, in <module>
    main()
  File "/media/olga/Data/projects/qa_metrics/count_metrics.py", line 111, in main
    ranker = build_model(configs.doc_retrieval.ru_ranker_tfidf_wiki, download=True)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/deeppavlov/core/commands/infer.py", line 40, in build_model
    deep_download(config)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/deeppavlov/download.py", line 146, in deep_download
    download_resource(url, dest_paths)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/deeppavlov/download.py", line 115, in download_resource
    if check_md5(url, dest_paths):
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/deeppavlov/download.py", line 80, in check_md5
    r = requests.get(url_md5)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/olga/soft/miniconda3/envs/qa_metrics/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='files.deeppavlov.ai', port=80): Max retries exceeded with url: /deeppavlov_data/ru_odqa.tar.gz.md5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16091e3ac8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

Process finished with exit code 1
```
This behaviour is really frustrating. Is it possible to try to skip file hashes checking in the case of `ConnectionError`? And if nothing still is found, just to output `FileNotFound` error?

**Comment by my-master** [comment]
For now, I have to change the code in my projects when servers are down. From this:
```
   ranker = build_model(configs.doc_retrieval.ru_ranker_tfidf_wiki, download=True)
```
to this:
```
   ranker = build_model(configs.doc_retrieval.ru_ranker_tfidf_wiki, download=False)
```

**Comment by IgnatovFedor** [comment]
It's better to raise error when files can't be downloaded than launch model with some local files that could differ from the ones user want to download. User should set `download=False` while building model or remove `-d` flag, if model is used from CLI.
