### ISSUE TITLE
error with ner rus 

### ISSUE THREAD

**Issue by serhio7** [deepmipt/DeepPavlov#856]
When I'm trying to run ner rus model on my own data I got following error "TypeError: compute() missing 1 required positional argument: 'x'" how it could be fixed?

**Comment by mu-arkhipov** [comment]
What config do you use?

**Comment by serhio7** [comment]
ner_rus. json

**Comment by mu-arkhipov** [comment]
Can you please provide the commad you run and example of the data sample?

**Comment by mu-arkhipov** [comment]
Full stack trace would be also very helpful

**Comment by serhio7** [comment]
**The command that I run**  : python -m deeppavlov train configs/ner/ner_rus.json
Here is **full stack trace**:
Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\Programs\Python\Python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\****\AppData\Local\Programs\Python\Python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\deepPVl2\DeepPavlov\dp\lib\site-packages\deeppavlov\__main__.py", line 3, in <module>
    main()
  File "D:\deepPVl2\DeepPavlov\dp\lib\site-packages\deeppavlov\deep.py", line 86, in main
    start_epoch_num=start_epoch_num)
  File "D:\deepPVl2\DeepPavlov\dp\lib\site-packages\deeppavlov\core\commands\train.py", line 228, in train_evaluate_model_from_config
    model = fit_chainer(config, iterator)
  File "D:\deepPVl2\DeepPavlov\dp\lib\site-packages\deeppavlov\core\commands\train.py", line 83, in fit_chainer
    preprocessed = chainer.compute(*iterator.get_instances('train'), targets=targets)
TypeError: compute() missing 1 required positional argument: 'x'
and here is example of the data sample:
[trn.txt](https://github.com/deepmipt/DeepPavlov/files/3232662/trn.txt)

**Comment by serhio7** [comment]
I figured it out by myself. In my data I had no separator between samples, so I just added it and all works well.
