### ISSUE TITLE
No module named 'fastText' error!

### ISSUE THREAD

**Issue by bhavykhatri** [deepmipt/DeepPavlov#877]
I want to use pretrained go chatbot on dstc2_best following the instructions in http://docs.deeppavlov.ai/en/master/skills/go_bot.html. I have installed deeppavlov using command 

> pip install deeppavlov

After that I ran 'python -m deeppavlov install gobot_dstc2'. But I am continuously getting the following error for not installing fastText even though I tried both of the command. 

>>> from deeppavlov import build_model, configs
>>> bot2 = build_model(configs.go_bot.gobot_dstc2_best, download=False)
[nltk_data] Downloading package punkt to /home/bhavy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/bhavy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to
[nltk_data]     /home/bhavy/nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /home/bhavy/nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
2019-06-11 23:06:03.68 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 103: [loading vocabulary from /home/bhavy/.deeppavlov/models/gobot_dstc2_best/word.dict]
2019-06-11 23:06:03.70 WARNING in 'deeppavlov.core.models.serializable'['serializable'] at line 47: No load path is set for Sqlite3Database in 'infer' mode. Using save path instead
2019-06-11 23:06:03.70 INFO in 'deeppavlov.core.data.sqlite_database'['sqlite_database'] at line 63: Loading database from /home/bhavy/.deeppavlov/downloads/dstc2/resto.sqlite.
2019-06-11 23:06:05.900 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 103: [loading vocabulary from /home/bhavy/.deeppavlov/models/slotfill_dstc2/word.dict]
2019-06-11 23:06:05.902 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 103: [loading vocabulary from /home/bhavy/.deeppavlov/models/slotfill_dstc2/tag.dict]
Using TensorFlow backend.
WARNING:tensorflow:From /home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/models/ner/network.py:259: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

2019-06-11 23:06:06.543540: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-11 23:06:06.605 INFO in 'deeppavlov.core.models.tf_model'['tf_model'] at line 52: [loading model from /home/bhavy/.deeppavlov/models/slotfill_dstc2/model]
INFO:tensorflow:Restoring parameters from /home/bhavy/.deeppavlov/models/slotfill_dstc2/model
/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
2019-06-11 23:06:06.642 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 103: [loading vocabulary from /home/bhavy/.deeppavlov/models/classifiers/intents_dstc2_v10/classes.dict]
Traceback (most recent call last):
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/models/embedders/fasttext_embedder.py", line 19, in <module>
    import fastText
ModuleNotFoundError: No module named 'fastText'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/core/commands/infer.py", line 61, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 97, in from_params
    config_params = {k: _init_param(v, mode) for k, v in config_params.items()}
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 97, in <dictcomp>
    config_params = {k: _init_param(v, mode) for k, v in config_params.items()}
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 51, in _init_param
    param = from_params(param, mode=mode)
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 80, in from_params
    model = build_model(config, serialized=serialized)
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/core/commands/infer.py", line 61, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 94, in from_params
    cls = get_model(cls_name)
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/core/common/registry.py", line 71, in get_model
    return cls_from_str(_REGISTRY[name])
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/core/common/registry.py", line 40, in cls_from_str
    return getattr(importlib.import_module(module_name), cls_name)
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/models/embedders/fasttext_embedder.py", line 29, in <module>
    raise ModuleNotFoundError(f'{e}\n\nYou can install fastText by running\n'
ModuleNotFoundError: No module named 'fastText'

You can install fastText by running
/home/bhavy/anaconda3/envs/pavlov/bin/python -m pip install pybind11==2.2.3 git+https://github.com/deepmipt/fastText.git#egg=fastText==0.8.22
or for your deeppavlov pipeline configuration
/home/bhavy/anaconda3/envs/pavlov/bin/python -m deeppavlov install <config_path>

**Comment by yoptar** [comment]
Hi @bhavykhatri,
Please run `python -m deeppavlov install gobot_dstc2_best`, it should help.

**Comment by bhavykhatri** [comment]
Hi @yoptar ,
FileNotFoundError: [Errno 2] No such file or directory: 'gobot_dstc_2_best'

**Comment by yoptar** [comment]
There should be no underscore before `2`. So `gobot_dstc2_best`, not `gobot_dstc_2_best`, it's the configuration file you're using in the example you've shown.

**Comment by bhavykhatri** [comment]
It gave the following error

2019-06-12 00:21:11.600 INFO in 'deeppavlov.core.common.file'['file'] at line 30: Interpreting 'gobot_dstc2_best' as '/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/configs/go_bot/gobot_dstc2_best.json'
Requirement already satisfied: tensorflow==1.10.0 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (1.10.0)
Requirement already satisfied: absl-py>=0.1.6 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from tensorflow==1.10.0) (0.7.1)
Requirement already satisfied: wheel>=0.26 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from tensorflow==1.10.0) (0.33.4)
Collecting numpy<=1.14.5,>=1.13.3 (from tensorflow==1.10.0)
  Using cached https://files.pythonhosted.org/packages/68/1e/116ad560de97694e2d0c1843a7a0075cc9f49e922454d32f49a80eb6f1f2/numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: protobuf>=3.6.0 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from tensorflow==1.10.0) (3.8.0)
Requirement already satisfied: astor>=0.6.0 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from tensorflow==1.10.0) (0.8.0)
Requirement already satisfied: grpcio>=1.8.6 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from tensorflow==1.10.0) (1.21.1)
Requirement already satisfied: six>=1.10.0 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from tensorflow==1.10.0) (1.12.0)
Requirement already satisfied: tensorboard<1.11.0,>=1.10.0 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from tensorflow==1.10.0) (1.10.0)
Requirement already satisfied: setuptools<=39.1.0 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from tensorflow==1.10.0) (39.1.0)
Requirement already satisfied: termcolor>=1.1.0 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from tensorflow==1.10.0) (1.1.0)
Requirement already satisfied: gast>=0.2.0 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from tensorflow==1.10.0) (0.2.2)
Requirement already satisfied: werkzeug>=0.11.10 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from tensorboard<1.11.0,>=1.10.0->tensorflow==1.10.0) (0.15.4)
Requirement already satisfied: markdown>=2.6.8 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from tensorboard<1.11.0,>=1.10.0->tensorflow==1.10.0) (3.1.1)
ERROR: spacy 2.1.3 has requirement numpy>=1.15.0, but you'll have numpy 1.14.5 which is incompatible.
ERROR: blis 0.2.4 has requirement numpy>=1.15.0, but you'll have numpy 1.14.5 which is incompatible.
Installing collected packages: numpy
  Found existing installation: numpy 1.16.4
    Uninstalling numpy-1.16.4:
      Successfully uninstalled numpy-1.16.4
Successfully installed numpy-1.14.5
Requirement already satisfied: pybind11==2.2.3 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (2.2.3)
Collecting fastText==0.8.22 from git+https://github.com/deepmipt/fastText.git#egg=fastText==0.8.22
  Cloning https://github.com/deepmipt/fastText.git to /tmp/pip-install-ed7t1mr1/fastText
  Running command git clone -q https://github.com/deepmipt/fastText.git /tmp/pip-install-ed7t1mr1/fastText
Requirement already satisfied: pybind11>=2.2 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from fastText==0.8.22) (2.2.3)
Requirement already satisfied: setuptools>=0.7.0 in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from fastText==0.8.22) (39.1.0)
Requirement already satisfied: numpy in ./anaconda3/envs/pavlov/lib/python3.6/site-packages (from fastText==0.8.22) (1.14.5)
Building wheels for collected packages: fastText
  Building wheel for fastText (setup.py) ... error
  ERROR: Complete output from command /home/bhavy/anaconda3/envs/pavlov/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-ed7t1mr1/fastText/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-w973myxt --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/fastText
  copying python/fastText/__init__.py -> build/lib.linux-x86_64-3.6/fastText
  copying python/fastText/FastText.py -> build/lib.linux-x86_64-3.6/fastText
  creating build/lib.linux-x86_64-3.6/fastText/util
  copying python/fastText/util/util.py -> build/lib.linux-x86_64-3.6/fastText/util
  copying python/fastText/util/__init__.py -> build/lib.linux-x86_64-3.6/fastText/util
  creating build/lib.linux-x86_64-3.6/fastText/tests
  copying python/fastText/tests/test_configurations.py -> build/lib.linux-x86_64-3.6/fastText/tests
  copying python/fastText/tests/__init__.py -> build/lib.linux-x86_64-3.6/fastText/tests
  copying python/fastText/tests/test_script.py -> build/lib.linux-x86_64-3.6/fastText/tests
  running build_ext
  creating tmp
  gcc -pthread -B /home/bhavy/anaconda3/envs/pavlov/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/bhavy/anaconda3/envs/pavlov/include/python3.6m -c /tmp/tmp57mykm3g.cpp -o tmp/tmp57mykm3g.o -std=c++14
  unable to execute 'gcc': No such file or directory
  gcc -pthread -B /home/bhavy/anaconda3/envs/pavlov/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/bhavy/anaconda3/envs/pavlov/include/python3.6m -c /tmp/tmp7ie40tl1.cpp -o tmp/tmp7ie40tl1.o -std=c++11
  unable to execute 'gcc': No such file or directory
  gcc -pthread -B /home/bhavy/anaconda3/envs/pavlov/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/bhavy/anaconda3/envs/pavlov/include/python3.6m -c /tmp/tmprncyxa44.cpp -o tmp/tmprncyxa44.o -std=c++0x
  unable to execute 'gcc': No such file or directory
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-ed7t1mr1/fastText/setup.py", line 175, in <module>
      zip_safe=False,
    File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-install-ed7t1mr1/fastText/setup.py", line 120, in build_extensions
      opts.append(cpp_flag(self.compiler))
    File "/tmp/pip-install-ed7t1mr1/fastText/setup.py", line 92, in cpp_flag
      'Unsupported compiler -- at least C++0x support '
  RuntimeError: Unsupported compiler -- at least C++0x support is needed!
  ----------------------------------------
  ERROR: Failed building wheel for fastText
  Running setup.py clean for fastText
Failed to build fastText
Installing collected packages: fastText
  Running setup.py install for fastText ... error
    ERROR: Complete output from command /home/bhavy/anaconda3/envs/pavlov/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-ed7t1mr1/fastText/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-psaqc0he/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/fastText
    copying python/fastText/__init__.py -> build/lib.linux-x86_64-3.6/fastText
    copying python/fastText/FastText.py -> build/lib.linux-x86_64-3.6/fastText
    creating build/lib.linux-x86_64-3.6/fastText/util
    copying python/fastText/util/util.py -> build/lib.linux-x86_64-3.6/fastText/util
    copying python/fastText/util/__init__.py -> build/lib.linux-x86_64-3.6/fastText/util
    creating build/lib.linux-x86_64-3.6/fastText/tests
    copying python/fastText/tests/test_configurations.py -> build/lib.linux-x86_64-3.6/fastText/tests
    copying python/fastText/tests/__init__.py -> build/lib.linux-x86_64-3.6/fastText/tests
    copying python/fastText/tests/test_script.py -> build/lib.linux-x86_64-3.6/fastText/tests
    running build_ext
    gcc -pthread -B /home/bhavy/anaconda3/envs/pavlov/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/bhavy/anaconda3/envs/pavlov/include/python3.6m -c /tmp/tmp5gre4p7d.cpp -o tmp/tmp5gre4p7d.o -std=c++14
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/bhavy/anaconda3/envs/pavlov/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/bhavy/anaconda3/envs/pavlov/include/python3.6m -c /tmp/tmpgv3vy8lt.cpp -o tmp/tmpgv3vy8lt.o -std=c++11
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/bhavy/anaconda3/envs/pavlov/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/bhavy/anaconda3/envs/pavlov/include/python3.6m -c /tmp/tmpvxu7a7f3.cpp -o tmp/tmpvxu7a7f3.o -std=c++0x
    unable to execute 'gcc': No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ed7t1mr1/fastText/setup.py", line 175, in <module>
        zip_safe=False,
      File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-install-ed7t1mr1/fastText/setup.py", line 120, in build_extensions
        opts.append(cpp_flag(self.compiler))
      File "/tmp/pip-install-ed7t1mr1/fastText/setup.py", line 92, in cpp_flag
        'Unsupported compiler -- at least C++0x support '
    RuntimeError: Unsupported compiler -- at least C++0x support is needed!
    ----------------------------------------
ERROR: Command "/home/bhavy/anaconda3/envs/pavlov/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-ed7t1mr1/fastText/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-psaqc0he/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-ed7t1mr1/fastText/
Traceback (most recent call last):
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/__main__.py", line 3, in <module>
    main()
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/deep.py", line 126, in main
    install_from_config(pipeline_config_path)
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/utils/pip_wrapper/pip_wrapper.py", line 44, in install_from_config
    install(r)
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/site-packages/deeppavlov/utils/pip_wrapper/pip_wrapper.py", line 23, in install
    env=os.environ.copy())
  File "/home/bhavy/anaconda3/envs/pavlov/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/bhavy/anaconda3/envs/pavlov/bin/python', '-m', 'pip', 'install', 'git+https://github.com/deepmipt/fastText.git#egg=fastText==0.8.22']' returned non-zero exit status 1.

**Comment by yoptar** [comment]
Looks like fastText requires [gcc-4.8 compiler or newer](https://github.com/facebookresearch/fastText/tree/master/python#requirements). So if you're on Ubuntu you can try running `sudo apt install gcc-4.8`.
I usually do `sudo apt install python3-pip` as it should also install everything needed.

**Comment by bhavykhatri** [comment]
Thanks a lot @yoptar . Today was my meeting I was getting this error in last couple of days. You saved me. Also learnt to not only look at the last message but to also see if there is some other error which is causing this error.

**Comment by yoptar** [comment]
You are more than welcome, I'm glad I could help.
If you're having other questions about DeepPavlov, please don't hesitate to open new issues.
