### ISSUE TITLE
Metrics for levenshtein spelling correction model

### ISSUE THREAD

**Issue by vikmary** [deepmipt/DeepPavlov#966]
Wanted to calculate a metric score of a [levenshtein model](https://github.com/deepmipt/DeepPavlov/blob/0.5.0/deeppavlov/configs/spelling_correction/levenshtein_corrector_ru.json) for the SpellRuEval dataset (`F1 = 56.25` according to the [doc page](http://docs.deeppavlov.ai/en/master/features/models/spelling_correction.html#comparison)).

But `python3 -m deeppavlov evaluate levenshtein_corrector_ru -d` got the following error:

```2019-08-12 14:50:51.426 WARNING in 'deeppavlov.core.commands.train'['train'] at line 100: Train config is missing. Populating with default values
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vimary/code-projects/Pilot/deeppavlov/__main__.py", line 3, in <module>
    main()
  File "/home/vimary/code-projects/Pilot/deeppavlov/deep.py", line 87, in main
    train_evaluate_model_from_config(pipeline_config_path, to_train=False, start_epoch_num=args.start_epoch_num)
  File "/home/vimary/code-projects/Pilot/deeppavlov/core/commands/train.py", line 106, in train_evaluate_model_from_config
    if 'evaluation_targets' not in train_config and ('validate_best' in train_config
TypeError: argument of type 'NoneType' is not iterable```

**Comment by yoptar** [comment]
Scores in the documentation were calculated using an external scorer that's not included in the library yet. We can share it on request.
