### ISSUE TITLE
System cannot find file specified .deeppavlov/downloads/bert_models/cased_L-12_H-768_A-12/vocab.txt

### ISSUE THREAD

**Issue by cponce-uncc** [deepmipt/DeepPavlov#984]
Hi, I installed deeppavlov on my mac system without any issues, but when attempting to use it after installation on Windows I received this error:

"B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\Scripts\python.exe" "B:/Cristian/Code/PycharmProjects copy/projectEdith/named_entity_recognition.py"
2019-09-02 21:25:49.206 INFO in 'deeppavlov.core.common.file'['file'] at line 30: Interpreting 'ner_ontonotes_bert' as 'B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\deeppavlov\configs\ner\ner_ontonotes_bert.json'
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Cristian\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Cristian\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to
[nltk_data]     C:\Users\Cristian\AppData\Roaming\nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     C:\Users\Cristian\AppData\Roaming\nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
WARNING:tensorflow:From B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\bert_dp\tokenization.py:125: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

2019-09-02 21:25:51.558 ERROR in 'deeppavlov.core.common.params'['params'] at line 110: Exception in <class 'deeppavlov.models.preprocessors.bert_preprocessor.BertNerPreprocessor'>
Traceback (most recent call last):
  File "B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\deeppavlov\core\common\params.py", line 104, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\deeppavlov\models\preprocessors\bert_preprocessor.py", line 116, in __init__
    do_lower_case=do_lower_case)
  File "B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\bert_dp\tokenization.py", line 165, in __init__
    self.vocab = load_vocab(vocab_file)
  File "B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\bert_dp\tokenization.py", line 127, in load_vocab
    token = convert_to_unicode(reader.readline())
  File "B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 178, in readline
    self._preread_check()
  File "B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\Cristian\.deeppavlov\downloads\bert_models\cased_L-12_H-768_A-12\vocab.txt : The system cannot find the path specified.
; No such process
Traceback (most recent call last):
  File "B:/Cristian/Code/PycharmProjects copy/projectEdith/named_entity_recognition.py", line 6, in <module>
    model = build_model('ner_ontonotes_bert', download=False)
  File "B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\deeppavlov\core\commands\infer.py", line 61, in build_model
    component = from_params(component_config, mode=mode, serialized=component_serialized)
  File "B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\deeppavlov\core\common\params.py", line 104, in from_params
    component = cls(**dict(config_params, **kwargs))
  File "B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\deeppavlov\models\preprocessors\bert_preprocessor.py", line 116, in __init__
    do_lower_case=do_lower_case)
  File "B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\bert_dp\tokenization.py", line 165, in __init__
    self.vocab = load_vocab(vocab_file)
  File "B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\bert_dp\tokenization.py", line 127, in load_vocab
    token = convert_to_unicode(reader.readline())
  File "B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 178, in readline
    self._preread_check()
  File "B:\Cristian\Code\PycharmProjects copy\projectEdith\venv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\Cristian\.deeppavlov\downloads\bert_models\cased_L-12_H-768_A-12\vocab.txt : The system cannot find the path specified.
; No such process

**Comment by yoptar** [comment]
Hi @cponce-uncc,
Did you download required files for the model? For example, by running `build_model('ner_ontonotes_bert', download=True)`

Also the path in this error looks weird, specifically the `Users\Cristian.deeppavlov\downloads` part, as it should be `Users\Cristian\.deeppavlov\downloads`.
Was the `ner_ontonotes_bert.json` file changed?

**Comment by cponce-uncc** [comment]
I had the download argument set to False when I transferred the code over, that was exactly why- thank you for the quick response and help!
